### ISSUE TITLE
Build problem in iOS

### ISSUE THREAD

**Issue by marcelofb** [AppsFlyerSDK/appsflyer-react-native-plugin#104]
# Report

## Plugin Version

1.4.4

## On what Platform are you having the issue?

iOS

## What did you do?

Run `react-native run-ios`

## What did you expect to happen?

Build success

## What happened instead?

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AppsFlyerCrossPromotionHelper", referenced from:
      objc-class-ref in libRNAppsFlyer.a(RNAppsFlyer.o)
  "_OBJC_CLASS_$_AppsFlyerShareInviteHelper", referenced from:
      objc-class-ref in libRNAppsFlyer.a(RNAppsFlyer.o)
  "_OBJC_CLASS_$_AppsFlyerTracker", referenced from:
      objc-class-ref in libRNAppsFlyer.a(RNAppsFlyer.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by faycito** [comment]
Same here.

**Comment by kuzyakiev** [comment]
Same happens for me. react-native: 0.59.8
**steps**
`yarn add react-native-appsflyer`
`react-native link`
clear all cached files and folders
`react-native run-ios`

**Comment by kuzyakiev** [comment]
For me fixed:
Go to https://github.com/AppsFlyerSDK/react-native-appsflyer/blob/master/Docs/Installation.md
Find: Manual Integration (Integrating without Cocoapods)

So 
1) [download SDK](https://s3-eu-west-1.amazonaws.com/download.appsflyer.com/ios/AppsFlyerLib.framework.zip) , put somewhere
2) open in Xcode RNAppsFlyer.xcodeproj
3) navigate to PROJECT > RNAppsFlyer, Tab **Build Settings** > Search Paths > **Framework Search Paths**
4) Add the link to a folder which has **AppsFlyerLib.framework** 
5) Clean Build Folder
6) Build App in Xcode or run `react-native run-ios`

**Comment by marcelofb** [comment]
@kuzyakiev where have you located the framework and how have you referenced it?

**Comment by marcelofb** [comment]
@kuzyakiev where have you located the framework and how have you referenced it?

**Comment by marcelofb** [comment]
@kuzyakiev where have you located the framework and how have you referenced it?

**Comment by JustinKasad** [comment]
Updating the 'react-native-appsflyer' pod to 5.0 fixed this issue for me

`pod update react-native-appsflyer`

**Comment by mustafaskyer** [comment]
thanks @JustinKasad 
```
pod update AppsFlyerFramework
```
*Solved issue for me ✅*
-- -
`"react-native": "^0.59.10"`
`"react-native-appsflyer": "^5.1.3"`

**Comment by pentolbakso** [comment]
this is what I did  ( rn 0.61.5 for appsflyer 5.2.0 ). basically, install AppsFlyer sdk first before installing rn sdk

- add `pod 'AppsFlyerFramework', '~>5.2.0'` to your pod file
- pod install
- yarn add react-native-appsflyer
- pod install
- done
