### ISSUE TITLE
RN 0.60+ support and Android X

### ISSUE THREAD

**Issue by quachsimon** [AppsFlyerSDK/appsflyer-react-native-plugin#107]
We are looking to update our project to the latest version of RN (v0.60.5) and going through the docs I could not find anything on updating react-native-appsflyer.

All I know is there are breaking changes with 0.60 in regards to Android X and I was wondering if this is in the pipeline somewhere that may be addressed?

Has anyone run into any issues with v0.60+?

Thanks

**Comment by mikaoelitiana** [comment]
@quachsimon  Yes I am having issues on iOS with RN 0.60.4

```
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    react-native-appsflyer (from `../node_modules/react-native-appsflyer`) was resolved to 1.1.12, which depends on
      React/Core
```

**Comment by artechventure** [comment]
Any updates? We are trying to update rn 59 to 60 too

**Comment by faycito** [comment]
Hello, for android X error u must be put this line
`multiDexEnabled true` on your android/app/build.gradle  file and build it.

**Comment by rmamtaventures** [comment]
Any update for 0.60?

**Comment by Bang9** [comment]
I'm not problem with RN0.60.4(migarted from 0.59.3) with current version of AppsFlyer

If you have any problem with android-x, you can use `jetifier`
`npm install --save jetifier`
