### ISSUE TITLE
Missing support for React Native 0.61+

### ISSUE THREAD

**Issue by jonzakhip** [AppsFlyerSDK/appsflyer-react-native-plugin#120]
#94 Report

## Plugin Version
react-native-appsflyer 1.4.6

## On what Platform are you having the issue?
ios

## What did you do?
pod install

## What did you expect to happen?
libraries to be installed

## What happened instead?
No podspec found for `CxxBridge` in `../node_modules/react-native`

## Please provide any other relevant information.
I think the React Native libraries changed, and the installation guided for react native appsflyer sdk has not being updated a long time.

**Comment by wesfieldj** [comment]
@jonzakhip thanks for reporting the issue. We are looking into it, and we will make the necessary updates asap. 

Thanks!

**Comment by neyosoft** [comment]
Please update the documentation for React Native 0.61+
I need to set up the library on an existing React Native 0.61.4 project but the documentation is not up to date.

Thanks.

**Comment by af-fess** [comment]
#121
