### ISSUE TITLE
onInstallConversionData is not called

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [AppsFlyerSDK/appsflyer-react-native-plugin#126]
# Report

## Plugin Version

"react-native-appsflyer": "^1.4.5"
com.appsflyer:af-android-sdk:4.10.2
## On what Platform are you having the issue?

android

## What did you expect to happen?

I need response data from onInstallConversionData callback when I install from google play store

## What happened instead?
I installed from playstore via onelink invite link but onInstallConversionData from code dosn't generate any response.
When I run  Debug mode,I got following error in InitSDK function
Error: You attempted to set the key `onInstallConversionDataListener` with the value `true` on an object that is meant to be immutable and has been frozen.

**Comment by wesfieldj** [comment]
@Murugeshrockey-RN can you please provide a code snippet of the AppsFlyer init code and onInstallConversionDataListener method? 

It would be best if you can email AppsFlyer support with your issue, and they can provide you with optimal support. You can email them at support@appsflyer.com.

**Comment by JinYuSha0** [comment]
@Murugeshrockey-RN 
#128 This might be useful for you
