### ISSUE TITLE
API docs for sendDeepLinkData are incorrect

### ISSUE THREAD

**Issue by Liamandrew** [AppsFlyerSDK/appsflyer-react-native-plugin#134]
# Report

The docs for the function sendDeepLinkData are incorrect and instead of saying it accepts a callback function it should say that it accepts a string as the url of the deep link.

In fact, attempting to provide a function would cause the app to crash.

I have a small PR to fix this although I don't seem to have permissions to push to this repo.

**Comment by AshishKapoor** [comment]
Interesting...

**Comment by af-fess** [comment]
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/index.js#L101-L103

So far it is deprecated, we are going to remove it
