### ISSUE TITLE
appsflyer support expo? 

### ISSUE THREAD

**Issue by alaminopu** [AppsFlyerSDK/appsflyer-react-native-plugin#137]
Expo is a great a tool for building `react-native` app. is there any way to make `react-native-appsflyer` work with Expo?

**Comment by af-fess** [comment]
Generally yes, It should.
We will add additional steps for Expo

**Comment by FatBuTa** [comment]
@af-fess how about this? can I use react-native-appsflyer for my Expo

**Comment by SeePhilRun** [comment]
> We need to add the plugin to their repo
> We will add additional steps for Expo

@af-fess any idea when this will be completed?

**Comment by masiamj** [comment]
This would be a huge win for AppsFlyer!

**Comment by yann-jacquet** [comment]
Has someone successfully implemented AppsFlyer in an Expo app ? Do we have to eject or is there a way around ?

**Comment by SeePhilRun** [comment]
we opted to go with Branch.io which is unfortunate because I have used
appsflyer in several other apps.

**Comment by af-fess** [comment]
We talk with Expo team to accomplish the integration.

**Comment by zinlinphyo** [comment]
This is a must-have library for my project. Really appreciate that.

**Comment by Asadi123** [comment]
Appflyer is essential on my expo project, hope we get it soon.

**Comment by TrustyTechSG** [comment]
Please, otherwise I have no option but to choose  Branch.io

**Comment by bradherman** [comment]
Also +1 on getting this integration!

**Comment by SimonHausdorf** [comment]
+1, this is an important feature

**Comment by samlogan** [comment]
Any updates team?

**Comment by JCBsystem** [comment]
+1

**Comment by af-margot** [comment]
Hi, 

A new expo plugin, which will work with the AppsFlyer plugin, will be released in a few months!

**Comment by af-fess** [comment]
We work very close with expo developers and most of the integration is already done. We cannot release the support because expo new wrapper for the RN plugin is in beta stage. as @af-margot mentioned, it will be ready in a few months.

**Comment by fedecarli** [comment]
Any updates?

**Comment by jonatasfernandespimenta** [comment]
Hey, is there any updates?

**Comment by shanejones** [comment]
Also looking for this to work with Expo.

**Comment by af-margot** [comment]
Hi everyone, 
You can find expo updates about the subject [here](https://blog.expo.io/expo-application-services-eas-build-and-submit-fc1d1476aa2e).

**Comment by markstreich** [comment]
@af-margot thank you for the update. Do I understand correctly that the piece quoted below is needed for Appsflyer? Or is there something else in that article that is blocking using Appsflyer w/ expo?

> <img width="767" alt="Screen Shot 2021-02-05 at 15 50 14" src="https://user-images.githubusercontent.com/1214573/107042022-e996e580-67c9-11eb-98d9-8db8cc388d3a.png">

**Comment by liamhession** [comment]
I just need to do the one call to `setCustomerUserId` to complete this AppsFlyer + Mixpanel integration our godforsaken marketing team would like. Does anyone know a way i could make that happen with just a barebones HTTP call, or somehow with the existing `appsflyer-react-native-plugin`, if we've got this complication of using expo?

**Comment by af-margot** [comment]
Hi @markstreich, 
Sorry for the late answer, I miss this message. 
Yes, it's exactly that! If you have more questions about expo, please feel free to contact our [support](support@appsflyer.com)!

**Comment by af-margot** [comment]
Hi @liamhession, 
Please contact our [support team](support@appsflyer.com) for specific questions!

**Comment by akichim21** [comment]
Hi.
Is version 41 of expo going to fix this issue?
https://github.com/expo/expo/blob/master/CHANGELOG.md

**Comment by marvin-42** [comment]
any news about this integration?

**Comment by lazevedo** [comment]
any updates on this? appsflyer seems to be a good fit for our application, but ejecting is not a possibility for us right now

**Comment by DaanvK** [comment]
Any news, team expo?

**Comment by slytter** [comment]
+1

**Comment by gustavbang** [comment]
+1 huge importance to our app

**Comment by mateusw3c** [comment]
Any news?

**Comment by trin4ik** [comment]
+1, need this

**Comment by trin4ik** [comment]
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/tree/dev/RD-63289%2Fadd-expo

is it stable?

**Comment by Firanolfind** [comment]
Hello? Any updates

**Comment by lorenzosinisi** [comment]
Is https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/tree/dev/RD-63289%2Fadd-expo working? Anyone tried?

**Comment by trin4ik** [comment]
> Is https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/tree/dev/RD-63289%2Fadd-expo working? Anyone tried?

no its not. we move to `expo eject`. its needs make bundles yourself, but gives u some useful features. like Sentry with native crash.
anyway, we ready to move back to eas and waits for AF team

**Comment by lorenzosinisi** [comment]
Alright thank you @trin4ik !

**Comment by trin4ik** [comment]
some new info, mb its help you @lorenzosinisi, @Firanolfind, @lazevedo, @urionafacu, etc

we moved from `eas` to `expo eject`, but now i see, in sdk42 available `expo-dev-clients` (https://docs.expo.dev/clients/getting-started/)
its mean, u can build your own expo-go app with any custom packages. 

what u need?
1. `expo install expo-dev-clients react-native-appsflyer` add dev-clients and appsflyer
2. `eas build -p all --profile development` create eas build for ios/android
3. install build on phone. on https://expo.dev interfaces goto `project > builds > your build` and click install. 
4. `expo start --dev-client` start expo in dev-client mode
5. run your installed bundle on ios/android phone. 
6. profit...

we make app for kids, and we need strict mode appsflyer. who need it too, i recommended fork package and modify podspec file: https://github.com/trin4ik/appsflyer-react-native-plugin/commit/477020a1b2526c1d13c74bdfff32206ff4288cc1
and your first step: 
1. `expo install expo-dev-clients https://github.com/trin4ik/appsflyer-react-native-plugin` please, dont use my fork, i can remove it or modify for our project

be happy ) 
p.s. Im not found a better way to change the podfile than fork the package, if anyone knows - write pls

**Comment by trin4ik** [comment]
its tested and works

**Comment by lorenzosinisi** [comment]
Hi @trin4ik thank you! Did you get the app working on the local simulator running "expo start --dev-client --ios"? When I tried (after following your instructions) I get a URL similar to "exp+ourappname://expo-development-client/?url=http%3A%2F%2F192.168.0.238%3A8081" that doesn't work anymore with the expo client. Did you face the same issue?

**Comment by lorenzosinisi** [comment]
Hi @trin4ik how did you get the simulator working instead? Once using `expo start --dev-client` I get the following message: 


```
project is not installed. Please build and install the client on the simulator first.
Learn more.
Error: The development client (OUR BUNDLE ID) for this project is not installed. Please build and install the client on the simulator first.
Learn more.
```

But I have no idea how to install the dev client on the simulator, the only thing installed there is Expo Go. Anyone has ideas on how to run expo dev client on a simulator for both android and ios? 

I have enabled EAS but not I can't get the simulators to work anymore :/ Super frustrating 

cc @af-fess

**Comment by slytter** [comment]
We have created a fingerprint-based solution for attribution, that has 5x'ed our marketing performance. If anyone is interested, contact me at nikolaj@climaider.com

**Comment by alekseiaksenov** [comment]
> some new info, mb its help you @lorenzosinisi, @Firanolfind, @lazevedo, @urionafacu, etc
> 
> we moved from `eas` to `expo eject`, but now i see, in sdk42 available `expo-dev-clients` (https://docs.expo.dev/clients/getting-started/) its mean, u can build your own expo-go app with any custom packages.
> 
> what u need?
> 
> 1. `expo install expo-dev-clients react-native-appsflyer` add dev-clients and appsflyer
> 2. `eas build -p all --profile development` create eas build for ios/android
> 3. install build on phone. on https://expo.dev interfaces goto `project > builds > your build` and click install.
> 4. `expo start --dev-client` start expo in dev-client mode
> 5. run your installed bundle on ios/android phone.
> 6. profit...
> 
> we make app for kids, and we need strict mode appsflyer. who need it too, i recommended fork package and modify podspec file: [trin4ik@477020a](https://github.com/trin4ik/appsflyer-react-native-plugin/commit/477020a1b2526c1d13c74bdfff32206ff4288cc1) and your first step:
> 
> 1. `expo install expo-dev-clients https://github.com/trin4ik/appsflyer-react-native-plugin` please, dont use my fork, i can remove it or modify for our project
> 
> be happy ) p.s. Im not found a better way to change the podfile than fork the package, if anyone knows - write pls

Thank you so much! Worked for me exactly as you described.

**Comment by JamieGarcia123** [comment]
So are we stuck having to Eject expo to use Appsflyer?

**Comment by lorenzosinisi** [comment]
You don’t have to, you can also just upgrade to eas build ***@***.***_sinisi/how-to-add-uxcam-and-appsflyer-to-expo-projects-without-ejecting-eas-e2a2545b743f it worked for us

Best,
Lorenzo Sinisi

**Comment by Dakuan** [comment]
We'll be using branch.io instead

**Comment by NoelDiazMesa** [comment]
Is there any other solution?. I have the same error when initSdk.

TypeError: null is not an object (evaluating 'RNAppsFlyer.initSdkWithPromise')

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.14",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-picker/picker": "2.1.0",
    "@react-navigation/bottom-tabs": "~5.11.7",
    "@react-navigation/drawer": "~5.12.3",
    "@react-navigation/native": "~5.9.2",
    "@react-navigation/stack": "~5.14.2",
    "axios": "^0.21.1",
    "expo": "^43.0.0",
    "expo-status-bar": "~1.1.0",
    "lodash": "^4.17.21",
    "pouchdb-adapter-asyncstorage": "^6.4.1",
    "pouchdb-react-native": "^6.4.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-appsflyer": "^6.4.40",
    "react-native-elements": "~1.2.7",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-i18n-localize": "^1.0.4",
    "react-native-image-overlay": "^0.1.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-reanimated": "~2.2.0",
    "react-native-render-html": "^6.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-screens-swiper": "^1.1.12",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.13.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

**Comment by vileikis** [comment]
@trin4ik thanks for pointing out **expo-dev-client** https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/137#issuecomment-916424711. I was happy to see app running and there is no native module error for appsflyer lib. 
Tested on dev client and Testflight builds, lib loads and tracking seem to work for both so far.

**Comment by trin4ik** [comment]
> @trin4ik thanks for pointing out **expo-dev-client** [#137 (comment)](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/137#issuecomment-916424711). I was happy to see app running and there is no native module error for appsflyer lib. Tested on dev client and Testflight builds, lib loads and tracking seem to work for both so far.

welcome. offtopic? expo-dev-client -- one love

**Comment by Bruno-Meowtel** [comment]
2 years have passed and it seems this is still unavailable unless you eject from expo or use EAS builds? We've been using branch.io and were considering switching, not anymore :(

**Comment by smn-snkl** [comment]
Small input from my side, you can also do the following to activate the Strict Mode:

1. Install `expo-dev-client` and `react-native-appsflyer`
2. Add a custom config plugin, as described [here](https://gist.github.com/jakobo/a0a989018e12e2de0a400c9f39e887e2) with the following changes:
```
function addStrictMode(src) {
    return mergeContents({
        tag: `appsflyer-strict-mode`,
        src,
        newSrc: "$RNAppsFlyerStrictMode=true",
        anchor: /platform :ios/,
        offset: 0,
        comment: "# AppsFlyer Strict Mode",
    }).contents;
}

export const withAppsFlyerChanges = (c) => {
    return withDangerousMod(c, [
        "ios",
        async (config) => {
            const file = path.join(config.modRequest.platformProjectRoot, "Podfile");
            const contents = await readFileAsync(file);
            await saveFileAsync(file, addStrictMode(contents));
            return config;
        },
    ]);
};

module.exports = (config) => withPlugins(config, [withAppsFlyerChanges]);
```
3. Run `expo run:ios -d` to run a custom dev client on your connected device

**Comment by diegosquid** [comment]
Now expo has the prebuild feature, and it's pretty straightforward now
In my case, I only need for Android, so I just:

- Install ApssFlyer SDK
- run: expo prebuild
- call appsFlyer.initSdk in App.js
- build it using eas: eas build -p android

Done!

**Comment by amit-kremer93** [comment]
@smn-snkl we are currently working on a solution very similar to your approach and we will let you know in this thread when we will release it.

**Comment by illi-homz** [comment]
`@smn-snkl we are currently working on a solution very similar to your approach and we will let you know in this thread when we will release it.`

really needed

**Comment by illi-homz** [comment]
> @smn-snkl we are currently working on a solution very similar to your approach and we will let you know in this thread when we will release it.

really needed

**Comment by amit-kremer93** [comment]
We released a new version (6.6.0) that supports integration with expo managed app + 'Strict mode'. please read the instructions related to expo and also take al look in the expo sample app.

**Comment by ddinchev** [comment]
@amit-kremer93 I'm unable to make it work with managed worfklow. Please check my issue, I've provided a repository with minimal example that illustrates the issues I hit:
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/391

**Comment by pehagg** [comment]
The Expo integration docs are utter and complete 💩 . For example, the initSdk params are not properly documented as is the app.json example as well. I spent an entire day trying to make this plugin work without IDFA and strict mode, which should according to AF docs be possible, to no avail.

Also, prompting people to contact support in the issues leaves no trace of what was done to resolve the issues. Extremely frustrating to even try to piece together the missing parts from the docs via GitHub issue. Also, you link quite a lot to docs that don't exists anymore. I won't even bother pointing them out, feel the pain like we do and figure it out for yourself.

People seem to recommend branch, so I'm heading there next. 😡

**Comment by Robinkv1994** [comment]
I am using expo 48.0.15,i want to integrate the AppsFlyer Sdk in expo but , i am getting error Type Error: Cannot read property 'initSdkWithCallBack' of null
Anyone can me help me out

**Comment by aremu-smog** [comment]
> I am using expo 48.0.15,i want to integrate the AppsFlyer Sdk in expo but , i am getting error Type Error: Cannot read property 'initSdkWithCallBack' of null
> Anyone can me help me out

Any chance you got a solution to this? I am currently working on integrating expo as well and I get the same issue on Android.

**Comment by aremu-smog** [comment]
> I am using expo 48.0.15,i want to integrate the AppsFlyer Sdk in expo but , i am getting error Type Error: Cannot read property 'initSdkWithCallBack' of null
> Anyone can me help me out

Any chance you got a solution to this? I am currently working on integrating Apps flyer  as well and I get the same issue on Android.

**Comment by mzduc01** [comment]
the same with me now
