### ISSUE TITLE
Uninstalls not being tracked

### ISSUE THREAD

**Issue by Estebank94** [AppsFlyerSDK/appsflyer-react-native-plugin#146]
# Report

## Plugin Version

v5.2.0

## On what Platform are you having the issue?

iOS and Android

## What did you do?

Installed AppsFlyer following the install guide.
Checked that the project keys are correct.
Checked that initSdk and updateupdateServerUninstallToken return success.

Wait at least 24 hours for results in Android...
All other events are being tracked correctly, however uninstalls are not being tracked.

## What did you expect to happen?

Uninstall being tracked

## What happened instead?

Uninstall wasn't tracked

## Please provide any other relevant information.

It wasn't working on version 1.4.2 either.

**Comment by wesfieldj** [comment]
@Estebank94 can you please provide us with the app_id for ios and android?

Alternatively, you can open a ticket to AppsFlyer support by emailing support@appsflyer.com.
The support team will be able to help you solve this issue.

Thanks!
