### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mifi** [AppsFlyerSDK/appsflyer-react-native-plugin#149]
Maybe some of these are self explanatory, but I'm trying to setup this but I find some of the documentation is a bit vague:

1. `initSdk` - when to call this? Do we need to make sure that `initSdk` promise has returned **before** we start calling other methods like `trackAppLaunch`, meaning we have to wait for it to return **before** calling `AppRegistry.registerComponent('App', () => App);`?
2. `initSdk` resolves a `result`, what is this? an object?
3. `updateServerUninstallToken` resolves with a `success`. When will this be false?
4. `updateServerUninstallToken` Where to put this method call and what token to input? Should it be run after `const token = await firebase.messaging().getToken();` ?

**Comment by af-margot** [comment]
Hi,
 Thank you for your message. We are currently working on improving the plugin and as a result, some parts of the documentation might not be totally up-to-date.  To help you with your questions :
 1. `initSDK `is already calling `trackAppLaunch`, so there is no need to call if after. To measure sessions between background/foreground transitions in Android we listen to those transitions.
 In iOS, we cannot listen to those transitions, so we are using the app state, like mention in the doc. This is the only place where you need to call` trackAppLaunch` as following :
  ```
_handleAppStateChange = (nextAppState) => {
  if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
   if (Platform.OS === 'ios') {
    appsFlyer.trackAppLaunch();
   }
  }
  this.setState({appState: nextAppState});
 };
```
2.For now, you can use `initSDK` without the promise. It has two callbacks, both returning a String, one with “success” and the other one with an error message.
3. For now, `updateServerUninstallToken` will always return success. 
4.For iOS, you need to pass the device Token to `updateServerUninstallToken`, and for Android, you need to pass the firebase token. You can call it, as soon as you get both tokens and after AppsFlyer is initialized. 

I hope this is more clear.

**Comment by mifi** [comment]
Thanks for your clarifications.

4. can we also call updateServerUninstallToken with the firebase token on iOS so that we can use the same code on both platforms? ([as you suggest here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#second-method)). If not, which token to send to updateServerUninstallToken on ios?

**Comment by af-margot** [comment]
Hi, 

[Our uninstall measurement](https://support.appsflyer.com/hc/en-us/articles/210289286-Uninstall-measurement#ios-uninstall) depends on Apple Push Notification for iOS and Firebase Messaging for Android. Then for iOS, you need to pass [the device token](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1) to register to Apns services. You can use a third-party library to get this device token. Another option to implement the uninstall feature for iOS is to do it from the AppDelegate to automatically get the device token. More info [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#first-method).

**Comment by mifi** [comment]
Ok, so we cannot use FCM token on iOS too if using `react-native-firebase`, correct?

**Comment by af-margot** [comment]
Yes, correct. But you can get the APNs token with firebase using this [API](https://rnfirebase.io/reference/messaging#getAPNSToken). Please note that this is only a suggestion and there are other ways to get the APNs token.

**Comment by mingyjongo** [comment]
To harp on the `updateServerUninstallToken` method some more, does that mean something like this should work?
```typescript
const getToken = Platform.select({
  android: firebase.messaging().getToken,
  ios: firebase.messaging().ios.getAPNSToken,
})
const token = getToken ? await getToken() : null
if (token) appsFlyer.updateServerUninstallToken(token, () => {})
```

Does this functionality require the Android and iOS steps in [these guides](https://support.appsflyer.com/hc/en-us/articles/210289286) as well? (FCM Server Key for Android, P12 Certificate upload for iOS)

**Comment by mifi** [comment]
That's what I did. Note that `firebase.messaging().ios.getAPNSToken()` sometimes returns null, so it needs some retry or extra precautions. See https://github.com/invertase/react-native-firebase/issues/1990#issuecomment-631892469

**Comment by diegodorado** [comment]
+1 for improving documentation.

I was surprised that initialization forced us to use callbacks, and then looking at the code I see that promises are also accepted.

I the documentation missing because it is not going to be matained or why is it not there as an alternative example?
