### ISSUE TITLE
onInstallConversionData return Error connection to server: 400 (Only on Android)

### ISSUE THREAD

**Issue by idanlevi1** [AppsFlyerSDK/appsflyer-react-native-plugin#150]
`onInstallConversionData` return failure only on an android platform (on ios it works well)

## Plugin Version

ℹ `5.2.0`

## On what Platform are you having the issue?

ℹ android

## What did you do?

ℹ Install the plugin, put `onInstallConversionData`, `onAppOpenAttribution` and `initSdk` in the contructor (in this order) 

## What did you expect to happen?

ℹ When I open the app with deep link `onInstallConversionData` will not fail

## What happened instead?

ℹ When I open the app with deep link i get 
```
{
  "data": "Error connection to server: 400",
  "status": "failure",
  "type": "onInstallConversionFailure"
} 
```
on`onInstallConversionData` function

## Please provide any other relevant information.

ℹ react-native: 0.61.0

**Comment by af-fess** [comment]
Be sure your device is white listed and you registered your app package

**Comment by idanlevi1** [comment]
> Be sure your device is white listed and you registered your app package

How i can check it?

**Comment by wesfieldj** [comment]
@idanlevi1  you can email support@appsflyer.com regarding this issue and they will be able to help you get this solved. 


You can also set isDebug to true and initSDK, and provide the debug logs for us to check, but it will be better to do this through AppsFlyer support. 

Thanks!

**Comment by idanlevi1** [comment]
I added `<meta-data android:name="CHANNEL" android:value="standalone"/>` in `AndroidManifest.xml` and this solved the problam

**Comment by glocore** [comment]
I faced this issue because my package name (in AndroidManifest, MainActivity and MainApplication) was not the same as my `applicationId` in app/build.gradle. My app was already published on the Play Store, and so AppsFlyer automatically picked up the applicationId from there. But the SDK seems to check the package name instead of applicationId, so make sure that the two of them match.
