### ISSUE TITLE
[Android] Configure deep link with onNewIntent - build failed

### ISSUE THREAD

**Issue by idanlevi1** [AppsFlyerSDK/appsflyer-react-native-plugin#156]
## Plugin Version
`5.2.0`

## On what Platform are you having the issue?
`android`

## What did you do?

I try to configure like the new README file - i added this function in `MainActivity.java` inside: `android/app/src/main/java/com...` 
```
  @Override
  protected void onNewIntent(Intent intent) {
      super.onNewIntent(intent);
      setIntent(intent);
  }
```

## What did you expect to happen?
App running...

## What happened instead?
Build failed:
```
/projectMainActivity.java:42: error: cannot find symbol
  protected void onNewIntent(Intent intent) {
                             ^
  symbol:   class Intent
  location: class MainActivity
/project/MainActivity.java:42: error: onNewIntent(Intent) in MainActivity cannot override onNewIntent(Intent) in ReactActivity
  protected void onNewIntent(Intent intent) {
                 ^
  attempting to assign weaker access privileges; was public
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

## Please provide any other relevant information.
react-native -v: `0.61.5`

**Comment by af-vs** [comment]
Hi @idanlevi1!

Thank you for reporting this! Indeed, there was a mistake in the documentation, that we have just fixed. Access level modifier of `onNewIntent(Intent intent)` method should be `public` and not `protected`

Please let us know if that doesn't help

**Comment by idanlevi1** [comment]
> Hi @idanlevi1!
> 
> Thank you for reporting this! Indeed, there was a mistake in the documentation, that we have just fixed. Access level modifier of `onNewIntent(Intent intent)` method should be `public` and not `protected`
> 
> Please let us know if that doesn't help

Can you tell me what this method does?

**Comment by af-vs** [comment]
@idanlevi1 When Android Activity uses launchMode other than standard, every new launch of the app that was running in the background will not replace the intent used to launch the app from the cold state by default. This will lead to the situation when our SDK will get the same intent on every background-foreground transition and won't be able to handle and report deep linking correctly. 

onNewIntent method allows replacing original intent with the one that was just used to launch the app.

You can read more about it here - https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)
