### ISSUE TITLE
Implementing app user opt-in/opt-out at installation

### ISSUE THREAD

**Issue by denisk20** [AppsFlyerSDK/appsflyer-react-native-plugin#157]
Recently an article was posted suggesting that all appflyer clients should implement user opt-in/opt-out functionality. One option is to opt-in during installation: 
https://support.appsflyer.com/hc/en-us/articles/360001422989#optout-at-installation
According to the article, if the user hasn't opted in during the installation, the `startTracking` method shouldn't be called. However, I can't see how to omit calling this method when calling `initSdk` method. `startTracking` is called every time when `initSdk` is called, regardless of the parameters passed:
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java#L147
There should be a way to postpone calling `startTracking` when calling `initSdk`, and call it only if a user opts-in.

A workaround for now is to call `stopTracking` when we figure that the user opts-out, but that's not ideal, `startTracking` shouldn't be called at all before the user opts-in.

**Comment by af-vs** [comment]
Hi @denisk20!

At the moment we would suggest treating `initSdk()` of the plugin equal to `startTracking()` of the native SDK. Therefore, if you implementing opt-in approach in your app, please restrain from calling `intiSdk()` until user gives their consent.

In future, we are planning on aligning the plugin APIs with the native APIs. Once done we will make sure to update our documentation to reflect the changes.

Thank you!
