### ISSUE TITLE
setSharingFilterForAllPartners support

### ISSUE THREAD

**Issue by denisk20** [AppsFlyerSDK/appsflyer-react-native-plugin#158]
The following APIs are missing from the plugin:
https://support.appsflyer.com/hc/en-us/articles/207032126#api-reference-setsharingfilterforallpartners
https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-integration-for-developers#api-reference-%C2%A0setsharingfilterforallpartners
Any plans on supporting them?

**Comment by af-vs** [comment]
Hi @denisk20!

Yes, these APIs will be added in the upcoming release of the plugin

**Comment by af-vs** [comment]
@denisk20 We just released 5.4.1 that includes those APIs. Feel free to check it out!
