### ISSUE TITLE
iOS project doesn't compile with 5.4.1

### ISSUE THREAD

**Issue by denisk20** [AppsFlyerSDK/appsflyer-react-native-plugin#163]
The errors are:

No visible @interface for 'AppsFlyerTracker' declares the selector 'setSharingFilterForAllPartners'
No visible @interface for 'AppsFlyerTracker' declares the selector 'performOnAppAttributionWithURL:'
No visible @interface for 'AppsFlyerTracker' declares the selector 'setSharingFilter:'

![image](https://user-images.githubusercontent.com/3080318/86945438-b0be6180-c151-11ea-9a2a-ae4ae5db6714.png)

**Comment by af-vs** [comment]
@denisk20 Can you please `cd` into `ios` subfolder in your project and run `pod update`? This should solve the issue

![image](https://user-images.githubusercontent.com/50541317/86952415-a1441600-c15b-11ea-8cc6-312b97efeb34.png)

**Comment by denisk20** [comment]
This worked! Only had to update the AppsFlyerFramework like this
`pod update AppsFlyerFramework`
Thanks!
