### ISSUE TITLE
Android SDK got response code 403

### ISSUE THREAD

**Issue by pqminh** [AppsFlyerSDK/appsflyer-react-native-plugin#164]
#Report

## Plugin Version
appsflyer: I'm trying `5.2.0` and `5.4.1`
react-native: 0.62.2

## On what Platform are you having the issue?
`android`

## What did you do?
1. Add appsflyer package
2. Add two app in dashboard with type android out of store
- App 1 - Staging:
+ appid: com.abc.app.stg
+ channel: abc
- App 2 - Production:
+ appid: com.abc
+ channel: productionabc
3. Add
`<meta-data android:name="CHANNEL" android:value="productionabc"/>`
to AndroidManifest.xml

## What did you expect to happen?
onInstallConversionData event success.

## What happened instead?
get response 403
`
D/AppsFlyer_5.2.0: Calling onConversionFailure with:
    Error connection to server: 403
I/ReactNativeJS: 'onInstallConversionData', { status: 'failure',
      type: 'onInstallConversionFailure',
      data: 'Error connection to server: 403' }
I/AppsFlyer_5.2.0: AttributionIdFetcher response code: 403  url: https://gcdsdk.appsflyer.com/install_data/v4.0/com.......?devkey=Y********************9&device_id=1594192632930-1171085345471451321
`

## Please provide any other relevant information.
![appsflyer-apps](https://user-images.githubusercontent.com/13993984/87117836-c8a5fa80-c2a3-11ea-9b3b-a3f8522f5268.png)
![appsflyer-apps-2](https://user-images.githubusercontent.com/13993984/87117839-c9d72780-c2a3-11ea-8b59-58150d561c3a.png)
![appsflyer-apps-3](https://user-images.githubusercontent.com/13993984/87117842-ca6fbe00-c2a3-11ea-9b42-d3356754ff90.png)

**Comment by af-vs** [comment]
Hi @pqminh!

403 probably means a mismatch in the dev key or app_id (when using channel it is considered to be part of the app_id in AppsFlyer). After a quick check, I am not able to find an app in your account that would use channel "productionabc" that you have specified in the Android Manifest.

Please, open a ticket to our support team and they will assist you in setting up "out of store" channel properly

Thank you!

**Comment by pqminh** [comment]
Sorry, I has contact support team and issue was resolved

**Comment by aleksandrmozgovoi** [comment]
I also have a 403 error. Tech support is not responding. How can I find a solution?

**Comment by AllenLiu20210507** [comment]
> Sorry, I has contact support team and issue was resolved

How did you solve the issue?

**Comment by PanCrucian** [comment]
i solve, u need upgrade Zero plan to paid for mobile
