### ISSUE TITLE
Different behavior of calling onInstallConversionData

### ISSUE THREAD

**Issue by artyorsh** [AppsFlyerSDK/appsflyer-react-native-plugin#165]
# Report

`onInstallConversionData` is being called each time the app starts, (also marking this with `is_first_launch`, which works fine) on iOS. However, it seems that this function is being called only the time the app is installed on Android.
This seems to be not really an issue, but this makes the `is_first_launch` useless and may result with a different behavior in the app.  

## Plugin Version

ℹ Please replace these two lines with the plugin version.
e.g. via `5.4.1`

## On what Platform are you having the issue?

Both Android and iOS are affected, not sure which one works the right way.

ℹ Please replace these two lines with the SDK version.
iOS: AppsFlyerFramework (~> 5.4.1)

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be tracked

I'd expect the same behavior on both platforms, so that `onInstallConversionData` is called each time the app starts.

**Comment by af-vs** [comment]
Hi @artyorsh!

`onInstallConversionData`  should be invoked in every app open, regardless if it is opened for the first time after install, from killed state or from the background. If that is not the case for you, we will need to check AppsFlyer debug logs (prefixed with `AppsFlyer_` tag) from the **Android logcat** generated on the first launch after the install and another portion of logs generated when you launch the app but not getting the callback.

Thank you!

**Comment by artyorsh** [comment]
@af-vs Thanks for your reply.
Fortunately, it _is_ invoked. It seems to be I had some Metro caching issues. Sorry for the wrong information.
