### ISSUE TITLE
Problem with Android integration

### ISSUE THREAD

**Issue by SaintNekit** [AppsFlyerSDK/appsflyer-react-native-plugin#169]
trying to integrate AppsFlyer to my project using this lib, on Android launch get error - "Cannot read property 'initSdk' of undefined". When console logging object before initialization - there is some object, not undefined.

# Report

## Plugin Version

"react-native-appsflyer": "^5.4.1",
"react-native": "0.61.5",

## On what Platform are you having the issue?

Android

## What did you do?

just install package and call the function initSdk from App.tsx file

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be tracked

## What happened instead?

App will work and AppsFlyer will track my application downloading 

## Please provide any other relevant information.

Try to integrate AppsFlyer manually from their docs, but Android Studio send me this error - "I/AppsFlyerOaid5.4.0: Fetch
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;" - don't know if it would help.

**Comment by af-vs** [comment]
Hi @SaintNekit!

Sorry for not getting back earlier. I see you have closed the issue. Will appreciate if you could share a few words about what was the the solution. Thank you!

**Comment by SaintNekit** [comment]
Problem was with our firebase integration, not with appsflyer lib. We just rewrite firebase logic and appsflyer start to work perfectly

  
>Четверг, 6 августа 2020, 15:28 +03:00 от Vitaly Sokolov <notifications@github.com>:
> 
> 
>Hi  @SaintNekit !
>Sorry for not getting back earlier. I see you have closed the issue. Will appreciate if you could share a few words about what was the the solution. Thank you!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Nikita Stepanovs

**Comment by af-vs** [comment]
Thank you @SaintNekit!

Glad to hear you are good to go! :)
