### ISSUE TITLE
Cannot read property 'initSdk' of undefined

### ISSUE THREAD

**Issue by lesocheck** [AppsFlyerSDK/appsflyer-react-native-plugin#171]
reinstall and autolinking didn't work.
`TypeError: Cannot read property 'initSdk' of undefined`
`"react": "16.13.1",
 "react-native": "0.63.2",
 "react-native-appsflyer": "^5.4.1",`

**Comment by af-vs** [comment]
Hi @lesocheck!

Can you please share you initialization code?

**Comment by af-vs** [comment]
Hi @lesocheck! Were you able to solve the issue?

**Comment by lesocheck** [comment]
No.
`appsFlyer.initSdk(
        {
          devKey: 'tzTMezPNAAJ2jKPjNJezui',
          isDebug: false
        },
        (result) => {
              console.log(result);
          },
            (error) => {
              console.error(error);
            }
          );`

**Comment by af-vs** [comment]
Hi @lesocheck!

It seems that the `appsFLyer` object in your case is undefined. Please check your import statements from our module, make sure they are added to all files where you intend to use appsFlyer object.

The import statement should look like:
`import appsFlyer from 'react-native-appsflyer';`

 Also worth checking if you indeed have appsflyer folder in node_modules of your project. If not, run `npm install react-native-appsflyer --save`

Lastly, I suggest you perform those actions in an empty project. If issue doesn't happen, you can add more complexity to the new project, imitating your real app structure until you start getting the error again.
