### ISSUE TITLE
[iOS] How to disable IDFA? 

### ISSUE THREAD

**Issue by curiousdustin** [AppsFlyerSDK/appsflyer-react-native-plugin#172]
# Report
How can we disable IDFA collection when using this React Native version of AppsFlyer?

[This documentation](https://support.appsflyer.com/hc/en-us/articles/360001422989#disable-idfa-collection) describes how to remove the `AdSupport` framework from an Xcode project using the native SDK.

However, this does not appear to be possible when using this React Native version of the SDK.

When I attempt to follow the instructions, AdSupport is not in the list. Instead it is just `$(inherited)`, which DOES contain `AdSupport`, but is coming from the autogenerated pods config file.

## Plugin Version

5.2.0

## On what Platform are you having the issue?

ios

**Comment by curiousdustin** [comment]
The solution provided in #173 does not remove the framework(s) from the app as described in the [documentation for native SDK](https://support.appsflyer.com/hc/en-us/articles/360001422989#disable-idfa-collection). How do we do this as well?

**Comment by smn-snkl** [comment]
Wondering about the same thing.
