### ISSUE TITLE
[iOS] How to use `disableIAdTracking`

### ISSUE THREAD

**Issue by curiousdustin** [AppsFlyerSDK/appsflyer-react-native-plugin#173]
# Report

I would like to disable IDFA collection and the use of `iAd` framework.

There are links in the documentation for the native SDK [here](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V5-integration-for-developers#integration-2-adding-the-sdk-to-your-app).

> [disableIAdTracking](https://support.appsflyer.com/hc/en-us/articles/207032066#api-reference-disableiadtracking)

However, I do not see how to access the `disableIAdTracking` option via the API documented for this React Native version of the SDK.

## Plugin Version

5.2.0

## On what Platform are you having the issue?

ios

**Comment by af-vs** [comment]
Hi @curiousdustin!

Thanks for reporting this one. We just released the new version 5.4.40 with the 2 new APIs:

disableAdvertiserIdentifier - to disable IDFA collection
disableCollectASA - to disable iAd framework

I will close this issue as well as your [second related issue](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/172), feel free to open new ones if you encounter any problems.

Thank you!

**Comment by curiousdustin** [comment]
These new APIs are great. Thank you. 

However, these are for run time. 

Part of my question was that I would like to remove the _AdSupport_ and _iAd_ frameworks completely from the app. 

The instructions for the native SDK setup provide steps to do this. How can I apply these steps when using React Native?

**Comment by smn-snkl** [comment]
Having the same question over here.

**Comment by af-vs** [comment]
@curiousdustin @smn-snkl I believe this can be solved from the native SDK side, I am checking with native iOS SDK developers.

In the meantime, can you try the steps [described here](https://support.appsflyer.com/hc/en-us/articles/360001422989#disable-idfa-collection) for your iOS project? You still should be able to open the `ios` folder from your React Native project in Xcode and perform steps listed in the instructions. 

Let us know how it goes, thanks!

**Comment by curiousdustin** [comment]
For anyone else looking, this also pertains to #172.

I cannot follow those steps in my React Native project. Here is why:

On step 4, I do see that `AdSupport` and `iAd` frameworks on in the `Other Linker Flags` section of Build Settings.

![image](https://user-images.githubusercontent.com/1706540/92749559-72a51000-f343-11ea-9da2-9dd870729f8e.png)

However, on step 5, when I try to edit this, all I see is `${inherited)`, `-ObjC`, and `-lc++`.

![image](https://user-images.githubusercontent.com/1706540/92750029-ea733a80-f343-11ea-890a-2405fc9bffd0.png)

So, I cannot follow step 6 to remove the linker flags.

I believe that this is a result of using CocoaPods, which is default in recent versions of React Native.

When digging deeper, I determined that `react-native-appsflyer` does not add these framework linker flags directly. They get added by the `AppsFlyerFramework` pod that is defined as a dependency in the `react-native-appsflyer` podspec.

My current (unsustainable) solution is to fork the `AppsFlyerFramework` repo, and remove the linker flags. Then patch the `react-native-appsflyer` podspec file to remove the dependency, and instead, install my forked version in my project Podfile.

This is a very hacky workaround, so I am hoping your team can provide a more elegant and sustainable solution.

**Comment by af-vs** [comment]
@curiousdustin you got it right. We are working with `AppsFlyerFramework` developers to exclude this dependency from the podspec or provide other viable solution

**Comment by curiousdustin** [comment]
@af-vs Any update on this?

**Comment by af-fess** [comment]
The native SDK iOS 6.0.1 is under test. I believe next week. CC @curiousdustin

**Comment by curiousdustin** [comment]
6.0.3 of which repo?

Release notes here already talk about 6.0.3 released weeks ago: https://support.appsflyer.com/hc/en-us/articles/115001224823#ios-sdk-v6-release-notes

I see no commits related to this request on https://github.com/AppsFlyerSDK/AppsFlyerFramework

Is there anything I can look at even though it isn't officially released?

**Comment by af-vs** [comment]
@curiousdustin sorry for the confusion. This is planned for 6.0.4 of native SDK, thus, it will affect React Native 6.0.40. Native SDK with the relevant changes is being tested. Not sure about ETA, but promise to keep you posted.

Thank you for your understanding!

**Comment by curiousdustin** [comment]
Apple is currently rejecting our app because of IDFA collection.

We need to be **_certain_** that AppsFlyer is not collecting IDFA.

What is the timeline to have `6.0.40` released?

**Comment by amit-kremer93** [comment]
Hi @curiousdustin 6.0.40 will be release next week

**Comment by amit-kremer93** [comment]
version 6.0.50 with iOS sdk 6.0.5 has released.
If you still have this issue, please contact us!

**Comment by curiousdustin** [comment]
@amit-kremer93 , you closed this without answering this question:

> I cannot follow those steps in my React Native project. Here is why:
> 
> On step 4, I do see that `AdSupport` and `iAd` frameworks on in the `Other Linker Flags` section of Build Settings.
> 
> ![image](https://user-images.githubusercontent.com/1706540/92749559-72a51000-f343-11ea-9da2-9dd870729f8e.png)
> 
> However, on step 5, when I try to edit this, all I see is `${inherited)`, `-ObjC`, and `-lc++`.
> 
> ![image](https://user-images.githubusercontent.com/1706540/92750029-ea733a80-f343-11ea-890a-2405fc9bffd0.png)
> 
> So, I cannot follow step 6 to remove the linker flags.

Does 6.0.50 completely remove reliance on `AdSupport` and `iAd`, without any extra steps?

**Comment by amit-kremer93** [comment]
@curiousdustin now you should be able to remove the frameworks according to [this](https://support.appsflyer.com/hc/en-us/articles/360001422989#disable-idfa-collection) guide

**Comment by curiousdustin** [comment]
@amit-kremer93, sorry I do not understand.

**Comment by curiousdustin** [comment]
@amit-kremer93, sorry I do not understand what to do.

After updating to `6.0.50`, my xcode project appears the same as I described before.

I cannot remove the frameworks from the other linker flags because they are inherited from the apps flyer pods.

Can you please point me to the commits that you feel should have resolved this issue? All I see in the commit logs are simple version changes, nothing that would appear to manipulate how things are linked.

**Comment by amit-kremer93** [comment]
@curiousdustin sorry for misleading you. iOS sdk does not relies on AdSupport and iAd, so it should work without any extra steps by you.
![Screen Shot 2020-10-21 at 13 56 06](https://user-images.githubusercontent.com/61827664/96711412-333bfb80-13a6-11eb-9d12-5a904d670378.png)

**Comment by curiousdustin** [comment]
I will check this shortly. 

Does this mean that iOS sdk 6.0.5 NEVER uses AdSupport or iAd frameworks, even when you do not need to disable IDFA collection?

Can you explain how this works? How then do you get the IDFA when in fact an app DOES intend to allow IDFA collection?

Or does this mean that now there is an additional, opposite, setup step in which a developer would need to add the frameworks into their project, instead of remove them?

**Comment by curiousdustin** [comment]
Thank you, I can see that AppsFlyer iOS SDK `6.0.5` is indeed being used in my project now.

I can also see that neither `iAd` nor `AdSupport` frameworks are in the inherited other linker flags.

Still curious about my questions above.

**Comment by curiousdustin** [comment]
Also, should `appsFlyer.disableAdvertisingIdentifier(true)` be called before or after `initSDK`?

**Comment by amit-kremer93** [comment]
yes. `appsFlyer.disableAdvertisingIdentifier(true)` should be called before `initSDK`

**Comment by curiousdustin** [comment]
Thanks. Any answers on my other question?
