### ISSUE TITLE
[IOS] doesn't populate data in AppsFlyer.com similar to Android 

### ISSUE THREAD

**Issue by CallmeKingsley** [AppsFlyerSDK/appsflyer-react-native-plugin#175]
## Plugin Version
"react-native-AppsFlyer": "^5.4.1",
"react": "16.8.6",
"react-native": "0.60.0",

## On what Platform are you having the issue?
IOS and Not Andriod

## What did you do?
I have tested the SDK implementation and It returns successfully. I am not if I need to turn on Ios tracking on the site and how

**Comment by af-vs** [comment]
Hi @CallmeKingsley!

I have a feeling it will be more efficient to approach our support team at support@appsflyer.com, but I will be happy to take a look to better understand the problem first.

Can you please specify your iOS and Android app IDs in AppsFlyer? If you don't feel comfortable sharing any of this in a public GitHub thread, please close the issue and reach out to the Support Team to investigate.

Thank you!

**Comment by CallmeKingsley** [comment]
@af-vs thanks for a quick response. here is the Applw ld 1452962191 and the android com.nationsphotolab.photoapp

**Comment by af-vs** [comment]
@CallmeKingsley Hey, thanks for sharing this info! I can see several organic installs on iOS which indicates that SDK sends the data. The issue you may have is most likely in improper SDK initialization or misunderstanding of the AppsFlyer attribution model. 

Also, I see that the Android app has some non-organic traffic attributed to 1 of our partners which iOS doesn't. This is related to the integration with the partner and attribution and not related to the SDK. I suggest you reaching out to our Support Team as we only handle plugin-related issues in this repo. Support will be able to investigate the full data flow.

Thank you!
