### ISSUE TITLE
onAppOpenAttribution don't return af_dp

### ISSUE THREAD

**Issue by lucasaugustin** [AppsFlyerSDK/appsflyer-react-native-plugin#182]
# Report

## Plugin Version
5.2.0

## On what Platform are you having the issue?
ios

## What did you do?
open app using an onelink.

## What did you expect to happen?
onAppOpenAttribution to be called and return with all atributes data (af_dp and others)

data:
af_dp: "br.com.myapp://app-section"
af_force_deeplink: "true"
af_ios_url: "https://www.appsflyer.com/"
link: "https://myapp.onelink.me/wZZ4/MD"

## What happened instead?
onAppOpenAttribution was called, but the return data didn't have any info about the onelink that was used. 
```
data: {
 link: "br.com.myapp://google/link/?dismiss=1&is_weak_match=1"
},
status: "success"
type: "onAppOpenAttribution"
```

## Please provide any other relevant information.
This only happens on ios. On android, it works as expected.

**Comment by af-vs** [comment]
Hi @lucasaugustin!

This happens because you probably process deep links via Firebase SDK first. Please check your AppDelegate `continueUserActivity` and `openURL` methods if you process links by different SDKs. We suggest that you first process the links by AppsFlyer SDK or create some condition to decide which links would be processed by AppsFlyer and which by Firebase.

**Comment by lucasaugustin** [comment]
hi @af-vs.

This seems to be an intermittent issue.
we have updated the plugin version to 6.0.30 and now most devices work as expected, but there is one where the error continues to happen.
 
Our `continueUserActivity` and `openURL` methods only have the Appsflyer use.

`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString*)sourceApplication annotation:(id)annotation {
 [[AppsFlyerLib shared] handleOpenURL:url sourceApplication:sourceApplication withAnnotation:annotation];
return YES;
}`

`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary *) options {
[[AppsFlyerLib shared] handleOpenUrl:url options:options];`

But we do use firebase in our project, so i guess the error is related to this.
The problem is that we need configure it inside the `didFinishLaunchingWithOptions`, that is used before the `continueUserActivity` and `openURL` methods.

There is any other way that we can fix this problem?
