### ISSUE TITLE
Inaccurate initSdk TypeScript signature

### ISSUE THREAD

**Issue by willcaul** [AppsFlyerSDK/appsflyer-react-native-plugin#194]
# Report

## Plugin Version

6.0.30

## On what Platform are you having the issue?

ios and android

## What did you do?

TypeScript types for `initSdk` are not correct

## What did you expect to happen?

When only 1 arg is passed to `initSdk`, TypeScript should be able to infer that the return type is a `Promise`.

## What happened instead?

TypeScript thinks that the return type is a `Response`, which could be could be `void` or a `Promise`

<img width="158" alt="Screen Shot 2020-10-07 at 4 03 49 PM" src="https://user-images.githubusercontent.com/34461499/95591413-426d9180-0a15-11eb-8063-e0fa6fa1e311.png">

<img width="447" alt="Screen Shot 2020-10-07 at 4 04 24 PM" src="https://user-images.githubusercontent.com/34461499/95591424-46011880-0a15-11eb-8445-cbb20ce1797f.png">

## Please provide any other relevant information.

I opened a PR to fix this issue, but it was closed with no explanation. Can this PR please be reopened or responded to?: 
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/187

I also had a PR to fix this same issue for the `logEvent` function, but it was also closed without explanation:
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/189

**Comment by amit-kremer93** [comment]
Hey @willcaul !
Your code updates will be included in the next react-native plugin version (6.0.33) with additional api.
Thank you for your understanding.

**Comment by willcaul** [comment]
> Hey @willcaul !
> Your code updates will be included in the next react-native plugin version (6.0.33) with additional api.
> Thank you for your understanding.

Ok thanks Amit!

**Comment by amit-kremer93** [comment]
Hi @willcaul !
A new version has released with your fixes.
Thank you!

**Comment by willcaul** [comment]
> Hi @willcaul !
> A new version has released with your fixes.
> Thank you!

Thanks Amit! 👍
