### ISSUE TITLE
onInstallConversionData / onInstallConversionFailure don't fired in 6.0.31

### ISSUE THREAD

**Issue by AlexeyVlasenko** [AppsFlyerSDK/appsflyer-react-native-plugin#195]
# Report

## Plugin Version

6.0.31

## On what Platform are you having the issue?

iOS/Android

## What did you expect to happen?

App on Lib version 6.0.30 works perfect, but in 6.0.31 events don't fired

**Comment by AlexeyVlasenko** [comment]
Okay, i found why it's not called.
```
        onInstallConversionDataListener: true,
```
Please, mention breaking changes inside release notes...

**Comment by AlexeyVlasenko** [comment]
AppsFlyer not free service, so i think your should avoid such mistakes.

**Comment by af-fess** [comment]
hi @AlexeyVlasenko I very sorry your experience is less than perfect.

I agree that it confuses. We decided to make `onInstallConversionDataListener` to be `true` by default.

So you can use this parameter only when you don't need the callback.

The change: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/196
