### ISSUE TITLE
[Question] How to keep the devKey safe?

### ISSUE THREAD

**Issue by danielfx90** [AppsFlyerSDK/appsflyer-react-native-plugin#203]
When [initializing the SDK](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk), the `devKey` is required. This means we need to either hardcode it in the code or use something like [react-native-config](https://github.com/luggit/react-native-config) to have it in a dotenv file. While the latter is better, both are vulnerable to any [reverse engineering](https://reactnative.dev/docs/security#storing-sensitive-info) done to the app.

What are your recommendations to keep the `devKey` safe from attackers? Do we need to keep it safe or is it not an actual secret?

Cheers

**Comment by amit-kremer93** [comment]
Hi @danielfx90!
Thank you for opening this issue.
Please contact our support team: support@appsflyer.com
