### ISSUE TITLE
Event information with eventValues

### ISSUE THREAD

**Issue by gHashTag** [AppsFlyerSDK/appsflyer-react-native-plugin#204]
# Report

## Plugin Version
via `5.4.1`

## On what Platform are you having the issue?
ios and android

## What did you do
I am sending eventName and eventValues using as written in this[ tutorial](https://support.appsflyer.com/hc/en-us/articles/217108646-React-Native-plugin#core-apis-54-record-negative-revenue).

```javascript
import appsFlyer from "react-native-appsflyer"

const eventName = "af_add_to_cart"
const eventValues = {
   "af_content_id": "id123",
 }

appsFlyer.trackEvent(eventName, eventValues, (res) => { console.log(res) },  (err) => {  console.error(err) })
```

## What did you expect to happen?
I expect to see information in the admin area under events, but this information is not available.
<img width="1156" alt="Снимок экрана 2020-10-23 в 11 28 31" src="https://user-images.githubusercontent.com/6774813/96964005-1c6ee380-1523-11eb-8241-ab0a6341409e.png">

## What happened instead?
There is only information with these fields, but no information with eventValues.
<img width="1150" alt="Снимок экрана 2020-10-23 в 11 33 34" src="https://user-images.githubusercontent.com/6774813/96964310-b2a30980-1523-11eb-8449-4d3d6e5cb179.png">

**Comment by professorkolik** [comment]
Similar issue I have with `af_revenue` and `af_currency`. Event sent successfully but no update on AppsFlyer dashboard.

"react-native-appsflyer": "6.0.30"

**Comment by GM-appsflyer** [comment]
Hey,

We're investigating this issue and we'll get back to you with an update shortly.
Thank you!

**Comment by buchereli** [comment]
I am having the same issue with:

```
appsFlyer.logEvent(
    'test',
    { test: 'test' },
    (res) => console.log('succ', res),
    (res) => console.log('error', res),
  );
```

**Comment by gHashTag** [comment]
I was not at a sufficient level.

**Comment by buchereli** [comment]
> level

What do you mean sufficient level?

**Comment by gHashTag** [comment]
Payment
