### ISSUE TITLE
Apple rejects apps for kids with the AdSupport and iAd disabled

### ISSUE THREAD

**Issue by pabloearg** [AppsFlyerSDK/appsflyer-react-native-plugin#205]
# Report

## Plugin Version

6.0.50

## On what Platform are you having the issue?

iOS

## What did you do?
we added the react-native-appsflyer package to our app, and just run the pod install 

then we followed this guide: 

[additional-apis-kids-apps](https://support.appsflyer.com/hc/en-us/articles/207032066#additional-apis-kids-apps)

and then we added this two lines into the AppDelegate.m

```
...
#import "AppsFlyerLib.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  [AppsFlyerLib shared].disableCollectASA = YES;
  [AppsFlyerLib shared].disableAdvertisingIdentifier = YES;
...
```

## What did you expect to happen?

Apple should have approved our app

## What happened instead?

Apple rejected our app

## Please provide any other relevant information.

we also checked that we dont have AdSupport and iAd in any configuration file in our code

**Comment by af-fess** [comment]
Hi @pabloearg , can you provide the message you got from Apple?

**Comment by pabloearg** [comment]
@af-fess 

**From Apple**
1. 3 Safety: Kids Category

**### Guideline 1.3 - Safety - Kids Category**


We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties.

Your app includes the following feature(s), contrary to guideline 1.3 of the App Store Review Guidelines:

Third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA.

**Next Steps**

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.

**Comment by af-fess** [comment]
@pabloearg to help us, can you please DM me to maxim@appsflyer.com.

We will ask you for additional info.

**Comment by amit-kremer93** [comment]
Please follow [these](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#appKids) instructions.
