### ISSUE TITLE
onInstallConversionData: No address associated with hostname

### ISSUE THREAD

**Issue by Chasty** [AppsFlyerSDK/appsflyer-react-native-plugin#207]
# Report

## Plugin Version
via `6.0.50`

## On what Platform are you having the issue?
On Android with 5.4.4 SDK

## What did you do?

Run `npm install react-native-appsflyer --save` and then `react-native run-android`

## What did you expect to happen?
onInstallConversionData function to work as expected.

## What happened instead?
`onInstallConversionData: {"status":"failure","type":"onInstallConversionFailure","data":"Unable to resolve host \"launches.appsflyer.com\": No address associated with hostname"}`

## Please provide any other relevant information.
I have installed and changed my dev settings into my appsflyer account, and tried to use the plugin but it seems not to work and nothing happens in my dashboard.

My AppsFlyer email is willy.rosah@gmail.com.

The errors happens here after 2 minutes of waiting
`var onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
  (res) => {
    console.log('onInstallConversionData: ' + JSON.stringify(res));
    if (res.type === 'onInstallConversionSuccess') {
      if (JSON.parse(res.data.is_first_launch) === true) {
        if (res.data.af_status === 'Non-organic') {
          var media_source = res.data.media_source;
          var campaign = res.data.campaign;
          console.log(
            'This is first launch and a Non-Organic install. Media source: ' +
              media_source +
              ' Campaign: ' +
              campaign,
          );
        } else if (res.data.af_status === 'Organic') {
          console.log('This is first launch and a Organic Install');
        }
      } else {
        console.log('This is not first launch');
      }
    }
  },
);`

**Comment by af-fess** [comment]
Be sure you have an internet permissions (Manifest file):

```
<uses-permission android:name="android.permission.INTERNET" />

**Comment by Chasty** [comment]
> Be sure you have an internet permissions (Manifest file):
> 
> ```
> <uses-permission android:name="android.permission.INTERNET" />
> ```

I surely did that. this is my Manifest.xml

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.testonly">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>`

**Comment by amit-kremer93** [comment]
Hey @Chasty!
Do you run your app from emulator or a real device? if it from emulator try to close it and restart it again.
Second, be sure you entered the correct app's package name in your appsflyer dashboard

**Comment by amit-kremer93** [comment]
Hey @Chasty!
If the issue didn't solve yet please contact our support team: support@appsflyer.com

**Comment by Chasty** [comment]
Hi, finally it is working, I think it was because of a VPN connection.
