### ISSUE TITLE
[Android] Won't build in a monorepo

### ISSUE THREAD

**Issue by rborn** [AppsFlyerSDK/appsflyer-react-native-plugin#208]
# Report

## Plugin Version

6.0.50
## On what Platform are you having the issue?

android

## What did you do?

Trying to setup a monorepo project and android won't build with the next error:
I have hoisted the module in yarn workspaces but makes no difference

~~~
....node_modules/react-native-appsflyer/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java:510: error: cannot find symbol
        ArrayList<Object> domainsList = domainsArray.toArrayList();
symbol:   method toArrayList()
  location: variable domainsArray of type ReadableArray
~~~

## What did you expect to happen?

To build
## What happened instead?

Won't build as explained above

Any idea? Thank you 😻

**Comment by amit-kremer93** [comment]
Hi @rborn! thank you for opening this issue. i will check it and get back to you soon!

**Comment by amit-kremer93** [comment]
@rborn what version of react-native do you use?

**Comment by rborn** [comment]
@amit-kremer93 0.63.3
Thank you

**Comment by amit-kremer93** [comment]
Please try [this](https://stackoverflow.com/a/48155231) solution.
`toArrayList()` method related to react-native's `Readable Array` and not to Appsflyer.
Please let me know if it helped

**Comment by rborn** [comment]
Hi @amit-kremer93 
I have update that path before trying to build, same thing :(

**Comment by af-fess** [comment]
Did you try to clear the project and reinstall the node_modules? Looks like the new path will take no effect because the project still uses the old path.

**Comment by amit-kremer93** [comment]
@rborn if the issue still occurs, please open it again.
