### ISSUE TITLE
onAppOpenAttribution not called in consecutive openings on foreground

### ISSUE THREAD

**Issue by Chasty** [AppsFlyerSDK/appsflyer-react-native-plugin#209]
# Report

## Plugin Version

via `6.0.50`

## On what Platform are you having the issue?
Android 5.4.4 & iOS

## What did you do?
I used your provided code in init SDK guide the one with hooks.

## What did you expect to happen?
onAppOpenAttribution method being called successfully every time I open a onelink link.

## What happened instead?
The onAppOpenAttribution method is not called but when I minimize and then maximized the app the onAppOpenAttribution is called that's weird and it happens in both platforms on foreground.

## Please provide any other relevant information.
it happens when i open the apps thought a oneline link in two consecutive openings on foreground, I need to wait around 5 seconds to open a link to work it as expected.

**Comment by amit-kremer93** [comment]
Hey @Chasty and thank you for opening this issue.
The scenario that you described here is a typical behavior of the SDK and you can read more [Here](https://support.appsflyer.com/hc/en-us/articles/360000520785-Session-counting-explained)
if you have more questions, please contact our support team: support@appsflyer.com
