### ISSUE TITLE
No installs are shown on my dashboard

### ISSUE THREAD

**Issue by MaximAbramchuck** [AppsFlyerSDK/appsflyer-react-native-plugin#217]
# Report

## Plugin Version
`6.1.10`

## On what Platform are you having the issue?
Android

## What did you do?

1. Installed the package
2. White-listed my phone through an Appsflyer app, I can see it under the `Test devices` section on my Appsflyer account.
2. Put `appsFlyer.initSdk` with a correct `devKey`.
3. Built it - `react native run-android`.
3. Saw `Success` string in a `result` variable after the promise is resolved.

```
    appsFlyer.initSdk(
      {
        devKey: <my dev key>,
        isDebug: true,
        appId: '1537239242',
        onInstallConversionDataListener: true,
      },
      (result) => {
        console.log('result', result);
      },
      (error) => {
        console.error('error', error);
      },
    );
```

## What did you expect to happen?

Expect an organic install to be shown on my Appsflyer dashboard.

## What happened instead?

No installs on my dashboard

## Please provide any other relevant information.

account email: `maximabramchuck@gmail.com`

**Comment by af-fess** [comment]
Please post the AppsFlyer logs by using : 
```
<details>
  <summary>logs</summary>
...
</details>
```

**Comment by MaximAbramchuck** [comment]
I actually get no logs at all 😢 

I'm trying to get them via `react native log-android`.

I have `isDebug: true` passed to `appsFlyer.initSdk` function.

The only way I can log it is through `console.log` in promise result callback. There I get a "success" string.

**Comment by af-fess** [comment]
you can get them from logcat. Or open the project in Android Studio -> logcat

**Comment by MaximAbramchuck** [comment]
<details>
  <summary>logs</summary>
11-23 22:12:38.058 12028 12119 D AppsFlyer: Starting SDK
11-23 22:12:38.061 12028 12119 D AppsFlyer_6.1.0: Install referrer is allowed
11-23 22:12:38.061 12028 12119 D AppsFlyer_6.1.0: Connecting to Install Referrer Library...
11-23 22:12:38.061 12028 12119 D AppsFlyer_6.1.0: Connecting to Install Referrer Library...
11-23 22:12:38.069 12028 12119 D AppsFlyer_6.1.0: Initializing AppsFlyer SDK: (v6.1.0.64)
11-23 22:12:38.070 12028 12119 I AppsFlyer_6.1.0: Starting AppsFlyer: (v6.1.0.64)
11-23 22:12:38.070 12028 12119 I AppsFlyer_6.1.0: Build Number: 64
11-23 22:12:38.070 12028 12028 D AppsFlyer_6.1.0: InstallReferrer connected
11-23 22:12:38.072 12028 12173 I AppsFlyer_6.1.0: onBecameForeground
11-23 22:12:38.073 12028 12173 D AppsFlyer_6.1.0: No deep link detected
11-23 22:12:38.073 12028 12028 D AppsFlyer_6.1.0: Install Referrer collected locally
11-23 22:12:38.074 12028 12028 D AppsFlyer_6.1.0: Install Referrer collected locally
11-23 22:12:38.074 12028 12173 I AppsFlyer_6.1.0: Sending first launch for this session!
11-23 22:12:38.078 12028 12174 I AppsFlyer_6.1.0: sendWithEvent from activity: com.cname.app.MainApplication
11-23 22:12:38.081 12028 12174 I AppsFlyer_6.1.0: Trying to fetch GAID..
11-23 22:12:38.226 12028 12174 I AppsFlyer_6.1.0: ******* sendTrackingWithEvent: Launch
11-23 22:12:38.268 12028 12174 I AppsFlyer_6.1.0: IMEI was not collected.
11-23 22:12:38.269 12028 12174 I AppsFlyer_6.1.0: Android ID was not collected.
11-23 22:12:38.285 12028 12174 I AppsFlyerOaid6.1.2: Fetch 1 ms
11-23 22:12:38.297 12028 12174 D AppsFlyer_6.1.0: AppsFlyer: first launch detected
11-23 22:12:38.298 12028 12174 I AppsFlyer_6.1.0: AppsFlyer: first launch date: 2020-11-23_221238+0000
11-23 22:12:38.300 12028 12174 D AppsFlyer_6.1.0: didConfigureTokenRefreshService=false
11-23 22:12:38.309 12028 12174 I AppsFlyer_6.1.0: AppsFlyerLib.sendWithEvent
11-23 22:12:38.311 12028 12174 D AppsFlyer_6.1.0: Install referrer is allowed
11-23 22:12:38.533 12028 12174 I AppsFlyer_6.1.0: url: https://conversions.appsflyer.com/api/v6.1/androidevent?app_id=com.cname.app&buildnumber=6.1.0
11-23 22:12:38.534 12028 12174 I AppsFlyer_6.1.0: data: {"country":"US","af_timestamp":"1606169558197","appsflyerKey":"N********************K","isFirstCall":"true","registeredUninstall":false,"operator":"giffgaff","isGaidWithGps":"true","app_version_code":"3","model":"Pixel 4 XL","brand":"google","deviceType":"user","deviceData":{"sensors":[{"sT":2,"sVS":[-18.55125,-29.8175,-13.37375],"sV":"STMicro","sVE":[-18.9075,-28.97375,-13.11125],"sN":"LIS2MDL Magnetometer"},{"sT":1,"sVS":[-0.11784652,-0.28295127,9.81835],"sV":"STMicro","sVE":[-0.13220344,-0.29252258,9.799207],"sN":"LSM6DSR Accelerometer"},{"sT":4,"sVS":[0,-3.0542363E-4,-7.635591E-4],"sV":"STMicro","sVE":[0.0012216945,0.0021379655,-7.635591E-4],"sN":"LSM6DSR Gyroscope"}],"cpu_abi":"arm64-v8a","build_display_id":"RP1A.201105.002","btch":"ac","dim":{"size":"2","ydp":"539.972","xdp":"537.882","y_px":"2984","x_px":"1440","d_dpi":"560"},"arch":"","btl":"27.0","cpu_abi2":""},"exception_number":0,"disk":"3270\/51197","sdk":"30","fb":"138cea03-28b5-4e00-9f46-9a82bc2e52c0","app_version_name":"1.1","device":"coral","cksm_v1":"b7a26cd40312ceb39f09d6540a28af680d","rfr":{"val":"utm_source=google-play&utm_medium=organic","code":"0","clk":"0","install":"1605630994","instant":false},"kef6366":"b9a632c67672e91e48181a1b0c531a0d59181f0d5a1f13","af_events_api":"1","cell":{"mnc":10,"mcc":234},"network":"MOBILE","timepassedsincelastlaunch":"-1","open_referrer":"android-app:\/\/com.android.shell","af_v2":"d031c3251e42bda646a873b0605936d48c9edd89","sig":"A515CFDC5805D0A22CBDD42A73D3A51B7579056077E8CEB1D3487C1A18CC52BA","uid":"1606169558285-2436145331389516448","lang_code":"en","installDate":"2020-11-23_221235+0000","referrers":[{"api_ver":82271110,"referrer":"utm_source=google-play&utm_medium=organic","click_ts":0,"api_ver_name":"22.7.11-21 [0] [PR] 341094087","response":"OK","install_begin_ts":1605630994,"google_custom":{"install_begin_server_ts":1605630995,"install_version":"1.0","click_server_ts":0,"instant":false},"latency":12,"source":"google","type":"store"}],"firstLaunchDate":"2020-11-23_221238+0000","ivc":false,"lang":"English","batteryLevel":"27.000002","last_boot_time":1605983648467,"product":"coral","date2":"2020-11-23_221235+0000","counter":"1","date1":"2020-11-23_221235+0000","advertiserId":"03cab138-1073-48fc-8c8a-8b124b05f0a4","advertiserIdEnabled":"true","af_v":"e517e854db887fd60ea42d8f6cc8ff4cbf226258","carrier":"giffgaff","af_preinstalled":"false","iaecounter":"0","sc_o":"p","tokenRefreshConfigured":false,"platformextension":"android_reactNative"}
11-23 22:12:38.732 12028 12174 I AppsFlyer_6.1.0: response code: 403
11-23 22:12:38.732 12028 12174 D AppsFlyer_6.1.0: [GCD-A01] Loading conversion data. Counter: 1
11-23 22:12:38.744 12028 12205 I AppsFlyer_6.1.0: [GCD-B01] URL: https://gcdsdk.appsflyer.com/install_data/v4.0/com.cname.app?devkey=N********************K&device_id=1606169558285-2436145331389516448
11-23 22:12:38.919 12028 12205 D AppsFlyer_6.1.0: [GCD-A03] Server retrieving attempt finished
11-23 22:12:38.931 12028 12174 I AppsFlyer_6.1.0: [GCD-B01] URL: https://gcdsdk.appsflyer.com/install_data/v4.0/com.cname.app?devkey=N********************K&device_id=1606169558285-2436145331389516448
11-23 22:12:39.065 12028 12174 D AppsFlyer_6.1.0: [GCD-A03] Server retrieving attempt finished
11-23 22:12:39.076 12028 12217 I AppsFlyer_6.1.0: [GCD-B01] URL: https://gcdsdk.appsflyer.com/install_data/v4.0/com.cname.app?devkey=N********************K&device_id=1606169558285-2436145331389516448
11-23 22:12:39.205 12028 12217 D AppsFlyer_6.1.0: [GCD-A02] Calling onConversionFailure with:
11-23 22:12:39.205 12028 12217 D AppsFlyer_6.1.0: Error connection to server: 403
11-23 22:12:39.206 12028 12217 D AppsFlyer_6.1.0: [GCD-A03] Server retrieving attempt finished
</details>

**Comment by af-fess** [comment]
please send me your dev key, Ill check your account. maxim@appsflyer.com

**Comment by af-fess** [comment]
A code 403 means traffic-enabled, meaning zero plan package that used all of its quota

**Comment by phamthang03** [comment]
@af-fess hi, I'm facing the same issue with @MaksimAbramchuk , but this is the first time I use Appsflyer, so why I got 403 (traffic-enabled)?
