### ISSUE TITLE
Typescript errors

### ISSUE THREAD

**Issue by djMax** [AppsFlyerSDK/appsflyer-react-native-plugin#218]
The typescript declarations are incomplete. This patch fixes them, but I'd rather not have to patch it at all.

```
diff --git a/node_modules/react-native-appsflyer/index.d.ts b/node_modules/react-native-appsflyer/index.d.ts
index 7062b96..abc1c94 100644
--- a/node_modules/react-native-appsflyer/index.d.ts
+++ b/node_modules/react-native-appsflyer/index.d.ts
@@ -79,11 +79,11 @@ declare module "react-native-appsflyer" {
         anonymizeUser(shouldAnonymize: boolean, successC?: SuccessCB): void
         setOneLinkCustomDomains(domains: string[], successC: SuccessCB, errorC: ErrorCB): void
         setResolveDeepLinkURLs(urls: string[], successC: SuccessCB, errorC: ErrorCB): void
-        performOnAppAttribution(urlString, successC: SuccessCB, errorC: ErrorCB): void
+        performOnAppAttribution(urlString: string, successC: SuccessCB, errorC: ErrorCB): void
         setSharingFilterForAllPartners(): void
-        setSharingFilter(partners, successC, errorC): void
+        setSharingFilter(partners: any, successC: SuccessCB, errorC: ErrorCB): void
         logLocation(longitude: number, latitude: number, successC?: SuccessCB): void
-        validateAndLogInAppPurchase(purchaseInfo: InAppPurchase, successC, errorC): Response<string>
+        validateAndLogInAppPurchase(purchaseInfo: InAppPurchase, successC: SuccessCB, errorC: ErrorCB): Response<string>
         updateServerUninstallToken(token: string, successC?: SuccessCB): void
         sendPushNotificationData(pushPayload: object): void
```

**Comment by csantarin** [comment]
I'd also be happy if they could adjust the typescript declarations for the `onAppOpenAttribution` callback data. The `any` type makes it more difficult to understand what exactly to expect from the SDK.
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/076859572a15aeacbaea363e92c800305a9c5367/index.d.ts#L65-L66

**Comment by D-Hartley** [comment]
Another example that should be adjusted:

https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/076859572a15aeacbaea363e92c800305a9c5367/index.d.ts#L8-L21

The `data` property is a string containing error information when the status is `"failure"`.

Actual conversion data:

`{ status: 'failure', type: 'onInstallConversionFailure', data: 'Unable to resolve host "launches.appsflyer.com": No address associated with hostname' }`

**Comment by amit-kremer93** [comment]
Will be fixed in the next release

**Comment by benmgreene** [comment]
@amit-kremer93 is that next release forthcoming? thanks much 🙏

**Comment by amit-kremer93** [comment]
we added typescript declarations to `onAppOpenAttribution` and `onDeepLink` callback to 6.5.20
