### ISSUE TITLE
Incomplete section "v6 Breaking Changes" on Readme

### ISSUE THREAD

**Issue by JHPG** [AppsFlyerSDK/appsflyer-react-native-plugin#219]
# Report

## Plugin Version

`6.1.10`

## On what Platform are you having the issue?

iOS

## What did you do?

I've followed the instructions for "v6 Breaking Changes" described in this current Readme, then built the app on iOS.

## What did you expect to happen?

Build and run the app normally.

## What happened instead?

The iOS app doesn't build.

## Please provide any other relevant information.

The "v6 Breaking Changes" section on Readme looks incomplete, it doesn't mention the changes on the native side described here:
https://support.appsflyer.com/hc/en-us/articles/360011571778#2-implement-sdk-v6

Without it, I've got this error:
```
.
.
.
.../AppDelegate.m:9:9: fatal error: 'AppsFlyerTracker.h' file not found
#import "AppsFlyerTracker.h"
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by amit-kremer93** [comment]
@JHPG thank you for mention that.
after following [these](https://support.appsflyer.com/hc/en-us/articles/360011571778#2-implement-sdk-v6) steps the app was built?

**Comment by JHPG** [comment]
Yes, after following these steps it works, but they are not in the Readme.

**Comment by amit-kremer93** [comment]
I will add this to the breaking changes section.
thank you
