### ISSUE TITLE
ios  error: cannot find 'AppsFlyerTracker' in scope

### ISSUE THREAD

**Issue by wangxingxing123654** [AppsFlyerSDK/appsflyer-react-native-plugin#220]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
e.g. via `4.1.1`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
e.g. ios and android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be logged

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. No uninstalls on my dashboard

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by amit-kremer93** [comment]
Hi @wangxingxing123654 thank for opening this issue.
the latest appsflyer sdk deprecated the work "track" from all of the apis. please check the readme [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#v6-breaking-chang).
if you are using version 4.1.1,  update to version 6.x.x.
