### ISSUE TITLE
[android] server error code : 400

### ISSUE THREAD

**Issue by genseric** [AppsFlyerSDK/appsflyer-react-native-plugin#224]
# Report

## Plugin Version
6.1.2

## On what Platform are you having the issue?
android

## What did you do?
apk install  + android studio results with server code 400. 
{"data": "Error connection to server: 400", "status": "failure", "type": "onInstallConversionFailure"}

## What did you expect to happen?
no 400 error

## Please provide any other relevant information.
it all works fine with ios. there are 2 versions of app for ios and android specifically.

**Comment by amit-kremer93** [comment]
Hi @genseric.  Be sure you integrated the SDK correctly, with all the permissions needed, and you added the app to your AppsFlyer account.
for more help, please contact our support team: support@appsflyer.com
