### ISSUE TITLE
onInstallConversionData not working, failure with "The data couldn’t be read because it isn’t in the correct format."

### ISSUE THREAD

**Issue by kshport** [AppsFlyerSDK/appsflyer-react-native-plugin#225]
# Report

## Plugin Version

6.1.20
react-native: 0.63.3

## On what Platform are you having the issue?

iOS & Android

## What did you do?

rm -rf Pods/
pod install

## What did you expect to happen?

onInstallConversionData not triggered

## What happened instead?

onInstallConversionFailure returns:
{
status: "failure"
type: "onInstallConversionFailure"
data: "The data couldn’t be read because it isn’t in the correct format."
}

## Please provide any other relevant information.

At 24.12.2020 in 13:10 (UTC-0) it's stop working, in released in store build too (they stopped sending data to server on onInstallConversionData event)

**Comment by kshport** [comment]
Zero tariff quotas have been exhausted... No notifications either in the appsflyer dashboard or in the mail

**Comment by jetaggart** [comment]
@kshport did you figure this out? we're seeing the same issue.

**Comment by kshport** [comment]
@jetaggart check appsflyer's quotas, they are most likely exhausted
