### ISSUE TITLE
android build faild with error 

### ISSUE THREAD

**Issue by believeyourself** [AppsFlyerSDK/appsflyer-react-native-plugin#226]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
via `6.1.10`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `yarn android`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
app installed on my phone 

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
long time loading in :
> :app > Resolve dependencies of :app:debugRuntimeClasspathCopy > :react-native-appsflyer > Resolve dependencies of :react-native-appsflyer:classpath > gradle-4.0.0.pom
and then report error:
Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
if I remove the plugin ,everything is OK

**Comment by amit-kremer93** [comment]
@believeyourself try to clean the project from your Android studio and build again.
what is your Gradle version and your android studio version?

**Comment by believeyourself** [comment]
> @believeyourself try to clean the project from your Android studio and build again.
> what is your Gradle version and your android studio version?

I cleaned the project and rebuild,it failed with "Gradle: Download gradle-4.0.0.pom..."
Gradle version is 6.2 and android studio version is 4.1.1

**Comment by believeyourself** [comment]
@amit-kremer93  I cleaned the project and rebuild,it failed with "Gradle: Download gradle-4.0.0.pom..."
Gradle version is 6.2 and android studio version is 4.1.1

**Comment by believeyourself** [comment]
@amit-kremer93  I cleaned the project and rebuild,it failed with "Expected org.gradle.api.artifacts.result.ResolvedDependencyResult but found org.gradle.api.internal.artifacts.result.DefaultUnresolvedDependencyResult"
Gradle version is 6.2 and android studio version is 4.1.1

**Comment by amit-kremer93** [comment]
@believeyourself in your app folder, go to `gradle->wrapper->gradle-wrapper.properties`. what is your `distributionUrl`?
and also what is your `classpath` in the `build.gradle` file?
please try [this](https://github.com/gradle/gradle/issues/12723#issuecomment-612490322) solution
