### ISSUE TITLE
validateAndLogInAppPurchase not working on iOS

### ISSUE THREAD

**Issue by jwebcat** [AppsFlyerSDK/appsflyer-react-native-plugin#229]
# Report

## Plugin Version

`6.1.20`

## On what Platform are you having the issue?

ios

## What did you do?

installed latest version of the plugin

## What did you expect to happen?

validateAndLogInAppPurchase to be called successfully on iOS

## What happened instead?

validateAndLogInAppPurchase fails on iOS with this error message. Working as expected on Android.

```
code: "E(null)0"
domain: "RCTErrorDomain"
message: "Unknown error from a native module"
```

## Please provide any other relevant information.

I am calling `appsFlyer.setUseReceiptValidationSandbox(true);` on iOS, as recommended in the docs. I have tried calling it 
 both  before `appsFlyer.initSdk` method and before calling `appsFlyer.validateAndLogInAppPurchase`  (separately) and it still doesn't work. Also I tried it without calling `appsFlyer.setUseReceiptValidationSandbox` and it yields the same result.

ReactNative version is `0.63.3`

**Comment by pazlavi** [comment]
hey,
Can you please let us know what is the error code you got from the native when you run the app from Xcode? Search the logs block that starts with `[Validate] Response Info`. Don't forget the enable the debug logs when you initialize the SDK `isDebug: false`
![21007](https://user-images.githubusercontent.com/72502546/103626683-3b3b1e80-4f45-11eb-9300-94d85ab8684e.png)

**Comment by jwebcat** [comment]
@pazlavi For sure, thanks for the quick reply. I will get back to you shortly with that error code.

**Comment by jwebcat** [comment]
@pazlavi this is what is output in the logs when that error occurs:

```
[DEBUG] AppsFlyer: 
[Validate] Dictionary:{
    environment = Sandbox;
    status = 21004;
}
[Validate] Response Info:{
    data = {length = 40, bytes = 0x7b22656e ... };
    dataStr = "{\"environment\":\"Sandbox\",\"status\":21004}";
    statusCode = 200;
    taskIdentifier = 10;
}
[Validate] Error: (null)
```

**Comment by jwebcat** [comment]
@pazlavi Does the plugin not support validating Sandbox receipts? I assumed it does, as we have this method available `appsFlyer.setUseReceiptValidationSandbox(true)` but I figured I would call it out just in case.

**Comment by pazlavi** [comment]
@jwebcat the plugin supports validating Apple Sandbox receipts. This error is not SDK-related, it comes from Apple. 
I'll explain what this error means in your support ticket.

**Comment by kyle-ssg** [comment]
@pazlavi, is it possible to put the answer here too? I'm facing the exact same issue with sandbox purchases - I can create a duplicate github issue if you'd prefer though.
