### ISSUE TITLE
 Following one link does not work on Xiaomi android

### ISSUE THREAD

**Issue by Goldyukol** [AppsFlyerSDK/appsflyer-react-native-plugin#230]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
e.g. via `6.0.50`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
e.g. android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `redirect to link on xiaomi android`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Redirect to app

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Redirect to Play Marker

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. 
Following one link does not work on Xiaomi androids. Works on devices from other manufacturers

**Comment by amit-kremer93** [comment]
@Goldyukol can you please share your `onNewIntent` method on your `MainActivity`?

**Comment by Goldyukol** [comment]
```
 @Override
    public void onNewIntent(Intent intent) {
         super.onNewIntent(intent);
         setIntent(intent);
    }
```

> @Goldyukol can you please share your `onNewIntent` method on your `MainActivity`?

**Comment by amit-kremer93** [comment]
@Goldyukol if it works on other devices so the problem is not related to the plugin. you can try to switch between URI scheme or App links. for more information please contact our support team: support@appsflyer.com
