### ISSUE TITLE
onAppOpenAttribution is not called on the first time app launches after installation

### ISSUE THREAD

**Issue by haipham-kontist** [AppsFlyerSDK/appsflyer-react-native-plugin#232]
# Report

## Plugin Version

via `5.4.1` and `6.1.30`
(I upgraded to see if it's fixed in the newest version)

## On what Platform are you having the issue?

ios (haven't tested on android yet)

## What did you do?

I ran `react-native ios`, then the app is launched. However, `onAppOpenAttribution` doesn't get called.
I closed the app, and execute `xcrun simctl openurl booted "...onelink.me/..."`. Now it's called.

## What did you expect to happen?

When I open the app the first time, `onAppOpenAttribution` gets called, [as described here](https://dev.appsflyer.com/docs/deferred-deep-linking-new-users-to-specific-content-inside-your-app).

## What happened instead?

When I open the app the first time, `onAppOpenAttribution` doesn't get called.

Actually, [this comment](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223#issuecomment-759271405) sums it up quite correctly.

## Please provide any other relevant information.

`onInstallConversionData` was called in both cases.

**Comment by amit-kremer93** [comment]
Hi @haipham-kontist, there is another issue opened [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223) so please follow there.
