### ISSUE TITLE
Proper way to retrieve custom attributes on deferred deep linking

### ISSUE THREAD

**Issue by haipham-kontist** [AppsFlyerSDK/appsflyer-react-native-plugin#237]
# Report

## Plugin Version

ℹ  `6.1.41`

## On what Platform are you having the issue?

ℹ  android and ios

## What did you do?

This is not an issue, just general questions.

1) How to properly retrieve custom attributes on **deferred deep linking**?

When I click on the link, it redirects me to app store / play store to download and install the app. After the app is installed in opened, I expect to retrieve custom attributes.

Currently, `onAppOpenAttribution` **is not triggered at all** in both environments in this scenario. According to the flow [here](https://dev.appsflyer.com/docs/deferred-deep-linking-new-users-to-specific-content-inside-your-app), it should be trigger by `onConversionDataSuccess`. It's not the case here.

It works on **direct deep linking** (there's [an issue](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/223) with iOS though).

Without `onAppOpenAttribution` being triggered, please let me know how I can retrieve the custom attributes?

2) `onInstallConversionData` in IOS and Android behaves differently.
- In Android, it's only contains 4 different attributes: `af_message`, `af_status`, `install_time`, `is_first_launch`.
- in IOS, it is bloated. There are many attributes besides the 4 above such as: `adgroup`, `adgroup_id`, `adset`, `adset_id`, `af_click_lookback`, etc.

Is there some issue in appsFlyer leads to this inconsistency? Or is it intentional?

Thanks for reading 🙏

**Comment by amit-kremer93** [comment]
Hi @haipham-kontist. I think it better for you to ask our support team: support@appsflyer.com. They can help you understand the flow and how to handle it right according to your needs.
