### ISSUE TITLE
performOnAppAttribution can not have a non-function arg after a function arg

### ISSUE THREAD

**Issue by Goldyukol** [AppsFlyerSDK/appsflyer-react-native-plugin#238]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
e.g. via `6.0.50`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
e.g. ios and android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `run this API
```
 let uriString = 'sdktest://test';
    appsFlyer.performOnAppAttribution(uriString, (res) => {
      console.log('URI', res);
    });
````

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
performOnAppAttribution work 

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
My app has crashed

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.

**Comment by Goldyukol** [comment]
There is an example in your documentation that causes the application to crash


Here is a correct example: 
               ```
 appsFlyer.performOnAppAttribution(
                  url,
                  res => {
                    console.log(res);
                  },
                  err => {
                    console.error(err);
                  },
                );
```

**Comment by amit-kremer93** [comment]
@Goldyukol you're right, there is a mistake in the docs. I'll change them. Thank you!
