### ISSUE TITLE
Direct deep linking not working when app is full closed, working only when app in background 

### ISSUE THREAD

**Issue by balandinS** [AppsFlyerSDK/appsflyer-react-native-plugin#239]
# Report

## Plugin Version
6.0.30 version 

## On what Platform are you having the issue?
android 

## What did you do?

ed the direct deep linking configuration as the documentation shows. Once configured, opened a valid deep link that redirects to the app.

apps flayer dashboard
added to android sha256 
copied intent to manifest
and then in edit Onelin  -> attribution  i toggle on "This link will be used to retarget existing users"
in MainActivity added onNewIntent
implement every step in the DOCS
[docs](https://support.appsflyer.com/hc/en-us/articles/208874366)

## What did you expect to happen?

when lunched first time , onAppOpenAttribution and onInstallConversionData callback is not called

## What happened instead?

Works well when the app is in background, but if it is full closed, the onAppOpenAttribution and onInstallConversionData  callback is not called when the app opens.

## Please provide any other relevant information.

`let onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
        (res) => {
 console.log('onInstallConversionDataCanceller --> ', res);
        }
    );
    let onAppOpenAttributionCanceller = appsFlyer.onAppOpenAttribution((res) => {
        console.log(res);
    });

    appsFlyer.initSdk(
        {
            devKey: **,
            isDebug: false, // set to true if you want to see data in the logs
            appId: **,
            onInstallConversionDataListener: true
        },
        result => {
           // console.log('result = ' + JSON.stringify(result))
        },
        error => {
            // console.log('error = ' + JSON.stringify(error))
        }
    )`

**Comment by amit-kremer93** [comment]
@balandinS Thank you for opening this issue. do you use other SDKs inside your app that may consume the intent? can you please share your `onNewIntent` method?

**Comment by sregg** [comment]
I found the issue, the navigator that was handling the deeplink was rendered after we called `appsFlyer.onDeepLink`.
