### ISSUE TITLE
onInstallConversionData doesn't invoke on android after app installing. onAppOpenAttribution doesn't invoke on both platforms after app installing

### ISSUE THREAD

**Issue by bars88** [AppsFlyerSDK/appsflyer-react-native-plugin#241]
# Report

## Plugin Version

6.1.41

## On what Platform are you having the issue?

ios and android

## What did you do?

Trying to implement deffered link flow. Link works properly only when app is already installed

## What did you expect to happen?

If app is not installed link should lead to app store, then after installing onInstallConversionData should be triggered, then in onAppOpenAttribution i want to process params from the one link

## What happened instead?

on android even onInstallConversionData doesn't invoke.
on ios onAppOpenAttribution doesn't invoke

## Please provide any other relevant information.

"react-native": "0.62.2"

`    const onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
        (res: any) => {
            console.log('conversion ==>>', res.data);
            if (JSON.parse(res.data.is_first_launch) == true) {
                if (res.data.af_status === 'Non-organic') {
                    const media_source = res.data.media_source;
                    const campaign = res.data.campaign;
                    console.log(
                        'This is first launch and a Non-Organic install. Media source: ' +
                            media_source +
                            ' Campaign: ' +
                            campaign,
                    );
                } else if (res.data.af_status === 'Organic') {
                    console.log('This is first launch and a Organic Install');
                }
            } else {
                console.log('This is not first launch');
            }
        },
    );

    const onAppOpenAttributionCanceller = appsFlyer.onAppOpenAttribution(
        (res: any) => {
            console.log('attribution ==>>>', res.data)
            if (res?.status === 'success' && res?.data && !!res?.data.link) {
                console.log('onAppOpenAttribution', res?.data);
                const getApp = res?.data.link.includes('getapp');
                if (getApp) {
                    setRoute({
                        stack: 'Unauthorized',
                        name: 'SignIn'
                    })
                }
            } 
        },
    );

    appsFlyer.initSdk(
        {
            devKey: 'dev key',
            isDebug: true, // set to true if you want to see data in the logs
            appId: '12345678', // iOS app id
        },
        (result: any) => {
            console.log('appsFlyer.initSdk ==>>', result);
        },
        (error: any) => {
            console.error(error);
        },
    );`

**Comment by amit-kremer93** [comment]
Hi @bars88. According to [OneLink documentation](https://dev.appsflyer.com/docs/deferred-deep-linking-new-users-to-specific-content-inside-your-app), when the user installs and opens the app for the first time (deferred deep link) only the `onInstallConversionData` listener is triggered and gives you the one link attribution data.
On Android, be sure that you implemented `onNewIntent` in the MainActivity

**Comment by bars88** [comment]
thanks for the answer @amit-kremer93 . i have onNewIntent implementation inside MainActivity class

**Comment by jfbn** [comment]
> Hi @bars88. According to [OneLink documentation](https://dev.appsflyer.com/docs/deferred-deep-linking-new-users-to-specific-content-inside-your-app), when the user installs and opens the app for the first time (deferred deep link) only the `onInstallConversionData` listener is triggered and gives you the one link attribution data.
> On Android, be sure that you implemented `onNewIntent` in the MainActivity

Sorry for hijacking this post with something relatively unrelated.
We are considering implementing AppsFlyer in our RN app. I have been looking at the readme for this library, and I did not find any mention of what you're describing here with `onNewIntent` and neither anything about the native SDK's for Android and iOS being necessary to install beforehand. I assume that this is the case, but such assumptions will often lead to confused and unsatisfied users. Perhaps you should consider adding a paragraph to the readme that informs readers what prerequisites there are for using this library.

**Comment by amit-kremer93** [comment]
@bars88, please contact our support team: support@appsflyer.com in order to get more information about your problem

**Comment by nobbyclark** [comment]
I'm also having this issue, is there any way to locally debug the "app not installed" => "install app" => "inspect onAppOpenAttribution response" without having to upload a new version of the app to the Google Play Store?

**Comment by amit-kremer93** [comment]
@nobbyclark as i mentioned, when app is launched for the first time after install from link (deferred deep link, you can read [here](https://dev.appsflyer.com/hc/docs/deferred-deep-linking-new-users-to-specific-content-inside-your-app)) onAppOpenAttribution will not trigger. onInstallConversionData will trigger with `is_first_launch` flag = true.
In order to debug it, just remove the app from your phone, click a link, wait for your browser to open and then install the app manually from android studio/xcode/other ide. You can read [here](https://support.appsflyer.com/hc/en-us/articles/207032096#2-testing)
