### ISSUE TITLE
iOS: Deferred deep linking not working 6.2.10

### ISSUE THREAD

**Issue by RobertoNegro** [AppsFlyerSDK/appsflyer-react-native-plugin#247]
# Report

## Plugin Version

6.2.10

## On what Platform are you having the issue?

ios

## What did you do?

I've clicked on a deep link without the app installed, then installed the app via App Store, and opened the app

## What did you expect to happen?

Deferred deep link should be triggered

## What happened instead?

No deep link was recognized by the app

## Please provide any other relevant information.

I've updated the library since, with the previous version, deep links clicked when the app was closed on iOS was not triggering the corresponding action. In this new version (6.2.10) the deep linking works both with app opened or closed, but I'm not able to make deferred deep links working.

I've followed the Init SDK guide, I've added the code as reported there. 
But I was not able to add:
```
// Reports app open from deep link from apps which do not support Universal Links (Twitter) and for iOS8 and below
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString*)sourceApplication annotation:(id)annotation {
    // version >= 6.2.10
    [[AppsFlyerAttribution shared] handleOpenURL:url sourceApplication:sourceApplication withAnnotation:annotation];
    return YES;
}
```
Because of: `No visible @interface for 'AppsFlyerAttribution' declares the selector 'handleOpenURL:sourceApplication:withAnnotation:'`

So I've only used the other code for iOS 10. But I don't think this could cause this problem, since I'm testing by clicking on the link from Safari and on iOS 14.4.

If I click on a link, and when it prompts the app store I start the application from XCode (installing the app in debug version), the app recognizes successfully also the deferred deep link. But with the published app I'm not able to replicate that behaviour.

Summaryzing: In android, deep linking and deferred deep linking works as expected. In iOS deep linking works as expected, except for deferred deep linking when installing the app from the App Store after clicking on a deep link with no app installed.

**Comment by amit-kremer93** [comment]
Hi @RobertoNegro . please replace `withAnnotation` to `annotation`:
`[[AppsFlyerAttribution shared] handleOpenUrl:url sourceApplication:sourceApplication annotation:annotation];`
Please try again and let us know.

**Comment by RobertoNegro** [comment]
I've added that and published another version, but sadly the deferred deep linking is still not working on iOS!

**Comment by amit-kremer93** [comment]
@RobertoNegro please contact our support: support@appsflyer.com
