### ISSUE TITLE
v2.4.10 build fails on iOS

### ISSUE THREAD

**Issue by jwebcat** [AppsFlyerSDK/appsflyer-react-native-plugin#248]
# Report

## Plugin Version

`6.2.10`

## On what Platform are you having the issue?

iOS

## What did you do?

installed `v6.2.10` via yarn
ran pod install
integrated changes from the deeplink readme for `v6.2.10`
tried to build app

## What did you expect to happen?

app to build successfully.

## What happened instead?

app fails to build from including this line

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  // this line 
  [[AppsFlyerAttribution shared] handleOpenURL:url sourceApplication:sourceApplication withAnnotation:annotation];
}
```

 with error:

```
No visible @interface for 'AppsFlyerAttribution' declares the selector 'handleOpenURL:sourceApplication:withAnnotation:'
```

This was reported as part of https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/247 but I thought it best to flag as a separate issue.

**Comment by amit-kremer93** [comment]
Hi @jwebcat. please replace `withAnnotation` to `annotation`:
`[[AppsFlyerAttribution shared] handleOpenUrl:url sourceApplication:sourceApplication annotation:annotation];`
Sorry for this error, I will fix the docs.

**Comment by jwebcat** [comment]
@amit-kremer93 No worries, It's working as expected now. Thanks for updating the docs. Closing this issue.
