### ISSUE TITLE
initSdk API don't validate params types

### ISSUE THREAD

**Issue by flonghini** [AppsFlyerSDK/appsflyer-react-native-plugin#249]
# Report

## Plugin Version

`6.2.10`

## On what Platform are you having the issue?

iOS and Android

## What did you do?

Followed all steps provide on README for installing and initialized the SDK with devKey, isDebug as a number type (forcing an type error), exactly like this:

```javascript
import appsFlyer from 'react-native-appsflyer';

appsFlyer.initSdk(
  {
    devKey: '123123123',
    isDebug: 123123123,
    appId: '123123123',
  },
  (result) => {
    console.log(result);
  },
  (error) => {
    console.error(error);
  }
);
```

## What did you expect to happen?

It's expected that the error callback returns an error. AppsFlyer SDK shouldn't be initialized when passing parameters with wrong types, otherwise, returning Success will not track user acquisition trend on dashboard.
I know that on InitSDKOptions interface isDebug is optional, but initializing it with other types (instead boolean) it returns Success and won't track users

## What happened instead?

The SDK initialization returns **Success**

## Please provide any other relevant information.

I opened this issue because I've noticed the graphics of the user acquisition trend dropped to 0, then when I was debugging I also noticed that I was initalizating the SDK passing a parameter with a wrong type, setting isDebug: 'false' (as string).

I was using react-native-config to inject the AppsFlyer SDK variables, my error was injecting a string on isDebug due to react-native-config get these env vars as strings.
APPS_FLYER_IS_DEBUG=false

I've created a blank project, you guys could check it - https://github.com/flonghini/appsflyer-test

thanks

**Comment by amit-kremer93** [comment]
Hi @flonghini thank you for opening this issue. it will be fixed in the next release

**Comment by amit-kremer93** [comment]
added params types validation in the latest version (6.2.40)

**Comment by mcorner** [comment]
This one caught us by surprise as we didn't set isDebug and init starting failing.  This is a breaking change and probably should be documented as "required" in the README
