### ISSUE TITLE
Updating RN plugin for SDK v6.2.3

### ISSUE THREAD

**Issue by alexpluto** [AppsFlyerSDK/appsflyer-react-native-plugin#252]
# Report

## Plugin Version

6.0.50 (react-native-appsflyer)

## On what Platform are you having the issue?

ReactNative (iOS)

## Issue

I just saw an email from AF about an urgent bug fix (relating to SKAdNetwork conversion values). They recommend an update to SDK v6.2.3. See below.

I was wondering if there is a planned fix on this version of the plugin to incorporate that fix?

![Screenshot 2021-03-08 at 11 30 50](https://user-images.githubusercontent.com/42174498/110316181-458b9e80-8002-11eb-9757-a855d2a29dbb.png)

**Comment by amit-kremer93** [comment]
Hi @alexpluto yes we will release a new version of the plugin today (6.2.30) with new ios sdk version v6.2.3

**Comment by alexpluto** [comment]
@amit-kremer93 amazing, thanks for the speedy reply and action!

**Comment by amit-kremer93** [comment]
@alexpluto  v6.2.30 is available

**Comment by alexpluto** [comment]
Thank you!
