### ISSUE TITLE
Both platforms: 403 trying to log event

### ISSUE THREAD

**Issue by kyle-ssg** [AppsFlyerSDK/appsflyer-react-native-plugin#253]
# Report

## Plugin Version

6.2.10

## On what Platform are you having the issue?
Both.

## What did you do?

```

appsFlyer.initSdk(
  {
    devKey: "MY_DEV_KEY",
    isDebug: true,
    appId: Platform.select({ios:"MY_APP_ID", android:undefined}),
    onInstallConversionDataListener: true, //Optional
    onDeepLinkListener: true, //Optional
  },
  (result) => {
    console.log(result);
  },
  (error) => {
    console.error(error);
  }
);

...

 appsFlyer.logEvent(
        "app_open",
        {},
        (res) => {
          console.log(res);
        },
        (err) => {
          console.error(err);
        }
      );
```

## What did you expect to happen?

I expected events to be tracked.

## What happened instead?

For both iOS and Android I got a non-descript 403 error.

## Please provide any other relevant information.

If I set the app id to my pending staging app I also get a 404.

**Comment by pazlavi** [comment]
status code 403 represents a "Forbidden" request. Probably because of your [plan](https://www.appsflyer.com/pricing/)
if this is the case, please contact our Customer Engagement Team at hello@appsflyer.com. Thank you
