### ISSUE TITLE
21003 trying to call validateAndLogInAppPurchase on iOS

### ISSUE THREAD

**Issue by kyle-ssg** [AppsFlyerSDK/appsflyer-react-native-plugin#255]
# Report

## Plugin Version
6.2.10

## On what Platform are you having the issue?
iOS

## What did you do?

1: Made sure the SDK was setup to work with sandbox

```
appsFlyer.setUseReceiptValidationSandbox(true);
```

2: called validateAndLogInAppPurchase on iOS with 

```
{productIdentifier: "credits5_staging", currency: "GBP", transactionId: "1000000785911735", price: "3.99"}
```

## What did you expect to happen?

The IAP to be tracked.

## What happened instead?

JavaScript:
```
code: "E(null)0"
message: "Unknown error from a native module"
```

Native: 

```
[Validate] Response Info:{
    data = {length = 40, bytes = 0x7b22656e 7669726f 6e6d656e 74223a22 ... 223a3231 3030337d };
    dataStr = "{\"environment\":\"Sandbox\",\"status\":21003}";
    retries = 0;
    statusCode = 200;
    taskIdentifier = 15;
}
```

**Comment by pazlavi** [comment]
The error is from Apple's API. 
![Screen Shot 2018-08-19 at 14 56 31 (1)](https://user-images.githubusercontent.com/72502546/110339200-8dc1b580-8030-11eb-9730-f56c1a95780b.png)

**Comment by kyle-ssg** [comment]
Yep, not very useful since our api is already validating the purchase successfully. I think instead of using this I'll just log events with af_revenue etc

```
   appsFlyer.logEvent("purchase_"+purchase.productId, {
      af_revenue: foundProduct.price,
      af_currency: foundProduct.currency||'GBP'
    })
```
