### ISSUE TITLE
IOS 14

### ISSUE THREAD

**Issue by Holymith** [AppsFlyerSDK/appsflyer-react-native-plugin#256]
Is this plugin taking into account IOS 14.5 new rules of tracking user data? The AppTrackingTransparency permission.

**Comment by amit-kremer93** [comment]
Hi @Holymith yes this plugin is ready for iOS changes as you can see [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk). it's highly recommended for you to read also [Here](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#additional-apis-configuring-app-tracking-transparency-att-support)
