### ISSUE TITLE
Events not showing up on dashboard

### ISSUE THREAD

**Issue by B4ckes** [AppsFlyerSDK/appsflyer-react-native-plugin#258]
# Report
I'm implementing the app events, when i log the result i get a `success` string, so i presume that the implementation is correct, but when i go to the dashboard, there's no event being shown. The first event a tried to sent was 2 days ago.

## Plugin Version

6.2.10

## On what Platform are you having the issue?

ios and android

## What did you do?

```
appsFlyer.logEvent(
     'af_content_view',
      {
        af_content:  '/home',
      }
    )
```

## What did you expect to happen?

Event to be logged

## What happened instead?

No events where shown on events or activity dashboard.

## Please provide any other relevant information.

organic and non-organic installs being shown normally.

**Comment by amit-kremer93** [comment]
Hi @B4ckes thank you for opening this issue. in order to solve your problem, we need to get more details like the package name, devkey etc. please contact our support team via: support@appsflyer.com
