### ISSUE TITLE
 Deferred deep links don't work on all devices

### ISSUE THREAD

**Issue by Goldyukol** [AppsFlyerSDK/appsflyer-react-native-plugin#263]
# Report

## Plugin Version
`6.0.50`

## On what Platform are you having the issue?
 `ios and android`

## What did you do?
`Testing deferred deep links in App Store and Play Market`

## What did you expect to happen?
`Deferred deep links work on all devices`

## What happened instead?
`According to our tests, it works in one case out of four:
Samsung Galaxy S20,
Samsung Galaxy S9,
Iphone XR
Samsung Galaxy Tab S5e
Of all devices, the deep link worked only on the S20`

`Deferred deep links work in test mode, but do not work in app stores`

## Please provide any other relevant information.
`Implementation code`

`useEffect(() => {
    let onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
      res => {
        if (
          res &&
          res.data &&
          res.data.is_first_launch &&
          JSON.parse(res.data.is_first_launch) == true
        ) {
          setAppsFlyerData(res);
        }
      },
    );`

**Comment by amit-kremer93** [comment]
Hi @Goldyukol thank you for opening this issue. please contact our support in order to solve your problem: support@appsflyer.com
