### ISSUE TITLE
OneLink custom link is not opening the App when its installed

### ISSUE THREAD

**Issue by Lucasdsk** [AppsFlyerSDK/appsflyer-react-native-plugin#269]
# Report

## Plugin Version

`"react-native-appsflyer": "^6.2.30"`

## On what Platform are you having the issue?

`iOS`

## What did you do?

We've followed the docs to configure Branded Links and OneLink.
I've created a Gist to show our config.
https://gist.github.com/Lucasdsk/62cccd741446c65c345b291fea62a52d 

## What did you expect to happen?

Once we have the App installed and click on a link, the App should be opened.
Link: https://links.getcoral.app/MVvh/Heather

## What happened instead?

The Apple Store is opened.

## Please provide any other relevant information.

On Android we have the expected behavior.

**Comment by amit-kremer93** [comment]
@Lucasdsk thank you for opening this issue. please call `appsFlyer.setOneLinkCustomDomains` before you call `appsFlyer.initSdk`

**Comment by Lucasdsk** [comment]
hey @amit-kremer93 I've applied your suggestion to call `appsFlyer.setOneLinkCustomDomains` before calling `appsFlyer.initSdk` as you can see in the updated Gist: https://gist.github.com/Lucasdsk/62cccd741446c65c345b291fea62a52d#set-up-branded-links-in-the-app

But even doing that, when I click on a branded link, it opens the Apple Store, as you can see here:
https://drive.google.com/file/d/16bxEDUe6FoSB9WkOqPVI_fTBMv9Fs_t0/view?usp=sharing

Do you know if something else is missing in the config?

**Comment by amit-kremer93** [comment]
@Lucasdsk please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, production steps, logs, code snippets, and any additional relevant information.
