### ISSUE TITLE
How can I enable Apple SearchAds?

### ISSUE THREAD

**Issue by senolatac** [AppsFlyerSDK/appsflyer-react-native-plugin#274]
# Report

## Plugin Version

 `6.2.31`

## On what Platform are you having the issue?

ios

## What did you do?

```
  appsFlyer.initSdk(
    {
      isDebug: false,
      devKey: APPS_FLYER_DEV_KEY,
      appId: APPS_FLYER_APP_ID,
      onInstallConversionDataListener: true,
      timeToWaitForATTUserAuthorization: 10,
    },...

appsFlyer.logEvent(
    eventName,
    eventValues...
```

## What did you expect to happen?

 Event to be logged as organic and to be logged for non-organic for Apple SearchAds

## What happened instead?

All events logged as organic

## Please provide any other relevant information.

Actually, I try to use AppsFlyer for Apple SearchAds data collection but I could not track nnon-organic data with this configuration. Is there any other configuration that I missed?

**Comment by amit-kremer93** [comment]
Hi @senolatac thank you for opening this issue.
try to follow [this](https://support.appsflyer.com/hc/en-us/articles/213747963-Apple-Search-Ads-guide) guide. if you still not succeed please contact our support team: support@appsflyer.com
