### ISSUE TITLE
Event not showing in the SDK INTEGRATION TESTS dashboard

### ISSUE THREAD

**Issue by BogdanDemeny** [AppsFlyerSDK/appsflyer-react-native-plugin#275]
# Report

## Plugin Version

 `6.2.41`

## On what Platform are you having the issue?

**iOS**

## What did you do?

I've upgraded to 6.2.41 version and the events are not showing in the `SDK integration tests` anymore. 
The organic and non-organic tracking seems to be working fine.

I'm using the following block of code
```js
 appsFlyer.logEvent(
   "test_event",
   {},
    () => {
      console.log('Success');
    },
    error => {
       console.log('Success');
    },
  );
```

## What did you expect to happen?

Event to be logged in the dashboard

## What happened instead?

- The event is not showing in the dashboard - I did wait for about 10 minutes.
![image](https://user-images.githubusercontent.com/62950430/113175001-de4cbd00-9242-11eb-8337-238f6ed688b3.png)

- Success callback is called;
- No error returned.

## Please provide any other relevant information.

XCode Log:
```
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
<~+~   SEND Event:   https://inapps.appsflyer.com/api/v6.2/iosevent?app_id=XXXX&buildnumber=6.2.4
<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>

{"timestamp":"1617207082.130725","uid":"123","bundlename":"AppName","cell":{"mcc":"234","mnc":"15","ra":"CTRadioAccessTechnologyLTE"},"att_status":0,"platform":"iPhone12,3","fb_anon_id":"XZBDBCAAAA1111122223333","counter":"26","prev_session_dur":487,"reinstallCounter":"148","advertiserId":"","systemversion":"14.4.1","iaecounter":"16","lang_code":"en","JBDevice":false,"date3":"2021-03-31_155637+0100","deviceData":{"cpu_type":"ARM64","cpu_speed":"-1","osVersion":"14.4.1 (Build 18D61)","ram_size":"3778","cpu_64bits":"true","dim":{"y_px":2436,"x_px":1125},"device_model":"iPhone12,3","cpu_count":"6"},"sc_o":"fu","currentCountrycode":"GB","systemname":"iOS","date1":"2021-03-31_155632+0100","localizedmodel":"iPhone","ivc":false,"af_events_api":"1","bundleversion":"208","model":"iPhone","eventName":"test_event","dev_key":"myKey","currentLanguage":"en-GB","wifi":true,"vendorId":"asda","eventvalue":"%7B%7D","serverApiVersion":"6.2","af_timestamp":"1617207082130","advertiserIdEnabled":false,"cksm_v1":"1a20f11cccb910f3192005118e494999","ref":"blahRef;0;0;0;0;0","af_iad_data":{"Version3.1":{"iad-purchase-date":"2021-03-31T14:56:38Z","iad-keyword":"Keyword","iad-adgroup-id":"1234567890","iad-creativeset-id":"1234567890","iad-creativeset-name":"CreativeSetName","iad-campaign-id":"1234567890","iad-lineitem-id":"1234567890","iad-org-id":"1234567890","iad-conversion-date":"2021-03-31T14:56:38Z","iad-keyword-id":"12323222","iad-conversion-type":"Download","iad-country-or-region":"US","iad-org-name":"OrgName","iad-campaign-name":"CampaignName","iad-click-date":"2021-03-31T14:56:38Z","iad-attribution":"true","iad-adgroup-name":"AdGroupName","iad-keyword-matchtype":"Broad","iad-lineitem-name":"LineName"}},"event":"test_event","date1_2":"2021-03-31_155632+0100","disk":"3146\/60922","sessioncounter":"14","load_framework_result":"NotDetermined","date2":"2021-03-31_171122+0100","firstLaunchDate":"2021-03-31_155637+0100","originalAppsflyerId":"123","shortbundleversion":"2.21","platformextension":"ios_segment","bundleIdentifier":"myapp"}

<~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~+~~+~>
2021-03-31 17:11:31.472809+0100 AppName[22468:2993190] [DEBUG] AppsFlyer: [HTTP] 
Result: {
    data = {length = 2, bytes = 0x6f6b};
    dataStr = ok;
    retries = 2;
    statusCode = 200;
    taskIdentifier = 4;
}                
Error: (null)
```

**Comment by amit-kremer93** [comment]
@BogdanDemeny thank you for opening this issue. in order to help you in the best way, please contact our support team: support@appsflyer.com

**Comment by BogdanDemeny** [comment]
Thank you for your answer @amit-kremer93. I did contact the support but the only feedback that I got was "Test Again, the events seem to be saved correctly in the database". 

We are still struggling with this upgrade and we have to get it done ASAP. Could you please have a look over the issue again?

**Comment by gpontes98** [comment]
Same problem here, any resolve?

**Comment by gpontes98** [comment]
> Thank you for your answer @amit-kremer93. I did contact the support but the only feedback that I got was "Test Again, the events seem to be saved correctly in the database".
> 
> We are still struggling with this upgrade and we have to get it done ASAP. Could you please have a look over the issue again?

Same problem here, do you resolve this?

**Comment by BogdanDemeny** [comment]
Yes, we switched to adjust. They have many other issues but at least they answer to the support enquiries.

**Comment by lossen** [comment]
I have the same problem! Any updates on this?

**Comment by kjasd97** [comment]
I have the same problem! Any updates on this?

**Comment by tkud04** [comment]
Same here, please a solution would be nice

**Comment by zeforx123** [comment]
I have the same problem, can you share your solution?

**Comment by Ace090** [comment]
Same problem here

**Comment by AhmadIzaz** [comment]
It looks like the the testing part on the dashboard is still broke. I contacted the support and they said the same thing that data is correctly fine in our database , we will forward this issue to sdk team. Its been 3 years from today till this issue is being created. Looks like they have no interest in fixing this.
