### ISSUE TITLE
No is_deferred on the iOS onDeepLink callback

### ISSUE THREAD

**Issue by Taylor123** [AppsFlyerSDK/appsflyer-react-native-plugin#276]
# Report

## Plugin Version

`6.2.30`

## On what Platform are you having the issue?
iOS

## What did you do?
use deferred deep link (OneLink referral), then download the app.

## What did you expect to happen?
Some sort of indication that the opened link was a deferred deep link.

## What happened instead?
`is_deferred` is not in the response

**Comment by amit-kremer93** [comment]
Hi @Taylor123, `isDeferred ` was added in plugin version `6.2.31`

**Comment by Taylor123** [comment]
@amit-kremer93 looks like there's a typo in `6.2.42` assuming iOS and Android responses should be uniform.

iOS: `isDeffered`
Android: `isDeferred`
