### ISSUE TITLE
AppsFlyer events not showing up on dashboard

### ISSUE THREAD

**Issue by amitpatil77** [AppsFlyerSDK/appsflyer-react-native-plugin#277]
# Report

## Plugin Version

`5.4.40`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
e.g. ios and android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be logged

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. No uninstalls on my dashboard

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by pazlavi** [comment]
hi @amitpatil77 , 
In order to help you in the best way, please contact our support team: support@appsflyer.com 
When you opening the ticket, please attached code snippets of your implementation and AppsFlyer debug logs of a session that you sending events to our servers.
