### ISSUE TITLE
Expose requestTrackingAuthorization method

### ISSUE THREAD

**Issue by vambola** [AppsFlyerSDK/appsflyer-react-native-plugin#278]
According to https://support.appsflyer.com/hc/en-us/articles/207032066#integration-33-configuring-app-tracking-transparency-att-support we'll need to call requestTrackingAuthorization method to gain the user's permission to access their IDFA.

I cannot currently see any references to this function. Will it be added or is there a workaround for react native projects?

**Comment by af-fess** [comment]
`ATTrackingManager.requestTrackingAuthorization` API is not a part of the AppsFlyer SDK. You could search for another npm package that exposes it.
For example https://www.npmjs.com/package/react-native-tracking-transparency

**Comment by Norfeldt** [comment]
@af-fess  It would have been helpful if the (expo) setup mention that this is a required setup step in order to use AF
