### ISSUE TITLE
Plans to support IOS 14.5 with AppFlyerSdk 6.2.5

### ISSUE THREAD

**Issue by chenop** [AppsFlyerSDK/appsflyer-react-native-plugin#280]
Is there a plan to support IOS 14.5 with AppFlyerSdk 6.2.5?
When can we expect that?

**Comment by amit-kremer93** [comment]
Hi @chenop thank you for open this issue.
The current plugin version is supports iOS 14.5. you can read about it [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk)

**Comment by chenop** [comment]
Thank you for the quick response.

Its says
![image](https://user-images.githubusercontent.com/446575/115676774-95c38380-a358-11eb-92cc-8e1dafd22270.png)

So just double checking - version 6.2.42 is good for ios14.5?

**Comment by amit-kremer93** [comment]
version 6.2.42 is built for AppsFlyer iOS SDK 6.2.4 and it is good for iOS 14.5. we will soon upgrade for AppsFlyer iOS SDK 6.2.5
