### ISSUE TITLE
what will happened with app in AppStore when 14.5 ios will release? (the AppsFlayer version small then 6)

### ISSUE THREAD

**Issue by idanlevi1** [AppsFlyerSDK/appsflyer-react-native-plugin#282]
Hi, We have an Application in AppStore with `react-native-appsflyer: 5.4.4`
Do we have to upgrade to version 6+? 
The exsist application on the AppStore will still work?

* we use AppsFlyer for some data like report about actions and deep link

**Comment by amit-kremer93** [comment]
Hi @idanlevi1. Yes you have to upgrade and we always recommend to update to the latest version.
Please take a look on the breaking changes from 5.x.x to 6.x.x [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--breaking-changes)
and the `timeToWaitForATTUserAuthorization` parameter fo iOS 14.5 [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk)

**Comment by idanlevi1** [comment]
> Hi @idanlevi1. Yes you have to upgrade and we always recommend to update to the latest version.
> Please take a look on the breaking changes from 5.x.x to 6.x.x [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--breaking-changes)
> and the `timeToWaitForATTUserAuthorization` parameter fo iOS 14.5 [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk)

Thank you, you can tell me what will happen to existing app in AppStore?

**Comment by kuznetsov-from-wonderland** [comment]
@amit-kremer93 can you please clarify? I've got the latest version
`"react-native-appsflyer": "^6.3.0"`
and this packages installed `- AppsFlyerFramework (6.3.0)`pod for me.

I also use `'react-native-tracking-transparency'`

How to inform AppsFlyer (and should we?) when the tracking permission is granted ?

**Comment by amit-kremer93** [comment]
@kuznetsov-from-wonderland yes. you just need to set the time to wait and the sdk will automatically know the permission is granted
