### ISSUE TITLE
Link does not open straight in Safari (not exist app case)

### ISSUE THREAD

**Issue by idanlevi1** [AppsFlyerSDK/appsflyer-react-native-plugin#283]
We have a campaign on some site with a banner leading to our link (deep link)
in format `https://XXX.onelink.me/YYY/ZZZZZ`
Attribution parameters: 
`af_param_forwarding: false`
`af_force_deeplink: true`

In not exist application in the device case - we click on the banner and the safari browser open with an error popup:
![image](https://user-images.githubusercontent.com/21155847/115990268-efcb7f80-a5ca-11eb-846f-3522d9576ef4.png)
*Translate to English - `safari cannot open the page because the address is invalid`
in chrome, it's working fine

**Comment by amit-kremer93** [comment]
Hi @idanlevi1 and thank you for opening this issue.
Be sure you completed the [app setup](https://dev.appsflyer.com/hc/docs/initial-setup-2) for oneLink for each method (Universal links and URI scheme). in order to help you please contact our support team: support@appslfyer.com
