### ISSUE TITLE
App got rejected from the AppStore

### ISSUE THREAD

**Issue by eladgel** [AppsFlyerSDK/appsflyer-react-native-plugin#285]
![image](https://user-images.githubusercontent.com/412137/116473785-7e8b0700-a82c-11eb-874e-b2e7d1598732.png)

# Report

## Plugin Version

6.2.41

## On what Platform are you having the issue?

ios

## What did you do?

submitted version to apple

## What did you expect to happen?

App will be approved b/c it supports version 14.5

## What happened instead?

App was not approved

## Please provide any other relevant information.

Is there a link or something else I am missing here?

**Comment by amit-kremer93** [comment]
Hi @eladgel and thank you for opening this issue. Did you implement the [ATT pop-up](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#integration-33-configuring-app-tracking-transparency-att-support) and pass it the `timeToWaitForATTUserAuthorization` as mentioned [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk)?

**Comment by idanlevi1** [comment]
@eladgel  @amit-kremer93 
From now every app uploaded to the App store must be with an updated **Appsflyer** version? and update the code?
