### ISSUE TITLE
onInstallConversionData callback doesn't trigger if ATT is enabled?

### ISSUE THREAD

**Issue by gtsec** [AppsFlyerSDK/appsflyer-react-native-plugin#286]
# Report

## Plugin Version

6.2.42

## On what Platform are you having the issue?

iOS

## What did you do?

In my iOS settings, I have ATT disabled.
I rely on `appsFlyer.onInstallConversionData(res => ...)` being fired so I can then unhide the main contents of the app.

## What did you expect to happen?

onInstallConversionData to have its callback called. 

## What happened instead?

It never called. I think maybe on killing and reopening the app it did?

## Please provide any other relevant information.

I expected `source` to be either `success` or `failure`, instead of not getting a reply. Even with ATT off, I would still expect the callback to fire.

Also, maybe `appsFlyer.stop()`being run at some earlier time had somehow interfered and caused this issue.

----

I have stopped relying on the callback firing in order to satisfy some condition in my code, so instead I use `requestTrackingStatus()` to let me know a user has disabled ATT altogether and fulfilled the conditions for my app to work.

**Comment by amit-kremer93** [comment]
Hi @gtsec and thank you for opening this issue.
`appsFlyer.onInstallConversionData` is not related to the ATT and it will fire only after `appsFlyer.init` sends a launch.
 it can be delayed if you set number in the `timeToWaitForATTUserAuthorization` field like [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--initializing-the-sdk)

**Comment by gtsec** [comment]
My problem is different now, basically there is a scenario where:

1. User has my app already installed, ATT is disabled
2. User now enables ATT, opens app
3. In the following code, `appsFlyer.onInstallConversionData(res => ...` does not trigger again

```
appsFlyer.initSdk(
  {
    devKey: env.APPSFLYER_DEV_KEY,
    isDebug: env.IS_PRODUCTION == 'false',
    appId: env.APPSFLYER_APP_ID,
    onInstallConversionDataListener: true, // Optional
    onDeepLinkListener: true, // Optional
    timeToWaitForATTUserAuthorization: 10, // for iOS 14.5
  })
 
const App = () => {

  // some other code...
  
  useEffect(() => {
    let onInstallConversionDataCanceller = null // appsFlyer.onInstallConversionData(res => dispatch(setInstallationConversionData(res)))

    requestTrackingPermission().then(trackingStatus => {
      if (
        trackingStatus !== 'authorized' &&
        trackingStatus !== 'unavailable'
      ) {
        appsFlyer.stop(true)
        dispatch(setInstallationConversionStatus('failure'))
      } else { // user has suddenly allowed it
        onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(res => {
          dispatch(setInstallationConversionData(res))
        })
      }
      dispatch(setTrackingStatus(trackingStatus))
    })

    appsFlyer.getAppsFlyerUID((err, appsFlyerUID) => {
      if (err) {
        console.error('appsFlyer.getAppsFlyerUID error:', err);
      } else {
        dispatch(setAppsFlyerId(appsFlyerUID))
      }
    })

    return () => {
      onInstallConversionDataCanceller && onInstallConversionDataCanceller()
    }
  }, [])
 ```

**Comment by amit-kremer93** [comment]
Hi @gtsec. according to [this](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#additional-apis-optout), you must set the `appsFlyer.stop` to `false` if you want to trigger `appsFlyer.onInstallConversionData` again

**Comment by gtsec** [comment]
I'm experiencing this issue now regardless, on XCode + iOS Simulator at least. This is a bit of a pain and I have no idea why the callback doesn't call. It would be way, way better if the callback finishes no matter what, or at least throw some sort of error! Otherwise its just very difficult to figure out what I might have done wrong.

**Comment by gtsec** [comment]
Here's the code I had:
AppsFlyer version = 6.26
XCode 12.5, but also not working for someone else on 12.4

I've attempted putting `appsFlyer.onInstallConversionData(res => { ... })` at the very top of App.tsx, before I call `appsFlyer.initSdk()`, but the callback still never fires.... why?

**Comment by stanwrkt** [comment]
I have the same problem.

```
"react-native": "0.65.1",
"react-native-appsflyer": "^6.3.50"
```

```
appsFlyer.onInstallConversionData(res => {
    log.debug('onInstallConversionData', res.data)

    const isFirstLaunch = res?.data?.is_first_launch

    if (isFirstLaunch && JSON.parse(isFirstLaunch) === true) {
      ampInstance.setUserProperties(res.data)
    }
  })

  appsFlyer.initSdk({
    devKey: Config.APPSFLYER_KEY,
    isDebug: __DEV__,
    appId: Config.APPLE_APP_ID,
    timeToWaitForATTUserAuthorization: 5,
  })
```

Are there any updates?

**Comment by dennytosp** [comment]
Hi @amit-kremer93 , is there an update?
I also have this error in version 6.16.2
