### ISSUE TITLE
Problem compiling in M1 - React Native

### ISSUE THREAD

**Issue by estevg** [AppsFlyerSDK/appsflyer-react-native-plugin#288]
I have problems compiling the app on my macbook m1 
![image](https://user-images.githubusercontent.com/28814083/116621072-40fbac00-a908-11eb-8f7c-7d63ceae5a19.png)

Is there a solution to this problem?

**Comment by amit-kremer93** [comment]
Hi @estevg and thank you for opening this issue. The next version we will release (6.3.0) will support M1.
