### ISSUE TITLE
How to init SDK without waitForATTUserAuthorization

### ISSUE THREAD

**Issue by haipham-kontist** [AppsFlyerSDK/appsflyer-react-native-plugin#290]
# Report

In our app, we don't collect `IDFA`. We already use AppsFlyer's strict mode, but the app is rejected by Apple's app store due to the missing ATT prompt.

We're looking for a way to use AppsFlyer without the prompt. We found something in AppsFlyer's document [here](https://support.appsflyer.com/hc/en-us/articles/207032066#integration-33-configuring-app-tracking-transparency-att-support), that mentions AppsFlyer SDK can be initialized without `waitForATTUserAuthorization`.

So I have a few questions:
- After `waitForATTUserAuthorization` is disabled, is ATT prompt still required? In AppsFlyer's document, it's not explicitly mentioned.
- To disable `waitForATTUserAuthorization`, should we simply initialize AppsFlyer react native plugin without `timeToWaitForATTUserAuthorization`? It's not mentioned in the [README](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/README.md).

## Plugin Version

6.2.42

## On what Platform are you having the issue?

ios

**Comment by amit-kremer93** [comment]
Hi @haipham-kontist and thank you for opening this issue. You can init the sdk without the timeTo WaitForATTUserAutorization. The ATT pop-up is required by apple and it is not related to Appsflyer. If you have more questions, feel free to contact our support team: support@appsflyer.com
