### ISSUE TITLE
onDeepLink produces different payloads for deferred and non deferred link

### ISSUE THREAD

**Issue by Taylor123** [AppsFlyerSDK/appsflyer-react-native-plugin#292]
# Report

## Plugin Version
`"react-native-appsflyer": "^6.2.60"`

## On what Platform are you having the issue?
iOS and Android

## What did you do?
Open OneLink invite links deferred and non deferred.

## What did you expect to happen?
`onDeepLink` payloads to contain the same parameters no matter the circumstance

## What happened instead?
The non deferred contains `af_referrer_customer_id`, but it's missing from the deferred deep link.

## Please provide any other relevant information.
I've tried speaking with my CSM, but haven't gotten an answer as to why the payload is different under the deferred vs non deferred circumstances. If this is the intended behavior, it would be great if the docs could be updated to reflect it

**Comment by amit-kremer93** [comment]
Hi @Taylor123 and thank you for opening this issue.
According to [this](https://support.appsflyer.com/hc/en-us/articles/115004480866#generating-the-link) doc, you will get the `af_referrer_uid` and other values in the GCD (`onConversionDataSuccess`) when the user first launch the app. when the user opens an app that was installed from a link, you will get the values in the `onDeepLink`
