### ISSUE TITLE
Is there a way to access the advertisingId?

### ISSUE THREAD

**Issue by oaosman84** [AppsFlyerSDK/appsflyer-react-native-plugin#296]
I can't find a straightforward to access the advertisingId (use-case is I want to send it to a server so it can be sent with server-to-server events).

**Comment by amit-kremer93** [comment]
Hi @oaosman84 and thank you for opening this issue. You can't get the advertisingId from react-native-appsflyer plugin and you will need to use other RN plugin for this.
