### ISSUE TITLE
Deep Link -  `onAppOpenAttribution` function does not called (Android)

### ISSUE THREAD

**Issue by idanlevi1** [AppsFlyerSDK/appsflyer-react-native-plugin#297]
We try to upgrade the version from 5 to 6 and we have a problem with android (ios work well),
`onAppOpenAttribution` function does not called, when we open the application fron link we see the `onInstallConversionData` function called but `onAppOpenAttribution` not.

# Report

## Plugin Version

react-native-appsflyer `6.3.0`
react-native `0.61.5`

## On what Platform are you having the issue?
Android

## What did you expect to happen?
`onInstallConversionData` function will be called after the app open from deep link

## What happened instead?
`onAppOpenAttribution` function does not called

## Please provide any other relevant information.

our code:

```
export default class NavigatorContainer extends Component {
    constructor(props) {
        super(props);
        this.state = {
            appState: AppState.currentState,
        }

        this.onInstallConversionDataCanceller = appsFlyer.onInstallConversionData(
            (res) => {
                const isFirstLaunch = res ?.data ?.is_first_launch;
                console.log("%c [AppsFlyer] NavigatorContainer -> onInstallConversionData -> res", 'background: #244422; color: #FFF', res)
                if (isFirstLaunch && JSON.parse(isFirstLaunch) === true) {
                    if (res.data.af_status === 'Non-organic') {
                        let media_source = res.data.media_source;
                        let campaign = res.data.campaign;
                        this.checkAppModeLink(res)
                        console.log('[AppsFlyer] NavigatorContainer -> onInstallConversionData -> This is first launch and a Non-Organic install. Media source: ' + media_source + ' Campaign: ' + campaign);
                    } else if (res.data.af_status === 'Organic') {
                        console.log('[AppsFlyer] NavigatorContainer -> onInstallConversionData -> This is first launch and a Organic Install')
                    }
                } else {
                    console.log('[AppsFlyer] NavigatorContainer -> onInstallConversionData -> This is not first launch');
                }
            }
        );

        this.onAppOpenAttributionCanceller = appsFlyer.onAppOpenAttribution((res) => {
            console.log('%c onAppOpenAttribution', 'background: #222; color: #bada55', res);
            if (res.status == 'success') {
                this.checkAppModeLink(res)
            }
        });

        try {
                let appsFlyerOptions = {
                    isDebug: Config.APP_ENV != EnvType.PRODUCTION,
                    devKey: Config.APPSFLAYER_DEV_KEY,
                    appId: Config.APPSFLAYER_APP_ID
                }
                let result = await appsFlyer.initSdk(appsFlyerOptions);
                console.log("[AppsFlyer] initSdk -> result", result)
            } catch (error) {
                console.log("[AppsFlyer] initSdk -> error", error)
            }

    }

    checkAppModeLink = async (res) => {
        console.log('checkAppModeLink')
    }

    componentWillUnmount = () => {
        if (onInstallConversionDataCanceller) {
            this.onInstallConversionDataCanceller();
            console.log('unregister onInstallConversionDataCanceller');
            this.onInstallConversionDataCanceller = null;
        }
        if (onAppOpenAttributionCanceller) {
            this.onAppOpenAttributionCanceller();
            console.log('unregister onAppOpenAttributionCanceller');
            this.onAppOpenAttributionCanceller = null;
        }
    };

    render() {
        return <View> </View>
    }
}
```

**Comment by amit-kremer93** [comment]
Hi @idanlevi1 and thank you for opening this issue. Did you override the [method](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#-android-deep-links) `onNewIntent`?

**Comment by idanlevi1** [comment]
> Hi @idanlevi1 and thank you for opening this issue. Did you override the [method](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#-android-deep-links) `onNewIntent`?

Yes i put 
```
  //Appsflyer Deep link
  @Override
  public void onNewIntent(Intent intent) {
      super.onNewIntent(intent);
      setIntent(intent);
  }
```
inside `MainActivity` 
like the same before (when i used version 5)

**Comment by amit-kremer93** [comment]
@idanlevi1 does it work with `onDeepLink` listener? it can narrow down the problem

**Comment by idanlevi1** [comment]
> @idanlevi1 does it work with `onDeepLink` listener? it can narrow down the problem

I tried `onDeepLink` too and it's not work, 
Can you explain what the difference between the listeners?

**Comment by amit-kremer93** [comment]
@idanlevi1 they are subscribed to different methods with different logic in the native SDK. if you followed the docs and its not working, i recommend you to contact our support team: support@appsflyer.com

**Comment by idanlevi1** [comment]
> @idanlevi1 they are subscribed to different methods with different logic in the native SDK. if you followed the docs and its not working, i recommend you to contact our support team: [support@appsflyer.com](mailto:support@appsflyer.com)

Ok I sent message to support
