### ISSUE TITLE
[Docs] Unified deep linking contains link to "old" docs.

### ISSUE THREAD

**Issue by curiousdustin** [AppsFlyerSDK/appsflyer-react-native-plugin#298]
# Report

## Plugin Version

Docs

## On what Platform are you having the issue?

Docs 

## What did you do?

Read the docs.

## What did you expect to happen?

Current docs.

## What happened instead?

The [Unified deep linking](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md#Unified-deep-linking) guide contains a link to *[OneLink Guide here](https://dev.appsflyer.com/hc/docs/android-unified-deep-linking)*. This links to a page that is labeled "Old".

## Please provide any other relevant information.

Possible new link: https://dev.appsflyer.com/hc/docs/unified-deep-linking-udl

**Comment by amit-kremer93** [comment]
@curiousdustin fixed. Thanks
