### ISSUE TITLE
Track system events

### ISSUE THREAD

**Issue by kuznetsov-from-wonderland** [AppsFlyerSDK/appsflyer-react-native-plugin#299]
Dear all! How can I track system events like 
```
Application Installed
Application Opened
Application Updated
Application Backgrounded
Application Crashed
Application Uninstalled
```

**Comment by amit-kremer93** [comment]
Hi @kuznetsov-from-wonderland thank you for opening this issue. Appsflyer SDK records installs, sessions (app open) and application uninstalls and you can see them on your dashboard [see here](https://support.appsflyer.com/hc/en-us/articles/207032126-Android-SDK-integration-for-developers#core-apis). Application crashes, updated or life-cycle events can be logged with `appsFlyer.logEvent` with custom event name, but the sdk can't detect these events by himself. 
Please next time open the issue according to the template.
