### ISSUE TITLE
[Docs] Strict Mode Guide

### ISSUE THREAD

**Issue by artyorsh** [AppsFlyerSDK/appsflyer-react-native-plugin#300]
# Report

By following the [Strict Mode Guide](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--add-or-remove-strict-mode-for-app-kids), it's not clear that it's actually required to call the `changeMode.sh` script every time the dependency is installed. In my case, I've noticed that our CI workflow continued using `AppsFlyerFramework/Main` instead of `AppsFlyerFramework/Strict`. Consider mentioning that in the docs or better provide an ability to set a flag in the Podfile, [like it's done in RN Firebase](https://rnfirebase.io/analytics/usage#disable-ad-id-usage-on-ios).

Thanks!

**Comment by artyorsh** [comment]
One of the options to go with current implementation:

1. Create a script _./scripts/appsflyer-strict-mode.sh_
```shell
#!/usr/bin/env bash

cd ./node_modules/react-native-appsflyer && ./changeMode.sh strict && cd ../../
```
2. Make it executable
```
chmod +x ./scripts/set-appsflyer-strict-mode.sh
```

3. Run it on postinstall (package.json)
```json
  "scripts": {
    ...
    "postinstall": "./scripts/set-appsflyer-strict-mode.sh"
  },
```

**Comment by amit-kremer93** [comment]
@artyorsh thank you for opening this issue. we will take your suggestion and try to improve the developer's experience in the next versions. Thanks!
