### ISSUE TITLE
onDeepLink not triggered

### ISSUE THREAD

**Issue by poonai** [AppsFlyerSDK/appsflyer-react-native-plugin#304]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
6.3.20

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
android

## What did you do?
  Integrated appsflyer onDeepLink Listener
```js

    appsFlyer.onDeepLink((res) => {
        let data = res.data
        if (data?.invitedBy) {
            Storage.setItem(StorageItemKeys.referredBy, res.data.invitedBy)
        }
        if (data.screen && data.screen == NavigationKey.Game) {
            navigationRef.current.navigate(NavigationKey.Game)
        }
      
    });

    appsFlyer.initSdk(
        {
            devKey: appDetails.appsFlyerKey,
            isDebug: false, // set to true if you want to see data in the logs
            appId: appDetails.appStoreId, // iOS app id
            onDeepLinkListener: true
        },
        (result) => {
            console.log('Apps flyer sdk initialize', result)
        },
        (error) => {
            console.error('App flyer sdk not initialied', error)
        }
    )
```

## What did you expect to happen?
I would like that onDeepLink should be triggered even if the app starts.

## What happened instead?
appsFlyer.onDeepLink is not getting triggered when the app open from closed state. But it 
works if the app running in background

**Comment by pazlavi** [comment]
Hi @poonai , 
Thank you for reaching out to us. 

 In order for us to provide optimal support, we would kindly ask you to contact our support team at support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, your app ID, production steps, logs, code snippets, and any additional relevant information.

**Comment by inifaisal** [comment]
@pazlavi @amit-kremer93 I am also cannot run the `onDeepLink` event if the app not running.

**Comment by pazlavi** [comment]
@yvza please contact our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
