### ISSUE TITLE
[Feature Request] Add support for Expo Config Plugins

### ISSUE THREAD

**Issue by leggomuhgreggo** [AppsFlyerSDK/appsflyer-react-native-plugin#307]
Hello

I am on a team that's fixin to start work on a cross-platform Expo app, intended to replace our three legacy clients. Wanted to inquire whether y'all would consider adding support for [Config Plugins](https://docs.expo.io/guides/config-plugins/), so this library can be used with the Expo Managed Workflow (i.e. without ejecting)

Thanks for your consideration!

## Feature Context

Over the past several months Expo has introduced features which enable apps to use external native modules, without ejecting Expo's managed workflow. 

The customizations to the iOS and Android code that are required by a given native module are automated, using an AST-based API that Expo provides through  "Config Plugins" feature.

These automations (called "mods") are executed during a new "Prebuild" phase, in which boilerplate ios and android directories are created — and then their respective files are altered, based on the instructions in a given modules config plugin. The end result is essentially the same as if you ejected and manually changed the ios/android files. 

Here's the [Expo blog post](https://blog.expo.io/introducing-expo-run-commands-835ae8da4813) announcing Config Plugins and the associated feature-set.

## Overview of Proposed Implementation

The process for creating a Config Plugin is detailed here:
https://docs.expo.io/guides/config-plugins/#creating-a-plugin

There are a few different "recipes" for how to implement — but the gist of it is:

- Create the `app.plugin.js` file, at the project root — which serves as a standard entrypoint where expo can resolve the plugin code. [ex: [`expo-camera`](https://github.com/expo/expo/blob/master/packages/expo-camera/app.plugin.js)]
- Export a function prefixed using "with" (eg `withFeature`) which accepts a `config` object that can be used, along with `@expo/config-plugins` methods, to implement mods for each platform's native code. [ex: [`withCamera`](https://github.com/expo/expo/blob/master/packages/expo-camera/plugin/src/withCamera.ts)]
- Add mods corresponding to the setup steps in your README.md
- Celebrate!

**Comment by amit-kremer93** [comment]
Hi @leggomuhgreggo and thank you for opening this issue. We currently work on integrate config plugins inside our React native plugin and there are still some steps that are not complete in order to integrate it fully in the managed workflow.
There is [another issue](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/137) related to the subject keep posted there.

**Comment by HelgeSverre** [comment]
> Hi @leggomuhgreggo and thank you for opening this issue. We currently work on integrate config plugins inside our React native plugin and there are still some steps that are not complete in order to fully integrate it in the managed workflow. There is [another issue](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/137) related to the subject keep posted there.

Is there any updates on supporting Expo?
