### ISSUE TITLE
Link generated using generateInviteLink api doesn't work in Android

### ISSUE THREAD

**Issue by AsbarAli** [AppsFlyerSDK/appsflyer-react-native-plugin#309]
# Report
I generated the one link URL using the `generateInviteLink` API and call this URL in another android phone before download and install. Then in the `onInstallConversionData` method, returns as firstLaunch and organic install. It doesn't return any custom params i set for the `generateInviteLink` API.

Example of generated One Link URL  - https://quantfinance.onelink.me/bC1M/8e6cd156

## Plugin Version
 6.3.20
Android

## What did you do?
```

  async generateInvitationLink(
    generateLinkSuccess,
    generateLinkFailure,
    referralInput,
  ) {
    appsFlyer.setAppInviteOneLinkID('bC1M');

    appsFlyer.setOneLinkCustomDomains(
      ['quantfinance'],
      res => {
        console.log('res-link', res);
      },
      error => {
        console.log('error', error);
      },
    );

    appsFlyer.generateInviteLink(
      {
        channel: 'gmail',
        campaign: 'SMS Campaign',
        customerID: '123ref123',
        userParams: {
          referralId: referralInput,
        },
      },
      link => {
        generateLinkSuccess(link);
        console.log('link', link);
      },
      err => {
        generateLinkFailure();
      },
    );
  }

```

## What did you expect to happen?
Custom parameters should be returned where I set in `onInstallConversionData` API. This works fine in iOS Simulator and device in debug mode. (Still didn't check in release mode)

## What happened instead?
invitation link doesn't work and return as **first launch** and **organic install** in `onInstallConversionData` API

**Comment by pazlavi** [comment]
Hi @AsbarAli 
Thank you for reaching out to us.

In order for us to provide optimal support,  please submit a ticket to our support team at support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, production steps, logs, code snippets, and any additional relevant information.

**Comment by eduardorfreitas93** [comment]
@AsbarAli Any solution?

**Comment by amit-kremer93** [comment]
@AsbarAli please contact our support team. it looks like configuration problem
