### ISSUE TITLE
setOneLinkCustomDomains API doesn't work

### ISSUE THREAD

**Issue by AsbarAli** [AppsFlyerSDK/appsflyer-react-native-plugin#310]
# Report
Setup branded Link (**go.quant.finance**) in Appslfyer and tried to generate invitation link through `generateInviteLink` API.

Before initializing the SDK, I use the `setOneLinkCustomDomains` API to generate the invitation link with the custom domain. So, I expect the invitation link should be like this,

`https://go.quant.finance/bC1M/877ed5c7`

But it generates the URL as `https://quantfinance.onelink.me/bC1M/2510af51` and **quantfinance** is the Subdomain i gave to the One Link Template.

## Plugin Version
6.3.20
iOS and Android

## What did you do?

**1. Set Onelink custom/branded domains**

```
appsFlyer.setOneLinkCustomDomains(
    ['go.quant.finance', 'app.quant.finance'],
    res => {
      console.log('res-link', res);
    },
    error => {
      console.log('error', error);
    },
  );
```

**2. SDK Initialization**
```
appsFlyer.initSdk(
    this.options,
    result => {
      console.log(result);
    },
    error => {
      console.error('error' + Platform.OS + '-OS' + error);
    },
  );
```

**3. Generate Invitation Link**
```
appsFlyer.setAppInviteOneLinkID('bC1M');

appsFlyer.generateInviteLink(
  {
    channel: 'gmail',
    campaign: 'SMS Campaign',
    customerID: '123ref123',
    userParams: {
      referralId: referralInput,
    },
  },
  link => {
    generateLinkSuccess(link);
    console.log('link', link);
  },
  err => {
    generateLinkFailure();
  },
);
```

## What did you expect to happen?

I expect the invitation link should be like this,

https://go.quant.finance/bC1M/877ed5c7

## What happened instead?

it generates the URL as https://quantfinance.onelink.me/bC1M/2510af51 and **quantfinance** is the Subdomain i gave to the One Link Template.

**Comment by amit-kremer93** [comment]
Hi @AsbarAli Thank you for reaching out to us.
Please be sure you follow [these](https://support.appsflyer.com/hc/en-us/articles/360002329137-Implementing-Branded-Links) steps. If it's still doesn't work, please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, production steps, logs, code snippets, and any additional relevant information.

**Comment by AsbarAli** [comment]
```
 appsFlyer.generateInviteLink(
      {
        channel: 'gmail',
        campaign: 'SMS Campaign',
        customerID: '123ref123',
        brandDomain: 'staging-app.quant.finance',
        userParams: {
          referralId: referralInput,
        },
      },
      link => {
        generateLinkSuccess(link);
        console.log('link', link);
      },
      err => {
        generateLinkFailure();
      },
    );
  }
```

If I set the brand name as you mentioned, then i get the URL like this. its pretty ugly.

https://staging-app.quant.finance/bC1M?c=SMS%20Campaign&af_referrer_uid=1626684730430-9443161&af_channel=gmail&af_dp=quantfinance%3A%2F%2F&af_siteid=1576352751&referralId=0x708eI2J431fE&af_referrer_customer_id=123ref123&pid=af_app_invites
