### ISSUE TITLE
Unable to run jest when file use appsflyer

### ISSUE THREAD

**Issue by Balasnest** [AppsFlyerSDK/appsflyer-react-native-plugin#315]
I have used appsflyer in one home.js file and when I do test case for that file it causing issues in AppsFlyer. It is working for other files where AppsFlyer is not used.

How to resolve this?

# Report
<img width="1261" alt="Screenshot 2021-08-22 at 9 52 13 PM" src="https://user-images.githubusercontent.com/6050520/130362626-00756c5f-2e34-429c-8766-0912001534e0.png">

## Plugin Version

ℹ Please replace these two lines with the plugin version.
"react-native-appsflyer": "6.2.60",

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
ios and android

## What did you do?
npm jest

## What did you expect to happen?
test should run

## What happened instead?
Getting parse error in appflyer index file

**Comment by Balasnest** [comment]
@af-margot @af-fess can you help me out please? Thanks.

**Comment by Balasnest** [comment]
Getting this error if I add`transformIgnorePatterns`

```
"jest": {
    "preset": "react-native",
    "transform": {
      "node_modules/react-native/.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native)/)"
    ]
  },
```

<img width="1425" alt="Screenshot 2021-08-22 at 11 20 31 PM" src="https://user-images.githubusercontent.com/6050520/130364975-0b787f5e-907f-4033-98c5-8e2f6155e47d.png">

**Comment by Balasnest** [comment]
@amit-kremer93 let me know how can I solve this

**Comment by amit-kremer93** [comment]
Hi @Balasnest and thank you for contact us. The problem seems to be with Jest, because you are trying to test your app, which imports appsflyer plugin which imports other packages (all in ES6 js). You need to configure jest for that.
Please more read [Here](https://dev.to/bytebodger/how-i-fixed-the-unexpected-token-error-in-jest-4o1j)
