### ISSUE TITLE
how do i track revenue ?

### ISSUE THREAD

**Issue by CallmeKingsley** [AppsFlyerSDK/appsflyer-react-native-plugin#316]
I am currently use "react-native-appsflyer": "^6.3.20",

I am currently working on an eCommerce platform and we need to be able to log in to our purchase per sale

**Comment by amit-kremer93** [comment]
Hi @CallmeKingsley, Thank you for reaching out to us.
You can look for more information in our [support page](https://support.appsflyer.com/hc/en-us/articles/115005544169-Rich-in-app-events-guide#introduction). If you still didn't find what you are looking for, please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, production steps, logs, code snippets, and any additional relevant information.
