### ISSUE TITLE
onInstallConversionData called twice

### ISSUE THREAD

**Issue by hukpavlo** [AppsFlyerSDK/appsflyer-react-native-plugin#319]
## Plugin Version

6.3.20

## On what Platform are you having the issue?

ios

## What did you do?

installed the app or placed it in the background and opened it again

## What did you expect to happen?

call onInstallConversionData one time

## What happened instead?

`onInstallConversionData` called twice right after install and app state change (why do we need to call it after state change ?)

## Please provide any other relevant information.

Works fine without `continueUserActivity` implementation, not sure why do I need it?

My code:
![image](https://user-images.githubusercontent.com/40897161/131850429-24022b23-3500-4940-bde6-7fd8122cb95c.png)

**Comment by ge-af** [comment]
@hukpavlo 
Thank you for reaching out to us.

The `onInstallConversionData` method is being called every time the `applicationDidBecomeActive` is being invoked. Inside this AppDelegate's function we are starting the SDK and we will create a new session each time.

If you wish to distinguish between both calls to `onInstallConversionData`  you have the `is_first_launch`  boolean flag you can depend on inside this callback return values.

**Comment by hukpavlo** [comment]
@ge-af Thanks for a very quick reply, If I remove the `continueUserActrivity` handler will I broke an sdk? I just need deep linking support and  to be able to track the first install, I don't see a point to receive events every time my app did become active

**Comment by ge-af** [comment]
@hukpavlo 

Yes, removing the `continueUserActivity` method will break **direct** deep linking logic and you won't be able to get deep linking while the application is already installed on the device.

I can recommend to use the boolean mentioned above for your specific use case.
You can also unregister the listener of `onInstallConversionData` once you already consumed it.

**Comment by hukpavlo** [comment]
@ge-af I'll try, after the install, I receive 2 onInstallConversionData immediately, are you sure they'll have different flags?

**Comment by hukpavlo** [comment]
I found that is_first_launch is always false, even for brand new users, tested on many devices

**Comment by ge-af** [comment]
Hi @hukpavlo 

Only the first onInstallConversionData should indicate **is_first_launch: true**

If this is not the case, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information in order to provide optimal support.

**Comment by hukpavlo** [comment]
> Hi @hukpavlo 
> 
> 
> 
> Only the first onInstallConversionData should indicate **is_first_launch: true**
> 
> 
> 
> If this is not the case, we would kindly ask you to submit a support ticket to support@appsflyer.com.
> 
> When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information in order to provide optimal support.

Thanks, already did that
