### ISSUE TITLE
generateInviteLink and OG tags

### ISSUE THREAD

**Issue by cark1** [AppsFlyerSDK/appsflyer-react-native-plugin#320]
Hello, how can I add the OG tags to the link generated with the function `generateInviteLink`?

I found this guide: https://support.appsflyer.com/hc/en-us/articles/207032246#create-a-social-media-preview, but it's not clear how to use the OG tags params with the SDK.

**Comment by amit-kremer93** [comment]
Hi @cark1 and thank you for reaching out! You can add OG tags inside the `userParams` nested object like this:
```
appsFlyer.generateInviteLink(
 {
   channel: 'gmail',
   campaign: 'myCampaign',
   customerID: '1234',
   userParams: {
      af_og_title: "dwed",
      af_og_description: "ddd",
      af_og_image: "test",
     // more data //
   },
 },
 (link) => {
   console.log(link);
 },
 (err) => {
   console.log(err);
 }
);
```

**Comment by cark1** [comment]
Thank you! The problem was with the af_og_image. I passed an empty string. Passing an empty string all the other params were ignored.

**Comment by ahmadsyed** [comment]
Hi @cark1 ,
As per this doc ( https://support.appsflyer.com/hc/en-us/articles/207032246#create-a-social-media-preview), I added all three params for my link, But when I am sharing my link on social media , Its showing OLD text and Image only.
OG tags are not getting updated.

**Comment by AnshIcode** [comment]
@cark1 @ahmadsyed @amit-kremer93 @benlaverriere @gabecoyne Same issue is happening with me, i have added the og tags and still the default og tags are showing... how can i add the tags? in social media preview 
i am sending like these for generating the link
  channel: 'userinvite',
          userParams: {
            af_og_title: productName,
            af_og_description: productDescription,
            af_og_image: imageUrl,
            deep_link_value: deepLinkValue,
            af_dp: 'popseekl://',
          },

**Comment by MrPiao** [comment]
Just wanted to chime in (despite the thread being so old) and say that all three (title, description, and image) has to be set or they are all ignored.
