### ISSUE TITLE
Deep-linking with React Navigation

### ISSUE THREAD

**Issue by awkpagong** [AppsFlyerSDK/appsflyer-react-native-plugin#321]
# Report

Is there a way to imperatively get the deep-link params that the app was launched with? I am trying to integrate with React Navigation V6, and I need a way to get the initial params inside of the `getInitialURL` function, similar to how the [React Navigation example](https://reactnavigation.org/docs/deep-linking#third-party-integrations) calls `branch.getFirstReferringParams()`. I know AppsFlyer's SDK exposes deep-linking callbacks (`onInstallConversionData`, `onAppOpenAttribution`, and `onDeepLink`), but I'm not sure how I can call these imperatively from inside React Navigation's `getInitialURL` function. Thanks in advance for any help you can offer!

**Comment by amit-kremer93** [comment]
Hi @awkpagong and thank you for contacting us.
Initial parameters can only be retrieved from `onInstallConversionData ` and `onDeepLink`. Notice that you must use AppsFlyer delegate methods in the AppDelegate and not `RCTLinkingManager` in order to trigger the deep link flow.

**Comment by awkpagong** [comment]
> Hi @awkpagong and thank you for contacting us.
> Initial parameters can only be retrieved from `onInstallConversionData ` and `onDeepLink`. Notice that you must use AppsFlyer delegate methods in the AppDelegate and not `RCTLinkingManager` in order to trigger the deep link flow.

Hi @amit-kremer93, thanks for the response. My issue is that I have no way of knowing if a OneLink is being opened inside of react-navigation's `getInitialURL()` function. As a result, my app is loading the default initial route, and then almost immediately resetting the app state when the AppsFlyer `onDeepLink` function gets called. As you can imagine, this creates an undesirable screen flash whenever a OneLink is opened and the navigation state gets reset. Are you aware of any way to work around this issue? Ideally I only want to render a single screen when a OneLink is opened.

**Comment by amit-kremer93** [comment]
We have a sample app in this project [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/tree/master/SampleApps/AppsFlyerExample). We are not using RCTLinkingManager, just AppsFlyer delegate methods

**Comment by Deep-CB** [comment]
Hi @amit-kremer93 
**How I know App is opened from deep link or normally** 
when app is open from deep link appsFlyer.onDeepLink method is called and gives the response 
but when app is open in normal way onDeepLink method did not  called or not gives any response 

How we will handle our navigation accordingly without any knowing the app is opened from deep link or not 

appsFlyer.onInstallConversionData method always gives this data if i will open app from deep link or open normal app

af_message: "organic install"
af_status: "Organic"
install_time: "2021-11-10 11:44:15.657"
is_first_launch: false
[[Prototype]]: Object
status: "success"
type: "onInstallConversionDataLoaded"

Please help !!!
How to handle app navigation without any detection of this thing App is opened from deep link or not there is no status which are telling the dev anything .....

**Comment by amit-kremer93** [comment]
@Deep-CB like you mentioned, if the appsFlyer.onDeepLink is called it means that the app opened from deeplink. if appsFlyer.onDeepLink didn't called so its a normal open

**Comment by eliverto-moraes-develcode** [comment]
> 

@amit-kremer93 I am have a problem with UDL links, when my app is open and i click on UDL link the callback appsFlyer.onDeepLink is not called, but if my app is closed the callback is called and redirect the user correctly.

**Comment by ShaunLWM** [comment]
@amit-kremer93 same problem here.

When app is **closed/terminated (basically not running)**, opening the deeplink url opens the app and `onDeepLink` is triggered.

However, when the app is in the **foreground** (example: user is using the app) and a deeplink is clicked (somehow), `onDeepLink` does not get triggered.

Please advise.

**Comment by andrisLaduzans** [comment]
@amit-kremer93 could you please provide solution? why is this thread simply closed when there is 0 solution or explanation provided?
i have followed documentation and also found an example of `onDeepLink` implementation in example app
[here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/demos/appsflyer-react-native-app/components/HomeScreen.js) . But it does not solve the problem with deepLink foreground listener.

**Comment by ShaunLWM** [comment]
@andrisLaduzans have you tried this?
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/DeepLink.md#-android-deeplink-setup

**Comment by amit-kremer93** [comment]
@andrisLaduzans this is something that needs deeper investigation. I suggest you to contact our support team: support@appsflyer.com with code snippets of your code.

**Comment by andrisLaduzans** [comment]
> @andrisLaduzans have you tried this? https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/DeepLink.md#-android-deeplink-setup

yes, i already mentioned , that i have done all steps of installation, integration,  and testing. The only problem that remains is 'foreground' deepLinks listening. i am also using react-react-native navigation v6

also previously used firebase deepLinking api and implemented exactly how it 'should be done' according to documentation [deep-linking#third-party-integrations](https://reactnavigation.org/docs/deep-linking#third-party-integrations) and it worked flawlessly. 

I have also tried implementing appsFlyer's `onDeepLink` api in similar manner (using react-native-navigation Linking api) but it just does not work. Only way is using the `useEffect` method in some screen... so now i have to refactor half of the codebase to compliment this approach. so sorry for me being a bit 'salty'.

 And this thread is covering exactly the same problem i have but is closed without any support or solution.

**Comment by nikodevv** [comment]
Our team is also facing this issue

**Comment by gakinson** [comment]
I have been fiddling around with this and one workaround that I did that seemed to work was leveraging the appsflyer function: performOnAppAttribution
https://support.appsflyer.com/hc/en-us/articles/4410482202897#performonappattribution

This function will process a link that you pass in as a parameter. So I have all the usual React-Navigation setup and the appsflyer listeners (appsFlyer.onAppOpenAttribution, etc). Then I also added the listener in a useEffect for Linking as such:
```
  useEffect(() => {
    const listener = Linking.addListener('url', event => {
      if (event?.url) {
        if (event.url.includes(`/${APPSFLYER_ONE_LINK_ID}/`)) {
          //This will process the link as a onelink if it contains the appsflyerOnelink ID.
          // This is the workaround to process both appsflyer and non appsflyer links.
          appsFlyer.performOnAppAttribution(
            event.url,
            res => {
              console.log('Processed a oneLink', res);
            },
            error => {
              console.log('Failed to process a oneLink', error);
            },
          );
        }

    return () => {
      listener.remove();
    };
  }, []);
```


This will then trigger the onAppOpenAttribution, etc and do the correct deconstruction.

Hopefully this helps!

**Comment by sprutner** [comment]
@gakinson would you mind giving me a full example of this with react navigation?
