### ISSUE TITLE
Clarifications on ConversionData

### ISSUE THREAD

**Issue by bradherman** [AppsFlyerSDK/appsflyer-react-native-plugin#323]
# Question

When looking at documentation for AppsFlyer linking, things like `campaign` and `media_source` have parameter names like `c` and `pid`.  Others are of the format when creating links `af_ad` for instance.  

In the documentation for this SDK, we see that the example and typedef for `ConversionData` includes data with a key of `campaign` and `media_source` so it appears the SDK is doing some manipulation of the data included with the link.

What type of manipulation happens?  If I were to include `af_adset`, would it show up as `ConversionData.data.adset` for instance?  The documentation is a little unclear on what is happening here.

**Comment by pazlavi** [comment]
Hi @bradherman ,
Thank you for reaching out to us.

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by bradherman** [comment]
This isn't a bug and doesn't require any reproduction or code... If you read my question it's just stating that the documentation is unclear about the params in a ConversionData set
