### ISSUE TITLE
Referrer link

### ISSUE THREAD

**Issue by jonathanroze** [AppsFlyerSDK/appsflyer-react-native-plugin#326]
# Report

## Plugin Version

"react-native-appsflyer": "^6.4.0",

## What did you expect to happen?

A shortened link generated with this pattern `https://myapp.onelink.me/abcd/efgh`

## What happened instead?

A full link with a lot of parameters that's not working 

`https://go.onelink.me/4AAABerr?&c=myCampaign&myParam=newUser&af_referrer_uid=1631806865781-3138650&af_channel=gmail&anotherParam=fromWeb&af_siteid=1566738201&af_referrer_customer_id=1234&pid=af_app_invites
`
## Please provide any other relevant information.

My code
```


 const defineOneLinkId = await appsFlyer.setAppInviteOneLinkID(`${referrerId.toUpperCase()}`);
  appsFlyer.generateInviteLink(
    {
      channel: 'gmail',
      campaign: 'myCampaign',
      customerID: '1234',
      userParams: {
        myParam: 'newUser',
        anotherParam: 'fromWeb',
        amount: 1,
      },
    },
    (link) => {
      console.log(link);
      dLink = link;
      setLoading(false);
      setUrl(dLink);
      Share.share(....);
    },
    (err) => {
      console.log(err);
      setLoading(false);
    },
  );
```

Thanks

**Comment by mi-chal** [comment]
@jonathanroze Hi. Were you able to resolve this issue? I'm facing exactly the same behaviour on Android.

**Comment by tanayzepto** [comment]
> [@jonathanroze](https://github.com/jonathanroze)  [mi-chal](https://github.com/mi-chal) Were you able solve this issue ?

**Comment by minuhariharan** [comment]
Was anyone able to resolve this issue, this happens for us occasionally on Android, please let me know if you were able to resolve this
