### ISSUE TITLE
[iOS] Unable to get link parameters in onDeepLink method when app opened from closed state

### ISSUE THREAD

**Issue by rm-key** [AppsFlyerSDK/appsflyer-react-native-plugin#327]
# Report
The onDeepLink method is not having the link parameters, though it is getting invoked every time the link is being clicked.

## Plugin Version
"react-native": "0.64.0",
"react-native-appsflyer": "^6.3.20",

## On what Platform are you having the issue?

iOS

## What did you do?

-> Installed react-native-appsflyer plugin & did pod install
-> Followed the steps to open app via deep linking in Android & iOS
-> Followed the [docs](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Guides.md) to handle Unified Deep Linking in Android & iOS
-> Handled link parameters within the app & added redirection logic based on the response received in onDeepLink method

## What did you expect to happen?

When clicking on a onelink,
-> the app should open and receive link parameters in `onDeepLink` method

## What happened instead?

When clicking on a onelink,

-> if the app was in closed state,
        the app got opened, but didn't receive the expected link parameters
        instead it got `{ dismiss: 1, is_weak_match: 1}`
        afterwards, if the app is kept in the recent apps list, and then resumed, the `onDeepLink` method gives out the expected link parameters.
        
-> if the app was in background,
        the app got opened, and received the expected link parameters

## Please provide any other relevant information.

-> Firebase deep linking also exists along with AppsFlyer.
-> Android part for AppsFlyer deep linking works fine (in closed & background state)

**Comment by ge-af** [comment]
Hi @rm-key ,
Thank you for reaching out to us!

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
