### ISSUE TITLE
No able to run android app AppsFlyerLib.getInstance().setSharingFilterForPartners(null);

### ISSUE THREAD

**Issue by vinaysgl** [AppsFlyerSDK/appsflyer-react-native-plugin#336]
node_modules/react-native-appsflyer/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java:607: warning: non-varargs call of varargs method with inexact argument type for last parameter;
          AppsFlyerLib.getInstance().setSharingFilterForPartners(null);
                                                                 ^

# Report

## Plugin Version

`6.4.0`

## On what Platform are you having the issue?
Android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `react-native run-android`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
should run successfully

**Comment by amit-kremer93** [comment]
what version of RN do you use? it's just a warning or the app crashes also?

**Comment by tiagobnobrega** [comment]
I got the same error. I'm using RN 0.63.4. For me the app build fails on android. Downgrading to the plugin version 6.3.50 fixed the issue.

**Comment by amit-kremer93** [comment]
@tiagobnobrega @vinaysgl can you please share your code where you call `appsFlyer.setSharingFilterForPartners`?

**Comment by Chae-Sumin** [comment]
In m1 (monerey 12.0.1)
The same error occurred when using `npx react-native run-andeoid` using `RN 0.66.0` and  `plugin version 6.5.20`
And I've never called `appsFlyer.setSharingFilterForPartners`

**Comment by CuongNVietCetera** [comment]
@amit-kremer93 I got the same issue, app build fail on android, on both 6.4.x and 6.5.20. Downgrading to the plugin version 6.3.50 fixed the issue.

**Comment by amit-kremer93** [comment]
@CuongNVietCetera which JDK version do you use?

**Comment by CuongNVietCetera** [comment]
@amit-kremer93 oh I got error with my old jdk 8. Just update to jdk 11 and it works now, thank you!

**Comment by ahmadsyed** [comment]
Any fixes yet ? getting same issue after upgrading react-native to 0.70

**Comment by AlekseyLupach** [comment]
> 
had the same problem. this guide helped:
https://dev.appsflyer.com/hc/docs/install-android-sdk

**Comment by 0mayur1** [comment]
@vinaysgl  I got the same issue 

**-** Downgrading to the react-native-appsflyer version : **6.3.50**
**-** Downgrading to the react native moengage version  : **8.1.2**

fixed the issue.
