### ISSUE TITLE
How to use setCustomerUserId function?

### ISSUE THREAD

**Issue by 15110011** [AppsFlyerSDK/appsflyer-react-native-plugin#337]
I need to add user id for CVV, how can i solve this?

**Comment by willerrodrigo** [comment]
Here CUID has not appearing on CVV too, any solution?

**Comment by willerrodrigo** [comment]
@15110011 I found the solution. It's necessary set CUID before initSdk.

@amit-kremer93 Why is it necessary? Is there a way to improve it?
