### ISSUE TITLE
AppsFlyer crashing on Android while calling getAppsFlyerUID

### ISSUE THREAD

**Issue by madandrija** [AppsFlyerSDK/appsflyer-react-native-plugin#338]
# Report

After releasing the new version of our [Madbarz application](https://play.google.com/store/apps/details?id=com.madbarz.madbarzApp&hl=en&gl=US), we've started seeing crashes in Bugsnag for some of our Android users (it's Android only error, no iOS errors were reported). 

The stacktrace we get:

```
java.lang.IllegalStateException: Context must be set via setContext method before calling this dependency.       
at com.appsflyer.internal.be.AFInAppEventType(unknown:1120)         
at com.appsflyer.internal.ai.getAppsFlyerUID(unknown:2818)         
at com.appsflyer.reactnative.RNAppsFlyerModule.getAppsFlyerUID(RNAppsFlyerModule.java:330)         
at java.lang.reflect.Method.invoke(Method.java:-2)        
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)         
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)         
at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java:-2)         
at android.os.Handler.handleCallback(Handler.java:883)         
at android.os.Handler.dispatchMessage(Handler.java:100)         
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)         at android.os.Looper.loop(Looper.java:214)         
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)         
at java.lang.Thread.run(Thread.java:919)
```

Looking at the Breadcrumbs/data Bugsnag provides, the crash happens on app launch (within the first 5 seconds).
Looking at the code we're using, the only place we retrieve the `UUID` is in our [Redux Saga](https://redux-saga.js.org/):

```
export function* appsFlyerActionsOnProfileRecieved(id: string) {
  yield appsFlyer.setCustomerUserId(id, noop);
  try {
    const appsFlyerInitialised = yield* select(appsFlyerInitialisedAction);
    if (appsFlyerInitialised) {
      const resolvedUuid = (yield* cps(appsFlyer.getAppsFlyerUID)) as unknown as string | null;
      if (resolvedUuid) {
        yield* put(sendAppsFlyerIDToServerAction(resolvedUuid));
      }
    }
  } catch (error) {
    logError({ error: "Appsflyer not resolving uuid" });
  }
}
```

The saga call triggers after we update the user profile, and the user profile updates after the app finishes [rehydration](https://github.com/rt2zz/redux-persist), so there is the possibility that appsFlyer isn't initialised in JS when the call for UUID is made. The reasons I'm opening this issue are:

1. I couldn't find any "`isAppsFlyerInitialised`" method so I could do the check before the call, am I missing something?
2. The `getAppsFlyerUID` is using `getReactApplicationContext()` and I don't understand why does it need the `AppContext` (as far as I can see, iOS doesn't need it), but also, why isn't it using the one assigned in the `constructor` (especially since the method isn't `static`)?

## Plugin Version

6.4.0

## On what Platform are you having the issue?

android

## Please provide any other relevant information.

We're using `ReactNativeNavigation`, perhaps that's something that's influencing context setting.

**Comment by ge-af** [comment]
Hi @madandrija 

Thank you for reaching out!

This issue was specifically on the v6.4.0 Android SDK version when calling getAppsFlyerUID before init/start. It was dependent on the context given from those 2 methods. This happens if you call `getAppsFlyerUID` method before initializing the SDK. Is it indeed the case here?

We are expecting to issue a new version for the React Native plugin in the next few days with a fix for this issue.

**Comment by madandrija** [comment]
Hi @ge-af,

thanks for the quick response!

This is indeed the case as we, after your comment, went back and found a bug in our code - even though we were checking for `appsFlyerInitialising` via `redux` by dispatching `appsFlyerInitialisedAction`

```
 appsFlyer
    .initSdk({
    ...
    })
    .then(() => {
      store.dispatch(appsFlyerInitialisedAction());
    })

``` 

we had an error in the `saga` I've pasted above - `const appsFlyerInitialised = yield* select(appsFlyerInitialisedAction);`; we were selecting the `action` instead of the `selector` 🤦 

We'll be watching the repo for the fix, and again, thanks for the quick response!

**Comment by oussamakenzup** [comment]
Hello, I experienced the same issue on Android as well, iOS works great. Is there any estimate when it will be updated?
