### ISSUE TITLE
oneLink not work when app is open

### ISSUE THREAD

**Issue by aharon-vish** [AppsFlyerSDK/appsflyer-react-native-plugin#339]
Hello,
I am using react-native-AppsFlyer 6.4.0.

I am trying to trigger onelink (deeplink) when the user clicks on in-app-message.

when it's example://myRides it's works fine and Im route to the myRides screen , but when i am using 
https://example.onelink.me/xxxx/xxxxx it's not working and nothing happens. 

https://example.onelink.me/xxxx/xxxxx this link from push notification work fine.

![Screen Shot 2021-11-11 at 17 10 00](https://user-images.githubusercontent.com/12031960/141321468-a9e4b101-6bce-4fe1-a87b-e21059168d88.png)

**Comment by aharon-vish** [comment]
sdfsdf

**Comment by pazlavi** [comment]
Hi @aharon-vish,
Thank you for reaching out to us.

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
