### ISSUE TITLE
Falsely uses strict mode when the config `$RNAppsFlyerStrictMode=false` is explicitly set

### ISSUE THREAD

**Issue by reichhartd** [AppsFlyerSDK/appsflyer-react-native-plugin#340]
# Report

## Plugin Version

`react-native-appsflyer: 6.4.0`
`AppsFlyerFramework 6.4.0`

## On what Platform are you having the issue?

iOS

## What did you do?

When I run `pod install`, I get the following note:
```
react-native-appsflyer: Using default AppsFlyerFramework.You may require App Tracking Transparency. Not allowed for Kids apps.
react-native-appsflyer: You may set variable `$RNAppsFlyerStrictMode=true` in Podfile to use strict mode for kids apps.
```
So far so good. Then I set the config explicitly in my Podfile with `$RNAppsFlyerStrictMode=false`.
I run `pod install` again, and get the following note:
```
react-native-appsflyer: Using AppsFlyerFramework/Strict mode
```

## What did you expect to happen?

I set the config `$RNAppsFlyerStrictMode` to `false`. It uses the regular mode and the note disappears.

## What happened instead?

It uses strict mode.

**Comment by amit-kremer93** [comment]
Hi @reichhartd and thank you for opening this issue! you are right, the plugin uses strict mode even when you set `$RNAppsFlyerStrictMode=false`. so in order to fix it please remove this line from your podfile

**Comment by reichhartd** [comment]
Yes, that’s how we use it at the moment. But that's, in my opinion, not the expected behaviour and not developer-friendly. When I explicitly set a config value, I expect the framework to behave accordingly, not always set the value to true.

**Comment by amit-kremer93** [comment]
You are right and it will be fixed in the next release
