### ISSUE TITLE
Universal links (Deep linking) not working on real device but works on simulator IOS

### ISSUE THREAD

**Issue by hramadhaan** [AppsFlyerSDK/appsflyer-react-native-plugin#341]
**Plugin Version**

"react-native": "0.62.2"
"react-native-appsflyer": "^6.4.0"

**Comment by amit-kremer93** [comment]
Hi @haveamission 
Thank you for reaching out to us.

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
