### ISSUE TITLE
Defered deeplinking not working on android and iOS.

### ISSUE THREAD

**Issue by vaisakhzepto** [AppsFlyerSDK/appsflyer-react-native-plugin#343]
# Report

## Plugin Version

ℹ 6.4.0

## On what Platform are you having the issue?

ℹ ios and android

## What did you do?

ℹ Trying to implement deferred link flow as per documentation

## What did you expect to happen?

ℹ Trying to implement deffer ed link flow. App should redirect new installed users via deep link to certain page .

## What happened instead?

ℹ Redirection is not happening. In iOS when we click on link and run via xcode, I can see data coming in onInstallConversionData, but when released to testflight, it is not working. In android its not happening at all, both in debug as well as release builds. Normal deeplinking after installation is working as expected.

**Comment by ge-af** [comment]
Hi @vaisakhzepto ,
Thank you for reaching out to us!

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
