### ISSUE TITLE
How to set pid attribute when using generateInviteLink?

### ISSUE THREAD

**Issue by lengkhang** [AppsFlyerSDK/appsflyer-react-native-plugin#347]
Setting the `pid` value works on iOS with this configuration but not on Android:
```
appsFlyerSdk.generateInviteLink({
	channel: params.channel,
	customerID: params.customerID,
	userParams: {
		pid: 'my_pid_value'
	}
})
```

Does anyone know how to set the `pid` value for Android?

**Comment by amit-kremer93** [comment]
when you creates the onelink and open the app with it, what is the data that you get in `onDeepLink` or in `onAppOpenAttribution`? it doesn't include `"media_source": "my_pid_value"`?
