### ISSUE TITLE
Missing `data` typings, filled with `any`

### ISSUE THREAD

**Issue by jkadamczyk** [AppsFlyerSDK/appsflyer-react-native-plugin#355]
# Report

## Plugin Version

6.4.40

## On what Platform are you having the issue?

ios and android

## What did you do?

Everything works correctly I just think you should add some documentation that is missing

## What did you expect to happen?

I expect to be able to see an interface for the data `onDeepLink` callback receives

## What happened instead?

There's no documentation or typescript types. It is a black box.

## Please provide any other relevant information.

I think the documentation for react native plugin needs some attention. It is extremely hard to integrate the SDK. The docs seem to be outdated and not maintained actively. A lot of typing are missing and there's not even a slight hint of how to retrieve a deeplink value out of the callback parameter. Either Typescript declarations or just updated docs will help a lot in this case.

**Comment by amit-kremer93** [comment]
Hi @jkadamczyk and thank you! we have similar feature request [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/218) and we are working on it
