### ISSUE TITLE
SDK stripping important arguments from Universal Links

### ISSUE THREAD

**Issue by djMax** [AppsFlyerSDK/appsflyer-react-native-plugin#363]
# Report

## Plugin Version

6.4.40

## On what Platform are you having the issue?

ios

## What did you do?

When opening a deep link of the following form:

https://something.onelink.me/2n60?pid=super-link&af_dp=myapp%3A%2F%2Fsuper-link%2F34u048yt2d95whqu8ud0r&af_web_dp=https%3A%2F%2Fiam.somebody.com%2Fgo%2F34u48yt2d95whqu8ud0r&gb_f=super&gb_e=max%2Bgb%gmail.com&gb_m=&gb_d=MyAppName&gb_r=someguid

## What did you expect to happen?

Pass through all the information about the deep link.

## What happened instead?

The deep link data that I receive in the event is missing a number of those arguments, namely af_dp, af_web_dp (understandable), the path (2n60)... Why?

## Please provide any other relevant information.

Part of this may be because of the way our deep links are structured (we reuse that "2n60" for basically all our deep links and put the rest of the data in arguments, but that doesn't really seem wrong.

**Comment by amit-kremer93** [comment]
hi @djMax and thank you for opening this issue.
Do you work with UDL (onDeepLinking) or onAppOpenAttribution?

**Comment by djMax** [comment]
I'm using onDeepLinking, should I be using onAppOpenAttribution?

**Comment by djMax** [comment]
As an add on, when using protocol links, such as `myapp://something/somewhere`, AppsFlyer onDeepLink still fires, but has basically no useful data in it. I don't understand the reasoning...
