### ISSUE TITLE
is_first_launch comes as undefined regardless of "true" | "false" type

### ISSUE THREAD

**Issue by pistonsky** [AppsFlyerSDK/appsflyer-react-native-plugin#365]
# Report

## Plugin Version
`6.5.20`

## On what Platform are you having the issue?

android

## What did you do?

```
import appsFlyer from 'react-native-appsflyer';
import AsyncStorage from '@react-native-community/async-storage';

import Sentry from 'utils/sentry';

export const onInstallConversionData = () =>
  appsFlyer.onInstallConversionData(async (res) => {
    try {
      if (JSON.parse(res.data.is_first_launch) === true) {
        // something else here, not important
      }
    } catch (err) {
      Sentry.logError({
        filename: 'appsflyer.ts',
        fingerprint: ['onInstallConversionData', 'is_first_launch'],
        message: 'res.data.is_first_launch is not a valid JSON',
        data: res.data.is_first_launch,
        err,
      });
    }
  });

```

## What did you expect to happen?

I expected to see nothing in Sentry.

## What happened instead?

In Sentry I saw 
>JSON Parse error: Unexpected identifier "undefined"

## Please provide any other relevant information.

The type of that `is_first_launch` key is defined as `'true' | 'false'`. Even if it comes boolean, the catch clause would not be executed, but it was. I'm wondering why there is `undefined` and if I should replace that check with
```
if (res.data.is_first_launch === true || res.data.is_first_launch === 'true') ...
```

Thanks!

**Comment by amit-kremer93** [comment]
@pistonsky you can see an example in our sample app [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/demos/appsflyer-react-native-app/components/HomeScreen.js#L139-L142)

**Comment by pistonsky** [comment]
Thanks! Probably types are wrong then. @amit-kremer93

**Comment by MoritzCooks** [comment]
The typing for `is_first_launch` is still not correct. 
Can you please update them in your `ConversionData` type if `is_first_launch` can be undefined?
