### ISSUE TITLE
Pods conflicting names in Strict mode

### ISSUE THREAD

**Issue by davidnum** [AppsFlyerSDK/appsflyer-react-native-plugin#366]
# Report
When using `$RNAppsFlyerStrictMode = true`, `pod install` failed with following error:

`target has frameworks with conflicting names: appsflyerlib.xcframework`

## Plugin Version

6.5.20

## On what Platform are you having the issue?

ios

## What did you do?

Run `pod install`

## What did you expect to happen?

Successfully installing pods

## What happened instead?

Error: `target has frameworks with conflicting names: appsflyerlib.xcframework`

**Comment by amit-kremer93** [comment]
@davidnum try to remove and install AppsFlyer plugin again. did you modify your PodFile beside adding `$RNAppsFlyerStrictMode = true`?

**Comment by davidnum** [comment]
Hello, already solved by deleting `pod 'AppsFlyerFramework'` from  `Podfile`
