### ISSUE TITLE
A binary contains strings that reveal paths in the development environment

### ISSUE THREAD

**Issue by pabloearg** [AppsFlyerSDK/appsflyer-react-native-plugin#371]
# Report

## Plugin Version

6.4.40

## On what Platform are you having the issue?

iOS

## What did you do?

 Run `npm i react-native-appsflyer`
 add `  $RNAppsFlyerStrictMode=true` to Podfile
 Run `pod install`

## What did you expect to happen?

Lib should not have any references to local paths

## What happened instead?

 Some binaries contain strings that reveal paths in the development environment:

## Please provide any other relevant information.
 
an example:
file => ios/Pods/AppsFlyerFramework/Strict/AppsFlyerLib.xcframework/ios-arm64_armv7/AppsFlyerLib.framework/AppsFlyerLib

reference: /Users/maximshoustin/AppsFlyer/projects/BUILD_MACHINE/build-machine-sdk/workspace/ios_sdk_framework_test/AppsFlyerLib/AppsFlyerLib/Keychain/AppsFlyerKeychainWrapper.m

**Comment by pabloearg** [comment]
were you able to verify it?

**Comment by amit-kremer93** [comment]
Hey @pabloearg , thank you for opening this issue. This is related to our iOS native sdk and we are working on improving the build process which related to this issue.
