### ISSUE TITLE
OnDeeplink is not triggered when app is launched from background

### ISSUE THREAD

**Issue by vjmangu** [AppsFlyerSDK/appsflyer-react-native-plugin#372]
# Report
OnDeeplink is not triggered when the app is launched from the background, using one link URLs but if the app is killed and apps open from the URL then onDeeplink is invoked. 

## Plugin Version

6.4.4

## On what Platform are you having the issue?

ios and android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?
when we click on onelink URLs even while the app is running in the background, onDeeplink callback should be called.

## What happened instead?

when we click on onelink URLs even while the app is running in the background, onDeeplink callback should is not called.

## Please provide any other relevant information.

we initialize sdk before our main login component as part of app launch. 

**Code we have** 

appsFlyer.onDeepLink((res) => {
    Logger.log('onDeepLinking: ' + JSON.stringify(res));
    if (res?.data?.deep_link_value) {
        //deeplink to the screen
    }
});

appsFlyerInitValues = {
    //sset onDeeplinklistener: true
}

appsFlyer.initSdk(
        appsFlyerInitValues,
        async (result) => {

        }

        Logger.log('AppsFlyer initialized');
    },
    (error) => {
        Logger.error(error);
    }
);

**Comment by bilicio** [comment]
hi! it happens to me.. how do you fix it?

**Comment by pierrezimmermannbam** [comment]
We're having the same issue, how can this be resolved ?

**Comment by JMikeJ** [comment]
We've encountered the same issue. The onDeeplink is triggered when the app is closed but when the app is on background it doesn't. Have you resolved the issue @vjmangu

**Comment by rafinhaa** [comment]
Hi, I have the same problem
Does anyone have a solution?

version: "6.4.0"

**Comment by bilicio** [comment]
My workaround was change android:launchMode to standard on manifest.

**Comment by ahtokca** [comment]
same here 6.8.2

**Comment by soorajkumarck** [comment]
Any solution for this issue

**Comment by iway1** [comment]
why was this closed? obviously still an issue

**Comment by iway1** [comment]
I believe I found the issue. According to their *android* docs https://dev.appsflyer.com/hc/docs/dl_android_unified_deep_linking#implementation:~:text=📘-,Note,-onDeepLinking%20is%20not

`setIntent` must be called in `onNewIntent` in the MainActivity file of the java / kotlin code. It is not called by default. 

This is obviously not possible with typical expo workflows, so AppsFlyer should update their config plugin to do it so that they have actual Expo support (right now they don't really support expo since this critical functionality is missing). Going to try to write a config plugin for this and see if it works, if it does I'll open a PR

**Comment by iway1** [comment]
I have confirmed my above suspicion, Expo support is currently incomplete b/c the config plugin is missing some required native code changes on Android, which leads to the problem @sonnguyprophet has described.

If you're not using Expo you can just override the onNewIntent function in the main activity as in the above docs. If you are using expo you can use this config plugin

```js
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");
const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

async function readFileAsync(path) {
  return fs.promises.readFile(path, "utf8");
}

async function saveFileAsync(path, content) {
  return fs.promises.writeFile(path, content, "utf8");
}

function getPath(root, bundleId) {
  return path.join(
    root,
    "app/src/main/java",
    ...bundleId.split("."),
    "MainActivity.kt"
  );
}

const withOnNewIntent = (config) => {
  return withDangerousMod(config, [
    "android",
    async (mod) => {
      const path = getPath(
        mod.modRequest.platformProjectRoot,
        mod.android.package
      );
      const file = await readFileAsync(path);
      const updatedWithIntentOverride = mergeContents({
        src: file,
        newSrc: `  override fun onNewIntent(intent: Intent) {
    super.onNewIntent(intent)
    setIntent(intent)
  }`,
        // inserts it after the first function in the activity class
        anchor: /\}/,
        offset: 2,
        tag: "appsflyer-on-new-intent",
        comment: "//",
      });
      // import android.content.Intent;
      const updatedWithImport = mergeContents({
        src: updatedWithIntentOverride.contents,
        newSrc: `import android.content.Intent`,
        // import as second line in the file
        anchor: /package/,
        offset: 1,
        tag: "appsflyer-import-intent",
        comment: "//",
      });
      await saveFileAsync(path, updatedWithImport.contents);
      return mod;
    },
  ]);
};

module.exports = function withAppsFlyerAndroid(config) {
  config = withOnNewIntent(config);
  return config;
};
```

I opened a PR with this config plugin but IDK if they're going to merge it

**Comment by sprutner** [comment]
Thanks @iway1 I have the exact same issues as you. I will try out your plugin.
