### ISSUE TITLE
How to reset userIdentifier on logout

### ISSUE THREAD

**Issue by gabrielfvf7** [AppsFlyerSDK/appsflyer-react-native-plugin#377]
Hi, this is not exactly an issue, but reading the docs and the API, there's a method `setCustomerUserId` to set the user Id, but when this user do the logout of my application, how do i reset this id?

**Comment by amit-kremer93** [comment]
Hi @gabrielfvf7 , you can just use `setCustomerUserId` again and it will overwrite it. For more info please contact our support team: support@appsflyer.com

**Comment by rolandvar** [comment]
Is it not possible to set it null?

If I try to do setCustomerUserId(null) I get a typescript error that requires a string as a parameter. We are currently using an empty string, is this the right approach ?
