### ISSUE TITLE
[IOS][CHROME] deferred deeplinking not works in Chrome browser

### ISSUE THREAD

**Issue by kasterlod** [AppsFlyerSDK/appsflyer-react-native-plugin#384]
# Report

## Plugin Version

tested on 3 latest versions of the library

## On what Platform are you having the issue?

ios 15.4.1

## What did you do?

nothing special, deferred deeplinking flow works as expected on 14.X - working with all browsers

deferred deeplinking flow does not working at 15.X

## What did you expect to happen?

Deferred deeplinking should works on all browsers

## What happened instead?

Deferred deeplinking works only with Safari browser, not working with Chrome browser.

## Please provide any other relevant information.

When link is opened by chrome, then I receive only
{ status: 'failure',
  deepLinkStatus: 'NOT_FOUND',
  data: 'deep link not found',
  type: 'onDeepLinking',
  isDeferred: false }

when using Safari - then everything is ok. I have no idea where to look at, I'll appreciate any ideas 🙏

**Comment by msvargas** [comment]
Hi @kasterlod I'm facing the same problem but it doesn't work on both platforms I always get NOT_FOUND, I really appreciate any help regarding to deferred deeplinking for example if you test this on simulator, OS version, SDK version, if this works with the example app, whatever please, thank you in advance!

**Comment by kasterlod** [comment]
here is how I'm testing it on a real IOS device:

1. click the link in Gmail (real gmail app, real email, real link)
2. browser select prompt appear
3. link opened & redirect to app store
4. I install the app by Xcode
5. app opens -> **I can see all results when select Safari in step 2, and I can't see any results when select any other**

**Comment by sriganesh-nagaraj** [comment]
@kasterlod @msvargas I'm facing the same issue. Were you able to workaround this?

**Comment by msvargas** [comment]
@sriganesh-nagaraj  Yes, but sorry I don't remember what I did, maybe you can use the latest Appsflyer SDK version

**Comment by frzkn** [comment]
I was wondering if you guys managed to fix this problem?

**Comment by thiennhank9** [comment]
Still encounter this issue with v6.13.1. Is there any workaround guys? Many appreciations.

**Comment by Georg7** [comment]
Anyone any success?
