### ISSUE TITLE
 Invariant Violation: Native module cannot be null

### ISSUE THREAD

**Issue by asdf1899** [AppsFlyerSDK/appsflyer-react-native-plugin#389]
# Report

## Plugin Version

via `6.6.1`

## On what Platform are you having the issue?

ios

## What did you do?

1. `yarn add react-native-appsflyer`
2. `cd ios && pod install`

## What did you expect to happen?

Initialize the sdk

## What happened instead?

Gives the build error Native Module cannot be null

## Please provide any other relevant information.

```
appsFlyer.initSdk(
  {
    devKey: '***********',
    isDebug: false,
    appId: '*******',
  },
  (result) => {
    console.log(result);
  },
  (error) => {
    console.error(error);
  }
);
```

Using the old api (5.1.2) it works fine

**Comment by jorgeruvalcaba** [comment]
I have the same issue

**Comment by amit-kremer93** [comment]
try to clean your project and remove derived data. then build again

**Comment by amit-kremer93** [comment]
@jorgeruvalcaba Please take a look here: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/391
