### ISSUE TITLE
In-App events Status code failure 404

### ISSUE THREAD

**Issue by jorgeruvalcaba** [AppsFlyerSDK/appsflyer-react-native-plugin#390]
# Report

## Plugin Version

via `6.6.0`

## On what Platform are you having the issue?

ios and android

## What did you do?

1. Init sdk and validate it worked having the `Success` string log.
2. Included the following In-App event:
```
appsFlyer.logEvent(
    'af_login',
    {},
    (success) => {
      console.log({ success })
    },
    (error) => {
      console.log({ error })
    },
  )
```

## What did you expect to happen?

Event to be logged (`console.log({ success})`)

## What happened instead?

Got this error:
```
{
  "error": "Status code failure 404",
}
```

## Please provide any other relevant information.

I'm using Expo v44 with EAS Build.

**Comment by pratik-adh** [comment]
@jorgeruvalcaba, Did you find the solution to your issue?
If yes, can you please share?

**Comment by thaycacac** [comment]
Any update for this issue?

**Comment by singhagam1** [comment]
@amit-kremer93 
Can you let us know if this is fixed or any work around ? I still see this in 6.10.3 version.
