### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by ddinchev** [AppsFlyerSDK/appsflyer-react-native-plugin#391]
# Report

## Plugin Version

6.6.0

## On what Platform are you having the issue?

expo managed workflow, trying to run on ios simulator

## What did you do?

Followed the [expo managed workflow instructions](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/Expo.md). Created minimal example based on your own expo demo app I found over [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/tree/master/demos/appsflyer-expo-app):
https://github.com/ddinchev/expo-managed-appsflyer

In my repo, the changes are all contained in a single commit (after generating expo managed workflow app with expo cli):
https://github.com/ddinchev/expo-managed-appsflyer/commit/fb0cf206466ae5081094684db85225f405a4760a

Checkout my example repo and do:

```
npm install
npm start
```

I tried to run the app in iOS emulator (press i).

## What did you expect to happen?

The app to run.

## What happened instead?

```

Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:203:6 in guardedLoadModule
at http://192.168.31.141:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:121008:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError

```

## Please provide any other relevant information.

Again, my minimal example should make it easy to reproduce, at least on a Mac:
https://github.com/ddinchev/expo-managed-appsflyer

**Comment by amit-kremer93** [comment]
@ddinchev it happens because you are trying to run your app using Expo Go app which is not compatible with custom native code build. you need to build your own custom build with `expo run:ios` and then it will work

**Comment by ddinchev** [comment]
Thank you. It would be nice if these details are clearly stated in the docs. As well as conditionally import appsflyer sdk so that you can keep using `expo go` for development and quick testing, without appsflyer attribution & tracking.

**Comment by russriser** [comment]
@ddinchev did you get this working? 

My company is considering switching attribution partners and it'd be great to have some assurance this works before committing to the switch. But so far there's just another issue (that remains open) that says they added this config plugin=

**Comment by ddinchev** [comment]
It works fine. If you want to use Expo Go for development, you can do a conditional require as explained here:
https://docs.expo.dev/bare/using-expo-client/

You can write a dummy dev implementation of the appsflyer API for development (expo go).

**Comment by bportman** [comment]
This issue occurs for me even though I am using a "development build" - not Expo Go - I ran `npx expo run:ios` to launch the app and I get the exact same error.  I am on react-native-appsflyer 6.15.1.

**Comment by adgeg** [comment]
@bportman After many tests, I found that the only way to solve that issue was to add that line to the `app.config.ts`:
```
  [
   'expo-build-properties',
   {
     ios: {
       forceStaticLinking: ['RNAppsFlyer'],
       useFrameworks: 'static',
     },
   },
 ]
```

I'm using react-native-appsflyer version 6.18.0.
