### ISSUE TITLE
how to get url query data from onInstallConversionDataCanceller function?

### ISSUE THREAD

**Issue by taehyun-kim-tenuto** [AppsFlyerSDK/appsflyer-react-native-plugin#396]
# Report

## Plugin Version

ℹ Please replace these two lines with the plugin version.
e.g. via `4.1.1`

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
e.g. ios and android

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

if i make my onelink url something like https://abc.me/ver=1&roomId='taehyunzzang'
onDeeplink function can get roomId data
but onInstallConversionDataCanceller cannot get roomId data
i want to let my not-installed-customer install the app and navigate to certain screen
what should i do

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be logged

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. No uninstalls on my dashboard

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by taehyun-kim-tenuto** [comment]
appsflyer.onDeeplink callback can get query params
but appsflyer.onInstallConversionDataCanceller callback can't
all i want is onInstallConversionDataCanceller callback can get query params like onDeeplink callback does

**Comment by amit-kremer93** [comment]
in order to get parameters in onDeepLink callback you should use the `deep_link_value` and `af_sub(1-10)`. you can read more [here](https://dev.appsflyer.com/hc/docs/unified-deep-linking-udl)
