### ISSUE TITLE
On some iOS devices (example: iphone 12 pro max) when app is installed via deep link, the deep_link_value is undefined

### ISSUE THREAD

**Issue by Ggayane** [AppsFlyerSDK/appsflyer-react-native-plugin#398]
# Report
On some iOS devices (example: iphone 12 pro max) when app is installed via link, deep `deep_link_value` inside `onInstallConversionData` is undefined.

## Plugin Version
6.6.1

## On what Platform are you having the issue?
iOS

These are the lines which I've added in my `AppDelegate.m` file:
```c#
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [[AppsFlyerAttribution shared] handleOpenUrl:url options:options];
  [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:app openURL:url options:options];
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  return NO;
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  [[AppsFlyerAttribution shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
  [[RNFBDynamicLinksAppDelegateInterceptor sharedInstance] application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}
```

Also I see this in logs:
`[AppsFlyerSDK] [com.appsflyer.serial] [DDL] Calling didResolveDeepLink with: {"af_sub4":null,"click_http_referrer":null,"af_sub1":null,"click_event":{"request_ip_version":"IP_V4","match_message":"No pre-install link matched for this device."},"af_sub3":null,"deep_link_value":null,"campaign":null,"match_type":null,"af_sub5":null,"media_source":null,"campaign_id":null,"af_sub2":null}`

**Comment by pjc0247** [comment]
same here

**Comment by Ggayane** [comment]
> same here

@pjc0247 you need to write their tech support, they're not communicating here (don't understand why).
