### ISSUE TITLE
How to get additional params in deferred deep link

### ISSUE THREAD

**Issue by gabrielfvf7** [AppsFlyerSDK/appsflyer-react-native-plugin#399]
# Report

## Plugin Version

`6.4.0`

## On what Platform are you having the issue?

iOS and Android

## What did you do?

Opened a deepLink with and without the app installed

## What did you expect to happen?

The same behavior for both case, where when i open the deeplink, the app receives the same data

## What happened instead?

In the deferred deep link, it's receives unexpected data

## Please provide any other relevant information.

When i open the app using the deeplink and the app is already installed, the object for deeplink is:
`{"status":"success","deepLinkStatus":"FOUND","type":"onDeepLinking","data":{"deeplink_path":"partner-online","media_source":"dev","campaign":"testeonline","id":"2","deep_link_value":"partner-online","is_deferred":false},"isDeferred":false}`
Where i use the values inside `data` to redirect the user to a screen.
But when i open the deeplink in the deferred way, where the app it's not yet installed, the object for deeplink i receive when the app opens is:
`{"status":"success","deepLinkStatus":"FOUND","type":"onDeepLinking","data":{"campaign_id":"","af_sub3":"","match_type":"probabilistic","af_sub1":"","deep_link_value":"partner-online","campaign":"","af_sub4":"","timestamp":"2022-07-05T20:53:04.725","click_http_referrer":"","af_sub5":"","media_source":"","af_sub2":"","is_deferred":true},"isDeferred":true}`
Where the additional params that i set in AppsFlyer are missing. What i need to do to get?

There already other issues like [this](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/396#issuecomment-1167073245) with the same problem

**Comment by gabrielfvf7** [comment]
> 👋 Hi @gabrielfvf7 and Thank you for reaching out to us. In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com). When submitting the ticket, please specify:
> 
> * ✅ your AppsFlyer sign-up (account) email
> * ✅ app ID
> * ✅ production steps
> * ✅ logs
> * ✅ code snippets
> * ✅ and any additional relevant information.

I already did that

**Comment by filippobarcellos** [comment]
@gabrielfvf7 Did you manage to solve it? I have the same problem.

**Comment by gabrielfvf7** [comment]
Hi @filippobarcellos , i have sent an email to AppsFlyer support and they responded saying that this works this way, for security reasons in defered deep link the extra params wont come, as said [here](https://dev.appsflyer.com/hc/docs/unified-deep-linking-udl). So in defered is required to use `deep_link_value`
