### ISSUE TITLE
Invalid react-native configuration

### ISSUE THREAD

**Issue by onelittlebird** [AppsFlyerSDK/appsflyer-react-native-plugin#403]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-appsflyer@6.6.1` for the project I'm working on.

This is related to when using react-native > 0.68. Metro complains about the react configuration not being valid.

```warn Package react-native-appsflyer contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-appsflyer/react-native.config.js b/node_modules/react-native-appsflyer/react-native.config.js
index dfbe81b..20187c2 100644
--- a/node_modules/react-native-appsflyer/react-native.config.js
+++ b/node_modules/react-native-appsflyer/react-native.config.js
@@ -3,7 +3,7 @@ const path = require('path');
 module.exports = {
   dependency: {
     platforms: {
-      ios: { podspecPath: path.join(__dirname, 'react-native-appsflyer.podspec') },
+      ios: {},
       android: {
         packageImportPath: 'import com.appsflyer.reactnative.RNAppsFlyerPackage;',
         packageInstance: 'new RNAppsFlyerPackage()',
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by amit-kremer93** [comment]
Hi @onelittlebird and thank you for opening this issue. There is another issue related to what you mentioned [here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/395) and we are working on it. So i'm closing this one and we will keep you updated there.
