### ISSUE TITLE
Error: No dev key on Android

### ISSUE THREAD

**Issue by eb-real** [AppsFlyerSDK/appsflyer-react-native-plugin#409]
# Report

## Plugin Version
- 6.6.0

## On what Platform are you having the issue?
- Android

## What did you do?
- Initializing SDK and running `appsFlyer.logEvent`

## What happened instead?
- SDK initializes successfully as `(result) => {console.log(result)}` displays `Success` but seeing `Error: No dev key` in logs.

## Please provide any other relevant information.
- We are only initializing the SDK when our app is pointed to our `prod` environment and the error appears when running `appsFlyer.logEvent()`.
- We also see attribution metrics in AppsFlyer dashboard so everything seems to be working even with the `No dev key` surfacing.

**Comment by StampixSMO** [comment]
We are also noticing this issue all of a sudden

**Comment by amit-kremer93** [comment]
The calls to `initSdk` and `logEvent` are asynchronous so if you call logEvent right after init it can happen. try to call logEvent inside the initSdk callback or to delay the call to logEvent in order to isolate the problem.
