### ISSUE TITLE
Could not invoke RNAppsFlyer.initSdkWithPromise

### ISSUE THREAD

**Issue by MariusCatanoiu** [AppsFlyerSDK/appsflyer-react-native-plugin#414]
I have this error

```
Could not invoke RNAppsFlyer.initSdkWithPromise

java.lang.NoSuchMethodError · No direct method <init>(Ljava/lang/Runnable;Lcom/appsflyer/internal/AFc1xSDK;)V in class Lcom/appsflyer/internal/AFd1jSDK; or its super classes (declaration of 'com.appsflyer.internal.AFd1jSDK' appears in base.apk)
```

platform: android
react-native-appsflyer:  6.8.0
react-native: 0.69.4
device: moto g(6) play (at this moment I get this error on bugsnag, and for this device. I will add more If I get this on other  device's)

**Comment by LupusX5** [comment]
I have the same problem.

**Comment by amit-kremer93** [comment]
@MariusCatanoiu @LupusX5 do you get this error on a specific device? few devices?
