### ISSUE TITLE
How to test deferred deep links

### ISSUE THREAD

**Issue by gabrielfvf7** [AppsFlyerSDK/appsflyer-react-native-plugin#415]
# Report

## Plugin Version

`6.4.0`

## On what Platform are you having the issue?

iOS and Android

## What did you do?

Test these 2 deferred deep links:
 https://meliuz.onelink.me/2657008059/testeindique
 https://meliuz.onelink.me/2657008059/testecp1

## What did you expect to happen?

When opening a deferred deep links, it open without error and the data get on the onDeepLink callback

## What happened instead?

When the deferred deep link is opened, the onDeepLink callback returns `{"status":"failure","deepLinkStatus":"NOT_FOUND","data":"deep link not found","type":"onDeepLinking","isDeferred":false}` instead of the correct data. The links tested works if the app is already installed

**Comment by dan-betmate** [comment]
Hey @gabrielfvf7 did you ever get a response or a solution for this? I can get deeplinking to work with an AppsFlyer link but not deferred deeplinking.

**Comment by iway1** [comment]
@amit-kremer93 why was this closed? same problem still exists

**Comment by sleekLancelot** [comment]
> [@amit-kremer93](https://github.com/amit-kremer93) why was this closed? same problem still exists

Hi, did you eventually find out how to test this outside app store?
