### ISSUE TITLE
Incorrect is_first_launch value passed to React Native 

### ISSUE THREAD

**Issue by hsandhu** [AppsFlyerSDK/appsflyer-react-native-plugin#423]
# Report

Incorrect value for `is_first_launch` passed from the iOS SDK to the React Native SDK. For example, a value of 1 or true is received by the iOS SDK in the logs, yet the React Native SDK reports false. 

`"is_first_launch" = 1;` in Xcode (iOS)

`"is_first_launch" = false;` in React Native JS

## Plugin Version
`6.8.2`

## On what Platform are you having the issue?

iOS

## What did you do?

Installed the SDK and built the app using QR code deep link.

## What did you expect to happen?

Correct value for `is_first_launch`

## What happened instead?

Incorrect value for `is_first_launch` is observed with the RN SDK.

**Comment by hsandhu** [comment]
@amit-kremer93 any update?

**Comment by amit-kremer93** [comment]
@hsandhu i couldn't reproduce this issue. I suggest that you'll open a ticket to our support team so we can further investigate your problem.
