### ISSUE TITLE
Unable to resolve host "inapps.appsflyer.com"

### ISSUE THREAD

**Issue by markushogberg** [AppsFlyerSDK/appsflyer-react-native-plugin#426]
# Report

## Plugin Version

`6.8.2`

## On what Platform are you having the issue?

Android and iOS

## What did you do?

Upgraded from `6.8.0` to `6.8.2`

## What did you expect to happen?

Everything should continue to work without errors

## What happened instead?

Start receiving errors in sentry after releasing the app. 

There are two types of error occurring on Android:

1. `Unable to resolve host "inapps.appsflyer.com": No address associated with hostname`
2. `Error: timeout`

And on iOS this error occurs:
1. `com.appsflyer.sdk.network`

## Please provide any other relevant information.

The issue started when we upgraded the plugin to version `6.8.2`
Example stack trace:
```
Crashed in non-app: node_modules/react-native/Libraries/BatchedBridge/NativeModules.js in promiseMethodWrapper
native in call
Called from: node_modules/@segment/analytics-react-native/src/plugin.ts in execute$
native in call
Called from: node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js in tryCatch
native in call
Called from: node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js in tryCatch
native in apply
Called from: node_modules/react-native/Libraries/Core/Timers/JSTimers.js in anonymous
```

**Comment by amit-kremer93** [comment]
@professorkolik @markushogberg this issue is related to internet connection. Do you see this only on logEvent call? what about initSdk?

**Comment by markushogberg** [comment]
@amit-kremer93 Looks like all (or at least most of) the errors happens on the logEvent call.

**Comment by professorkolik** [comment]
@amit-kremer93 seems to be gone on v6.9.1, still analyzing

**Comment by qasimgit** [comment]
same error on IOS, when calling logevent V6.9.2 RN version 0.67.3
`Error: com.appsflyer.sdk.network`

@GM-appsflyer

**Comment by qasimgit** [comment]
fixed this issue by adding the correct devKey and appId on the init of sdk.

```
appsFlyer.initSdk(
  {
    devKey: 'correct-dev-key',             ----> here
    isDebug: false,
    appId: 'your-app-id',                       ----> here
    onInstallConversionDataListener: true, //Optional
    onDeepLinkListener: true, //Optional
    timeToWaitForATTUserAuthorization: 10, //for iOS 14.5
  },
  (result) => {
    console.log('result from appsflyer initialization', result);
  },
  (error) => {
    console.error('error in appsflyer initialization', error);
  },
);
``` 


@markushogberg @professorkolik @amit-kremer93

**Comment by amit-kremer93** [comment]
@markushogberg @professorkolik please confirm that you initialized the sdk properly before sending an event

**Comment by markushogberg** [comment]
@amit-kremer93 When I try it myself locally I can confirm that it is initialized with the correct values before sending any events.

**Comment by professorkolik** [comment]
@amit-kremer93 sdk was initialized properly, only thing that helped is to update to v6.9.1 from v6.4.40

**Comment by markushogberg** [comment]
We are currently on v6.8.2. In the next release of our app we will have v6.9.2. I'll keep you posted if that makes the issue go away.

**Comment by markushogberg** [comment]
We are also still seeing these errors in v6.9.4.

**Comment by bishalfan** [comment]
We are also facing this issue after upgrading RN to 0.71

**Comment by dnvarun** [comment]
Any update here? We are also seeing this a lot

**Comment by amit-kremer93** [comment]
This issue can be related to a specific device or network and not to the sdk. I recommend you to contact our support team at support@appsflyer.com with all the relevant information so they can help you
