### ISSUE TITLE
Link not open view on iOS when app is in foreground

### ISSUE THREAD

**Issue by Darex1991** [AppsFlyerSDK/appsflyer-react-native-plugin#429]
# Report

## Plugin Version
checked `6.4.40` and `6.8.0`

## On what Platform are you having the issue?
iOS

## What did you do?

I just click the universal link.

## What did you expect to happen?
Open the correct view.

## What happened instead?

Nothing (just display app), `onDeepLink` was executed with correct params.

<img width="254" alt="Screenshot 2022-10-07 at 10 29 23" src="https://user-images.githubusercontent.com/5881611/194572363-843fd3ca-18b9-497a-907f-9d1dea2b3cf9.png">

## Please provide any other relevant information.
On Android, it is working fine. When the app is killed link correctly starts the app with an opened view.

---- 
Flow works fine when instead of using 
```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler {
    [[AppsFlyerAttribution shared] continueUserActivity:userActivity restorationHandler:restorationHandler];
    return YES;
}
```
from [documentation](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/DeepLink.md#-ios-deeplink-setup)

I will use setup from RN Navigation [documentation](https://reactnavigation.org/docs/5.x/deep-linking/#ios)

```
// Add this inside `@implementation AppDelegate` above `@end`:
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}
```

so there is problem with `[[AppsFlyerAttribution shared] `

**Comment by amit-kremer93** [comment]
@Darex1991 are you trying to open a certain view after clicking on a link? `AppsFlyerAttribution shared` is responsible on triggering the `onDeepLink` method on the javascript side and not on redirecting to a specific screen or any other action. you need to do it on your own in the `onDeepLink` method

**Comment by Darex1991** [comment]
Yeah, now I know :) I talked with support about that and after a few days of chat I've been informed about that. Thanks
