### ISSUE TITLE
Expo - App install

### ISSUE THREAD

**Issue by flo-butterfly** [AppsFlyerSDK/appsflyer-react-native-plugin#433]
# Report

## Plugin Version

6.9.1

## On what Platform are you having the issue?

iOS

## What did you do?

Called initSdk

## What did you expect to happen?

When running non-organic install test from AppsFlyer dashboard, following the instructions

## What happened instead?

The install never shown up in the dashboard while the app didn't show any errors calling the function

**Comment by gabriel-moresco** [comment]
hello, how did you solve this?
