### ISSUE TITLE
can't archive in IOS

### ISSUE THREAD

**Issue by LamQuyet** [AppsFlyerSDK/appsflyer-react-native-plugin#438]
my app run in simulator and IOS/android real devices very well but when I want archive Xcode send for me 'Use of undeclared identifier 'AppsFlyerAttribution'.
I don't know why. I'm trying fix it but I can't. can you tell me how to fix it?
![Screen Shot 2022-10-26 at 16 22 34](https://user-images.githubusercontent.com/83718392/197990379-e465549c-e7b6-41c2-be84-c81ca3685192.png)

**Comment by amit-kremer93** [comment]
try to clean project and derived data and then archive again

**Comment by Eldenn** [comment]
@LamQuyet did you resolve this error ?

**Comment by LouisKraemer** [comment]
I have the same issue on my build, tried cleaning everything but still having this issue.

Followed the documentation here https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/DeepLink.md

Only difference is that I use the .mm format instead of .m

**Comment by amit-kremer93** [comment]
If you are just using `AppsFlyerAttribution` in your `AppDelegate` file, you can try and replace the import of RNAppsFlyer with AppsFlyerAttribution like this:
`#import <RNAppsFlyer.h>` -> `#import "AppsFlyerAttribution.h"`
