### ISSUE TITLE
Deeplink is not working as expected on android

### ISSUE THREAD

**Issue by sukesh-pfx** [AppsFlyerSDK/appsflyer-react-native-plugin#441]
Plugin Version
6.6.0

On what Platform are you having the issue?
Android

What did you do?
Opened a Deeplink with the app installed

What did you expect to happen?
Need to open a screen based on the deep link 

What happened instead?
it receives unexpected data

Please provide any other relevant information.

_{"data": "NETWORK", "deepLinkStatus": "ERROR", "isDeferred": false, "status": "failure", "type": "onDeepLinking"}_

![image](https://user-images.githubusercontent.com/64000239/205597733-5b6d44df-0d36-4c6c-88b3-13870a2a075e.png)

**Comment by phuocantd** [comment]
how to fix it? @sukesh-pfx
