### ISSUE TITLE
Warning due to expo peer dep

### ISSUE THREAD

**Issue by gfrancischini** [AppsFlyerSDK/appsflyer-react-native-plugin#445]
# Report

## Plugin Version

`6.8.2`

## On what Platform are you having the issue?

`Typescript/NPM`

## What did you do?

`yarn install`

## What did you expect to happen?

No errors/warning when installing this package on a pure React Native project (no Expo)

## What happened instead?

`warning " > react-native-appsflyer@6.8.2" has unmet peer dependency "expo@*".`

## Please provide any other relevant information.

Currently, expo is being listed as a peerDep. This is wrong as expo is not required for using this library. 

Options: Remove it as a peerDep or set it to optional:

```
"peerDependenciesMeta": {
  "expo": {
    "optional": true
  }
}
```

Thanks

**Comment by amit-kremer93** [comment]
Thank you for your suggestion. This will be added in the next release
