### ISSUE TITLE
Possible deprecation issue?

### ISSUE THREAD

**Issue by llee1990** [AppsFlyerSDK/appsflyer-react-native-plugin#448]
![image](https://user-images.githubusercontent.com/43011002/215630263-edc5dfcc-cb1d-4c96-ab28-7b07f7345fd3.png)

Just received an email from Apple about this. Is there anything we need to do if I am already using the latest package version. The AdServices framework have been supported since v6.1.3 so it shouldn't be an issue right?

**Comment by amit-kremer93** [comment]
Thank you for reaching out.
There shouldn't be any issue with the deprecation
