### ISSUE TITLE
Deprecated API V1 Token

### ISSUE THREAD

**Issue by LuanNguyenHNL** [AppsFlyerSDK/appsflyer-react-native-plugin#449]
# Report

## Plugin Version

6.9.4

## On what Platform are you having the issue?

ios and android (React Native)

## What did you expect to happen?
Do the team have plan for updating this SDK for the new API Token V2?

## Please provide any other relevant information.

<img width="1320" alt="Screenshot 2023-01-31 at 14 39 35" src="https://user-images.githubusercontent.com/101781199/215697032-89381d8a-c379-4eec-a1ed-7e698b1845db.png">

**Comment by amit-kremer93** [comment]
Thank you for reaching out.
This change is not related to the SDK so it will not effect the SDK behavior.

**Comment by ThushalIntervest** [comment]
So when we update the API V1 token to the API V2 token, the place we want to change in code is devKey ?

`appsFlyer.initSdk(
  {
    devKey: ???????,
    isDebug: true,
    appId: '1111111',
    onDeepLinkListener: true,
    timeToWaitForATTUserAuthorization: 10, //for iOS 14.5
  },
  (result) => {
    console.log(result);
  },
  (error) => {
    console.log(error);
  },
);`

**Comment by neharastogi093** [comment]
@amit-kremer93 
With new V2 token, the SDK is logging the events anymore. We verified the token using curl and it works. We are sending the V2 token in devKey under below code. The event log is working with V1 token.

appsFlyer.initSdk( { devKey: *********, isDebug: true, appId: '*******' });

Could you please explain what you meant by "This change is not related to the SDK so it will not effect the SDK behavior."?

Thank you.
