### ISSUE TITLE
react-native-appsflyer@6.9.4" has unmet peer dependency "expo@*"

### ISSUE THREAD

**Issue by canpoyrazoglu** [AppsFlyerSDK/appsflyer-react-native-plugin#455]
# Report

## Plugin Version

6.9.4
## On what Platform are you having the issue?

iOS + Android

## What did you do?

Do anything with yarn (even unrelated to AppsFlyer) e.g. "yarn add some-other-package"

## What did you expect to happen?

No warnings.

## What happened instead?

Got a warning with line `react-native-appsflyer@6.9.4" has unmet peer dependency "expo@*"`

## Please provide any other relevant information.

I'm not using Expo (so it's not in my project, hence the warning), and the peer dependency warning, even though harmless (things do work regardless of the error), is creating a clutter. Anyone who doesn't use Expo shouldn't see this warning.

**Comment by amit-kremer93** [comment]
Fixed in 6.10.1
