### ISSUE TITLE
Package react-native-appsflyer contains invalid configuration: "dependency.platforms.ios.podspecPath"

### ISSUE THREAD

**Issue by mishranova** [AppsFlyerSDK/appsflyer-react-native-plugin#458]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-appsflyer@6.10.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-appsflyer/react-native.config.js b/node_modules/react-native-appsflyer/react-native.config.js
index dfbe81b..1f279b3 100644
--- a/node_modules/react-native-appsflyer/react-native.config.js
+++ b/node_modules/react-native-appsflyer/react-native.config.js
@@ -3,7 +3,7 @@ const path = require('path');
 module.exports = {
   dependency: {
     platforms: {
-      ios: { podspecPath: path.join(__dirname, 'react-native-appsflyer.podspec') },
       android: {
         packageImportPath: 'import com.appsflyer.reactnative.RNAppsFlyerPackage;',
         packageInstance: 'new RNAppsFlyerPackage()',
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by amit-kremer93** [comment]
There is a MR related to this:
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/434
We need to check first how this change will impact older versions of RN in different apps.
We will update when it will be fixed.
Thx!
