### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AppsFlyerFramework" (6.10.1)

### ISSUE THREAD

**Issue by markstreich** [AppsFlyerSDK/appsflyer-react-native-plugin#462]
Trying to update to the latest version (re: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/issues/456), and  I'm getting the following error.

I'm kind of a CocoaPods newbie and maybe doing something dumb (`pod repo update` didn't help anyway), but it seems like (pod version) 6.10.1 is not out yet?

https://cocoapods.org/pods/AppsFlyerFramework#changelog links to https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-release-notes (6.10.0 is the latest version listed here)

```
[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
  In Podfile:
    react-native-appsflyer (from `../node_modules/react-native-appsflyer`) was resolved to 6.10.2, which depends on
      AppsFlyerFramework (= 6.10.1)

None of your spec sources contain a spec satisfying the dependency: `AppsFlyerFramework (= 6.10.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Couldn't install Pods. Updating the Pods project and trying again...
```

**Comment by markstreich** [comment]
If it's not clear, if I understand correctly:

Latest reactive-native-appsflyer version: 6.10.2
Latest AppsFlyerFramework pod: 6.10.0
AppsFlyerFramework dependency in reactive-native-appsflyer: 6.10.1

**Comment by SamMcDuffie** [comment]
I'm seeing similar behavior. However it looks like there is a 6.10.1 [release](https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases) for AppsFlyerFramework.

**Comment by amit-kremer93** [comment]
AppsFlyerFramework 6.10.1 is out. You need to update your local spec repo

**Comment by phamthang03** [comment]
@amit-kremer93 thank you, after pod repo update, this problem was solved
