### ISSUE TITLE
Missing Deeplink.md Docs file

### ISSUE THREAD

**Issue by walshie4** [AppsFlyerSDK/appsflyer-react-native-plugin#468]
# Report

## Plugin Version

N/A

## On what Platform are you having the issue?

N/A

## What did you do?

Click on the link to learn about deep linking in [this docs section](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/9a0b07fd3c134af89f08b0a39e739dac89e18cbb/Docs/API.md#-ondeeplinkcallback--functionunregister) (although all appear to be linking to the same broken file for those referring to deep linking)

## What did you expect to happen?

Docs file to be opened

## What happened instead?

Was directed to a 404 page (file doesn't exist in current `master` branch)

**Comment by amit-kremer93** [comment]
Thank you for reaching out. We will fix it
