### ISSUE TITLE
Non-organic test not working (stuck forever at "Open the app now")

### ISSUE THREAD

**Issue by canpoyrazoglu** [AppsFlyerSDK/appsflyer-react-native-plugin#470]
# Report

## Plugin Version

6.10.2

## On what Platform are you having the issue?

iOS

## What did you do?

 - Made sure app tracking is enabled in iOS settings.
 - Installed and init the SDK. 
 - Made sure `onInstallConversionData` is called (it is).
 - Deleted the app.
 - Went to SDK Integration Tests on portal, clicked Non-organic install.
 - Added my device with its IDFA.
 - Selected "other" as opposed to App Store, as I'm building from Xcode.
 - Clicked Run test, scanned the QR code on my device.
 - Installed the app (didn't launch)
 - Clicked I'm ready to open the app
 - Opened the app
 - Tap "Allow" in iOS ATT popup
 - Waited.

## What did you expect to happen?

Non-organic install should be detected in web portal

## What happened instead?

Nothing happened in web portal (stuck at "Open the app now" view in web portal). Also in the first install in `onInstallConversionData` `af_message` is `organic install` and `af_status` is `Organic`.

## Please provide any other relevant information.

iOS 16.5.

Initialized as:
```
 appsFlyer.initSdk(
            {
                devKey: [...],
                isDebug: true, //also tried false
                appId: Platform.OS === 'ios' ? env.appsFlyerAppId : '', //only iOS
                onInstallConversionDataListener: true, //Optional
                onDeepLinkListener: true, //Optional
                timeToWaitForATTUserAuthorization: 30, //for iOS 14.5,
                manualStart: true,
            },
            result => {
              [...]
            },
            error => {
                [...]
            },
        );
```

And then later `appsFlyer.startSdk();`.

**Comment by jtvargas** [comment]
@canpoyrazoglu any updates on how to test/expect this non-organic install?

**Comment by SYursa** [comment]
my solution is upgrade lib to -> "react-native-appsflyer": "^6.17.7" version and add appsFlyer.startSdk() after appsFlyer.initSdk(option)

so for now my init looks like
```

export const useAppsflyer = () => {
  useEffect(() => {
    const option = {
      isDebug: process.env.EXPO_PUBLIC_IS_APPSFLYER_DEBUG === 'true',
      devKey: process.env.EXPO_PUBLIC_APPSFLYER_DEV_KEY as string,
      timeToWaitForATTUserAuthorization: 30,
      onDeepLinkListener: true,
      ...(Platform.OS === 'ios'
        ? { appId: process.env.EXPO_PUBLIC_APPSFLYER_APP_ID as string }
        : {}),
    }

    appsFlyer.setOneLinkCustomDomains(
      [process.env.EXPO_PUBLIC_APPSFLYER_CUSTOM_DOMAIN as string],
      () => {
        appsFlyer.initSdk(option)
        appsFlyer.startSdk()
      },
      () => {
        appsFlyer.initSdk(option)
        appsFlyer.startSdk()
      }
    )
  }, [])
}

```
