### ISSUE TITLE
trackAppLaunch

### ISSUE THREAD

**Issue by abdRida** [AppsFlyerSDK/appsflyer-react-native-plugin#471]
Inside my mobile application, I have added the AppsFlyer package. However, I am facing an issue with the event af_opened_app. I would like to inquire if this problem is due to any changes made on your end, specifically the removal of the trackAppLaunch functionality. Could you please clarify the status of trackAppLaunch and whether it might be related to the issue I am experiencing?

**Comment by abdRida** [comment]
trackAppLaunch -> no longer needed. See new init guide
why you do that guys ?

**Comment by amit-kremer93** [comment]
`trackAppLaunch` was removed in version 6.x.x [see here](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin#--breaking-changes-when-updating-to-v6xx). Please follow the new apis
