### ISSUE TITLE
Can't build with adapty library

### ISSUE THREAD

**Issue by wefyns** [AppsFlyerSDK/appsflyer-react-native-plugin#472]
I using adapty react-native library for subscription and after install appsflyer library my project don't start (android)

here is error

error Failed to install the app. Make sure you have the Android development environment set 
up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\wefyn\Desktop\projects\freelance\chatai\android\app\src\debug\AndroidManifest.xml:11:18-70 Error:
        Attribute application@fullBackupContent value=(@xml/adapty_backup_rules) from [com.github.adaptyteam:AdaptySDK-Android:2.3.3] AndroidManifest.xml:11:18-70
        is also present at [com.appsflyer:af-android-sdk:6.10.3] AndroidManifest.xml:21:18-73 value=(@xml/appsflyer_backup_rules).        
        Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:7:5-12:19 to override.
FAILURE: Build completed with 2 failures.     

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@fullBackupContent value=(@xml/adapty_backup_rules) from [com.github.adaptyteam:AdaptySDK-Android:2.3.3] AndroidManifest.xml:11:18-70   
        is also present at [com.appsflyer:af-android-sdk:6.10.3] AndroidManifest.xml:21:18-73 value=(@xml/appsflyer_backup_rules).        
        Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:7:5-12:19 to override.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.       
================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.       
==============================================================================

* Get more help at https://help.gradle.org    

BUILD FAILED in 6m 21s

    at makeError (C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

I try to make (Suggestion: add 'tools:replace="android:fullBackupContent"')

and got this error
error Failed to install the app. Make sure you have the Android development environment set 
up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.     

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: Error parsing C:\Users\wefyn\Desktop\projects\freelance\chatai\android\app\src\main\AndroidManifest.xml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.       
================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.       
==============================================================================

* Get more help at https://help.gradle.org    

BUILD FAILED in 46s

    at makeError (C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\Users\wefyn\Desktop\projects\freelance\chatai\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.

somebody know how to fix it?

**Comment by amit-kremer93** [comment]
Hey @wefyns and thank you for reaching out. Please take a look on:
https://dev.appsflyer.com/hc/docs/install-android-sdk#backup-rules
https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9#issuecomment-760150089
Let us know if it solved your problem.

**Comment by wefyns** [comment]
> Hey @wefyns and thank you for reaching out. Please take a look on: https://dev.appsflyer.com/hc/docs/install-android-sdk#backup-rules [AppsFlyerSDK/appsflyer-android-sdk#9 (comment)](https://github.com/AppsFlyerSDK/appsflyer-android-sdk/issues/9#issuecomment-760150089) Let us know if it solved your problem.

solved. thanks

**Comment by capaj** [comment]
@wefyns how exactly have you solved it?
I have `android:allowBackup="false"` in my `/android/app/src/main/AndroidManifest.xml` yet still I have this build error.
