### ISSUE TITLE
Incorrect behaviour of onInstallConversionData and onAppOpenAttribution

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [AppsFlyerSDK/appsflyer-react-native-plugin#473]
# Report

## Plugin Version

6.10.3

## On what Platform are you having the issue?

Android

## What did you do?

- Created a onelink with the following attribution parameters 

![image](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/90186621/e1c7d9c8-0dc6-4fa5-a94c-46abdec3ead8)

- Opened the onelink in my device. It redirected me to the Play Store since the app is not installed.
- Added `onInstallConversionData`, `onAppOpenAttribution` and `onDeepLink` before calling `initSdk`, as specified in the docs.
```
appsFlyer.onInstallConversionData((res) => {
  console.log('onInstallConversionData', JSON.stringify(res, null, 2));
});

appsFlyer.onAppOpenAttribution((res) => {
  console.log('onAppOpenAttribution', JSON.stringify(res, null, 2));
});

appsFlyer.onDeepLink((res) => {
  if (res?.deepLinkStatus !== 'NOT_FOUND') {
    console.log('onDeepLink', JSON.stringify(res?.data, null, 2));
  }
});

appsFlyer.initSdk(
  {},
  (result) => {},
  (error) => {}
);
```
- While the Play Store page for the app is open, I run the debug build (`yarn start && yarn android`).
- I check the console logs.

## What did you expect to happen?

- `onInstallConversionData` must be called on the first launch of the app install (Deferred Deep Link) with all the attribution parameters from the screenshot.
- `onAppOpenAttribution` must be called **after** the first launch (and not **on** the first launch).

## What happened instead?

- `onInstallConversionData` is not called with any of the attribution parameters. I only get back this : 

```
{
   "status":"success",
   "type":"onInstallConversionDataLoaded",
   "data":{
      "install_time":"2023-06-06 19:06:28.960",
      "af_status":"Organic",
      "af_message":"organic install",
      "is_first_launch":true
   }
}
```
- `onInstallConversionData` is called every time I open the deep link **after** the first install.

- `onAppOpenAttribution` is never called. Tried both background and killed state.

- `onDeepLink` is called on the first install and every app open. On the first install, it gives me `deep_link_value` and `deep_link_sub1` correctly. All other fields are empty.

## Please provide any other relevant information.

I'm on the latest version of the library.

**Comment by amit-kremer93** [comment]
if you implemented `onDeepLink` and set `onDeepLinkListener: true` in the init object `onAppOpenAttribution` will not be called. Please follow the instructions in the [Docs sections](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/Docs/RN_UnifiedDeepLink.md).
For further information please contact our support team
