### ISSUE TITLE
How Implement SKAN in Appsflyer ? 

### ISSUE THREAD

**Issue by ajiehatajie** [AppsFlyerSDK/appsflyer-react-native-plugin#474]
How is the SKAN implementation, my application has received ATT permission using the library [https://www.npmjs.com/package/react-native-tracking-transparency](https://www.npmjs.com/package/react-native-tracking-transparency)
, but in the dashboard the data does not enter 

Been emailed with CS but it didn't help at all

message in dashboard appsflyer. 

Your app isn’t set up to send iOS postback copies (iOS 15+) to AppsFlyer. This is required to assure the integrity of your SKAN measurement

```
const getPermissionTransparancy = useCallback(async () => {
    const trackingStatus = await getTrackingStatus();

    if (trackingStatus !== 'authorized' && !permissions.iosTransparancy) {
      const trackingStatusPermission = await requestTrackingPermission();
      if (trackingStatusPermission) {
        setShowDialogTransparancy(true); // for state 
        dispatch(actionsBootstrap.setShowPermissionTransparancy(true)); //for redux
        dispatch(
          actionsBootstrap.setPermissionsIosTransparancy(
            trackingStatusPermission,
          ), //for redux
        );
      }
    }
  }, [dispatch, permissions]);
```

 

my depedency 

"react-native": "0.71.10",
 "react-native-tracking-transparency": "^0.1.2",
 "react-native-appsflyer": "^6.10.3",

**Comment by amit-kremer93** [comment]
Please take a look in the [help center](https://support.appsflyer.com/hc/en-us/articles/360011420698-SKAdNetwork-SKAN-solution-guide)
