### ISSUE TITLE
Missing 'link' property in UnifiedDeepLinkData

### ISSUE THREAD

**Issue by OrenMag** [AppsFlyerSDK/appsflyer-react-native-plugin#475]
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/df985ace2f67f829811880a3a971ad6352d4272c/index.d.ts#L56

On `UnifiedDeepLinkData`  interface, the `link` is missing.
the data object on onDeepLink handler returns a link property, but the interface doesn't expose it.

Please add the link to the interface so it'd fit (we get TS errors for it)

<img width="517" alt="Screenshot 2023-06-22 at 14 39 52" src="https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/78356438/c14af7fd-0422-4402-9157-5f2389caefb1">

**Comment by amit-kremer93** [comment]
Added to the latest version
