### ISSUE TITLE
Non-organic Integration Test Successful but Attribution Data is for organic

### ISSUE THREAD

**Issue by singhayush1403** [AppsFlyerSDK/appsflyer-react-native-plugin#478]
# Report

## Plugin Version

`6.10.2`

## On what Platform are you having the issue?

 ios and android

## What did you do?

- Registered my device on test devices
- Started Non-organic integration test
- Scanned QR and installed the app from App Store
- Test Successful
- SDK shows organic install in app logs

## What did you expect to happen?

Install to be recorded as a Non-organic install

## What happened instead?

Install recorded as an organic install

## Please provide any other relevant information.

Using Expo SDK - version 48.0.16

**Comment by jorgerojas26** [comment]
I'm having the exact same issue, did you find any solution?

**Comment by EmanuilM** [comment]
> I'm having the exact same issue, did you find any solution?

Did you resolve it?

**Comment by jtvargas** [comment]
Any updates on this? @amit-kremer93 @jorgerojas26
