### ISSUE TITLE
IOS onDeepLink not triggering when app not installed app

### ISSUE THREAD

**Issue by abgaryanharutyun** [AppsFlyerSDK/appsflyer-react-native-plugin#487]
# Report

## Plugin Version

```
"react-native-appsflyer": "^6.12.1",
```

## On what Platform are you having the issue?

```
ios
```

## What did you expect to happen?

DeepLinking not works when the app not installed on your app

## What happened instead?

when the app is not installed on the mobile app when installing from the app store then opening from AppStore `onDeepLink` not triggering

**Comment by oldstud** [comment]
Hi, @abgaryanharutyun Could you tell me how you resolved this issue?

**Comment by abgaryanharutyun** [comment]
> Hi, @abgaryanharutyun Could you tell me how you resolved this issue?

For my case it was cache. I have tried in other device and it started to work thats why i have closed. 

I will recommend to do the same thing use other device to test!
