### ISSUE TITLE
io.invertase.firebase.crashlytics.UnhandledPromiseRejection - Unable to resolve host "inapps.appsflyer.com": No address associated with hostname

### ISSUE THREAD

**Issue by rishabh-raena** [AppsFlyerSDK/appsflyer-react-native-plugin#488]
# Report

## Plugin Version
6.12.1

## On what Platform are you having the issue?
 Ios and Android

## What did you do?
I integrated the version and got these exceptions on Firebase.

## What did you expect to happen?
It should not encounter these logs. I'm doubtful that events are dropping heavily due to these exceptions. 

## Please provide any other relevant information.
React-native version- 0.63.5

**Comment by trinitiwowka** [comment]
same problem

Unable to resolve host "mde7xp-launches.appsflyersdk.com": No address associated with hostname
