### ISSUE TITLE
Status code failure 404 on logEvent Android

### ISSUE THREAD

**Issue by jwillingham789** [AppsFlyerSDK/appsflyer-react-native-plugin#491]
# Report

## Plugin Version
6.12.1

## On what Platform are you having the issue?
android

## What did you do?

appsFlyer.logEvent

## What did you expect to happen?

Event to be logged

## What happened instead?

`  
    HTTP: [207394383] response code: 404 Not Found
    body: application doesn't exist
    took 272ms
`

## Please provide any other relevant information.

The application is set up on the AppsFlyer console and Im able to initialize the project just fine.

**Comment by singhagam1** [comment]
@jwillingham789 
Can you let me know what was leading this issue to happen and what was the fix ?

**Comment by jwillingham789** [comment]
@singhagam1 This library uses the active build variant's `applicationId` in the `appsFlyer.initSdk` method. I only had a production application set up on the appsflyer console so it couldn't find a matching `applicationId` when i was building a dev variant with the `.dev` suffix. Not sure why you can explicitly pass an `appId` to the `appsFlyer.initSdk` on ios but not on android. Seems like a simple addition that would address this problem.
