### ISSUE TITLE
Redefinition of 'SUCCESS' as different kind of symbol build error

### ISSUE THREAD

**Issue by cyoxxg** [AppsFlyerSDK/appsflyer-react-native-plugin#497]
# Report

## Plugin Version
"react": "18.2.0"
"react-native": "0.71.6"
"react-native-appsflyer": "^6.12.2"

## On what Platform are you having the issue?
iOS

## What did you do?
During iOS build, there is a conflict with the 'SUCCESS' symbol declared in another third-party library.
Error message: "Redefinition of 'SUCCESS' as different kind of symbol"

## What did you expect to happen?
The build should succeed

## What happened instead?
The build failed

## Please provide any other relevant information.
```
// RNAppsFlyer.h
...
static NSString *const SUCCESS    = @"Success";  // this line, Redefinition of 'SUCCESS' as different kind of symbol
...
```

**Comment by amit-kremer93** [comment]
Thank you for inform us. Which third party library it is?
