### ISSUE TITLE
getContentCards cause app crash

### ISSUE THREAD

**Issue by zrg-team** [AppsFlyerSDK/appsflyer-react-native-plugin#498]
# Report

## Plugin Version

"react-native-appsflyer": "6.10.2",

## On what Platform are you having the issue?

Android

## What did you do?

```
try {
  await appboy.getContentCards()
} catch {
}
```

## What did you expect to happen?

+ Can get content cards without crash

## What happened instead?

![image](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/38390571/7f1c48ff-70ee-4ced-b44d-766099a8ab15)

## Please provide any other relevant information.

![image](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/38390571/ba457cab-efde-48cb-ad97-1daabfd60ad2)

**Comment by amit-kremer93** [comment]
This issue is related to Braze
