### ISSUE TITLE
question regarding the af_app_opened event

### ISSUE THREAD

**Issue by capaj** [AppsFlyerSDK/appsflyer-react-native-plugin#499]
Sorry for deleting the issue template, but can I have just one question?
Is `af_app_opened` event sent on startup by default or do I need to send it manually?

**Comment by abdRida** [comment]
same question !

**Comment by amit-kremer93** [comment]
The SDK sends this event by default. You can read more [here](https://dev.appsflyer.com/hc/docs/integrate-ios-sdk#log-sessions)

**Comment by Harkertron** [comment]
Testing with the SDK we are observing the events are sent to Appsflyer correctly - with the exception of this specific `af_app_opened` event.

Is there explicit handling required for this event to surface? The iOS documentation linked above mentions triggering `start` within `didBecomeActive` iOS lifecycle - but this seems to make no impact - should we be calling isStopped=false, isStopped=true to restart the SDK if it was already running?

Similarly on Android - should we be restarting the Appsflyer SDK within the onStart() phase of the Android activity life cycle to force these events to surface? The documentation seems to imply it should just work without any extra configuration.

**Comment by srilokhkaruturi** [comment]
Any updates?
