### ISSUE TITLE
Chrome not working deep linking

### ISSUE THREAD

**Issue by phuocantd** [AppsFlyerSDK/appsflyer-react-native-plugin#518]
In iOS, it work on safari, but I open with chrome, deep link not working
How to fix it?
I tried using `https://demo.onelink.me/1aBC/123ab45c?af_force_deeplink=true` but not working

**Comment by thiennhank9** [comment]
Hi @amit-kremer93 , @phuocantd , I'm encountering the same issue. The deeplink is working fine on android.
But on ios, it only works if opening via safari, not via chrome. 
Might I know how to fix this?
I'm using v6.13.1.
Thanks!

**Comment by Georg7** [comment]
Same issue here - did you find a solution?

**Comment by Rajats2678** [comment]
The issue seems to be resolved but I too facing the same issue.  @amit-kremer93 @phuocantd Please assist for the appropriate solve
