### ISSUE TITLE
AppsFlyer iOS SDK 6.13.0 required to comply with iAd framework removal

### ISSUE THREAD

**Issue by langest** [AppsFlyerSDK/appsflyer-react-native-plugin#520]
In your readme it says that the current version of iOS AppsFlyer SDK is v6.12.2.

[Here](https://support.appsflyer.com/hc/en-us/articles/19329934807569-Bulletin-iAd-framework-to-be-removed-from-the-iOS-SDK), on your support page, it says that we need to be on AppsFlyer iOS SDK 6.13.0 to be compliant with the removal of iAd framework. If we are not, Apple will block our app within two years.

I kindly ask that you would bump your iOS AppsFlyer SDK to >=6.13.0 so that we can update our app to use it as soon as possible to avoid having it blocked by Apple.

# Report

## What did you expect to happen?

I expect the latest release of appsflyer-react-native-plugin to use AppsFlyer iOS SDK >=6.13.0.

## What happened instead?

Latest release of appsflyer-react-native-plugin uses iOS AppsFlyer SDK is v6.12.2.

**Comment by ge-af** [comment]
Hi @langest 

We recently released the new iOS SDK version without any reference to the deprecated iAd framework. The version was released last week (**v6.12.3**) for the native environment. We do expect this release to be included in our next React Native plugin release. We currently have no concrete estimation on when this plugin version will be released but we are aware of this issue and it will be handled soon.

Please be advised that regarding Apple's point of view there is no immediate action and it can take **up to 2 years** to be enforced. Obviously we are working to have this iAd removal on all environments way before then.

**Comment by ConorLindsay94** [comment]
Just to add to this we need version >=6.13.0 to send consent for DMA compliance on Android - received this notification via an email from AppsFlyer. Sounds like there needs to be a release before 6th March so anyone using this plugin can facilitate this?
