### ISSUE TITLE
In-App Purchase Tracking

### ISSUE THREAD

**Issue by FabricioMF100** [AppsFlyerSDK/appsflyer-react-native-plugin#521]
Hello!

I would like to know better if the react native plugin automatically tracks purchases, renewals and cancellations of in-app transactions (IAP) processed by Google Play and App Store.

Some points in the official AppsFlyer documentation say that this is done automatically, however in the documentation for Android SDK and iOS SDK they say that the Purchase Connector is necessary for this (https://dev.appsflyer.com/hc/docs/purchase -connector-ios), but from what I saw there is no version of this connector for React Native.

Therefore, I would like to understand better:
Is it automatic or not?
If not, is there any integration for React Native or any integration guides?

**Comment by korkija** [comment]
@FabricioMF100 
Good afternoon 
Have you received any response from support?
