### ISSUE TITLE
Rapidly growing organic installs data

### ISSUE THREAD

**Issue by G-Linker** [AppsFlyerSDK/appsflyer-react-native-plugin#522]
# Report

## Plugin Version

`6.12.2`

## On what Platform are you having the issue?

ios

## What did you do?

It's impossible to determine why Organic installs are growing so fast, and we're not doing anything extra on the app

## What did you expect to happen?

It should grow at the same frequency as before

## What happened instead?

Since the 31st of January, we've been getting a massive increase in Organic installs every day, with the largest value being a 20-fold increase compared to the previous one.

**Comment by G-Linker** [comment]
@onamfc Thanks for the reply, I got in touch with the support team and they told me that they will look into the issue.

**Comment by onamfc** [comment]
I'd love to know what they share. We're starting the integration process and imagine will run into the same issue.

**Comment by mattlennon3** [comment]
> it might be because your existing users are being seen for the first time by the SDK which is being considered an install

Hey @G-Linker, did you get any response from support? We're experiencing the same issue and would like to know if this is the reason. @amit-kremer93 would appreciate it if you could confirm this behaviour? Thanks 🙏

**Comment by G-Linker** [comment]
@mattlennon3 you can try to contact support. I communicated with support and found that it was a version from a long time ago, so support suggested that I make some filters and focus only on the valid app version. Hope it helps.

**Comment by mattlennon3** [comment]
Thanks for the reply @G-Linker !
