### ISSUE TITLE
SDK version >=6.13.0 for DMA compliance

### ISSUE THREAD

**Issue by ConorLindsay94** [AppsFlyerSDK/appsflyer-react-native-plugin#525]
# Report

## On what Platform are you having the issue?

Android

## Issue

Have received an email from AppsFlyer indicating that version >=6.13.0 for their Android SDK allows us to pass consent for DMA compliance which Google is taking into effect on 6th March 2024.

Can we get the SDKs updated so we can ensure we are compliant before that date?

**Comment by AdamGerthel** [comment]
I'm wondering the same thing. It's also not completely clear how to implement it. Will it be a new kind of prompt?
