### ISSUE TITLE
setConsentData type issue

### ISSUE THREAD

**Issue by artyorsh** [AppsFlyerSDK/appsflyer-react-native-plugin#528]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-appsflyer@6.13.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-appsflyer/index.d.ts b/node_modules/react-native-appsflyer/index.d.ts
index e1ae493..ba6ace1 100644
--- a/node_modules/react-native-appsflyer/index.d.ts
+++ b/node_modules/react-native-appsflyer/index.d.ts
@@ -115,8 +115,8 @@ declare module "react-native-appsflyer" {
     }
 
     export const AppsFlyerConsent: {
-        forGDPRUser: (hasConsentForDataUsage: boolean, hasConsentForAdsPersonalization: boolean) => void;
-        forNonGDPRUser: () => void;
+        forGDPRUser: (hasConsentForDataUsage: boolean, hasConsentForAdsPersonalization: boolean) => AppsFlyerConsentType;
+        forNonGDPRUser: () => AppsFlyerConsentType;
     }
 
     export type AppsFlyerConsentType = typeof AppsFlyerConsent;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by chriskurzeja** [comment]
I believe the proposed patch above doesn't go far enough in correcting the broken types. The following should actually fix the issue (ensuring that the object returned from `forGDPRUser` and `forNonGDPRUser` actually matches the expected type (an object containing `isUserSubjectToGDPR`, `hasConsentForDataUsage` and `hasConsentForAdsPersonalization`)  based on the two platform specific implementations :
 - iOS [setConsentData](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/3806778fd6ebf875ce311a584a8591e84c3c5d85/ios/RNAppsFlyer.m#L572)
 - Android [setConsentData](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/3806778fd6ebf875ce311a584a8591e84c3c5d85/android/src/main/java/com/appsflyer/reactnative/RNAppsFlyerModule.java#L825)
 
 
 ```diff
 diff --git a/node_modules/react-native-appsflyer/index.d.ts b/node_modules/react-native-appsflyer/index.d.ts
index e1ae493..d6d8442 100644
--- a/node_modules/react-native-appsflyer/index.d.ts
+++ b/node_modules/react-native-appsflyer/index.d.ts
@@ -115,11 +115,15 @@ declare module "react-native-appsflyer" {
     }
 
     export const AppsFlyerConsent: {
-        forGDPRUser: (hasConsentForDataUsage: boolean, hasConsentForAdsPersonalization: boolean) => void;
-        forNonGDPRUser: () => void;
+        forGDPRUser: (hasConsentForDataUsage: boolean, hasConsentForAdsPersonalization: boolean) => AppsFlyerConsentType;
+        forNonGDPRUser: () => AppsFlyerConsentType;
     }
 
-    export type AppsFlyerConsentType = typeof AppsFlyerConsent;
+    export interface AppsFlyerConsentType {
+        isUserSubjectToGDPR: boolean;
+        hasConsentForDataUsage?: boolean;
+        hasConsentForAdsPersonalization?: boolean;
+    }
 
     const appsFlyer: {
         onInstallConversionData(callback: (data: ConversionData) => any): () => void;
```

**Comment by walterholohan** [comment]
@amit-kremer93 can we get a fix for this merged. Seems like its very important with the March 6th deadline quickly approaching

**Comment by buuuudzik** [comment]
+1

**Comment by walterholohan** [comment]
@chriskurzeja @artyorsh thanks for the above. Super helpful.

Just wondering what method did you use to determine if the user was in a GDPR region or not? I was thinking to use the Timezone string to determine. Been keen to see if there is a better way
