### ISSUE TITLE
CocoaPods Issue when trying to use the latest version of Appsflyer 6.13.0

### ISSUE THREAD

**Issue by amromun** [AppsFlyerSDK/appsflyer-react-native-plugin#531]
# Report

## Plugin Version

Current version: 6.10.3
Trying to use the latest Version: 6.13.0

## On what Platform are you having the issue?

React Native 0.72.4

## What did you do?

When I changed the version of AppsFlyer from 6.10.3 to 6.13.0 and tried to do pod install it failed with the below error: 

[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
  In Podfile:
    react-native-appsflyer (from `../node_modules/react-native-appsflyer`) was resolved to 6.13.0, which depends on
      AppsFlyerFramework (= 6.13.0)
 
None of your spec sources contain a spec satisfying the dependency: `AppsFlyerFramework (= 6.13.0)`.
 
## What did you expect to happen?

pod install to work

## What happened instead?

It did work and got the below error: 

[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
  In Podfile:
    react-native-appsflyer (from `../node_modules/react-native-appsflyer`) was resolved to 6.13.0, which depends on
      AppsFlyerFramework (= 6.13.0)
 
None of your spec sources contain a spec satisfying the dependency: `AppsFlyerFramework (= 6.13.0)`.

## Please provide any other relevant information.

We tried to remove the Pods folder and the Podfile.lock and install it again and we are still getting the same issue

**Comment by amit-kremer93** [comment]
@amromun try to remove the plugin, install it again and run `pod install --repo-update`

**Comment by amromun** [comment]
> @amromun try to remove the plugin, install it again and run `pod install --repo-update`

Thanks. It worked with me
