### ISSUE TITLE
How to configure "Send SKAN postback" with react-native plugin

### ISSUE THREAD

**Issue by hdsuperman** [AppsFlyerSDK/appsflyer-react-native-plugin#532]
# Report

<img width="980" alt="Screenshot 2024-03-06 at 1 09 38 PM" src="https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/50064165/32babc93-2b78-499f-98b7-ed9e34168235">

## Plugin Version

ℹ Please replace these two lines with the plugin version.
6.13.0

## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
ios

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Clear warning

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  

SKAN Overview dashboard show warning:

```
Your app isn’t set up to send iOS postback copies (iOS 15+) to AppsFlyer. This is required to assure the integrity of your SKAN measurement
```

I have configured it in info.plist:

```
	<key>NSAdvertisingAttributionReportEndpoint</key>
	<string>https://appsflyer-skadnetwork.com/</string>
```
But there are still warnings.

**Comment by Mikewa33** [comment]
Same issue

**Comment by AdamGerthel** [comment]
See https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/494

**Comment by RouberR** [comment]
Any solution?

**Comment by hdsuperman** [comment]
close, It takes some time to wait. After the configuration is completed, I can see the returned data a few days later.

**Comment by trung1051996** [comment]
Hi @hdsuperman H
I have configured in info.plist same your configure and released new version about 2 week ago
```
	<key>NSAdvertisingAttributionReportEndpoint</key>
	<string>https://appsflyer-skadnetwork.com/</string>
``` 
But Appsflyer dashboard still shows warning.
In Podfile, i configured `platform :ios, '10.0'`. Do i need update to 15?
Thanks in advance

**Comment by rakshitharodrigo** [comment]
Hi There,
I'm facing the same issue, checked with all the configs mentioned in the AppsFlyer SKAN post back, it is just to add the key and string right?. No any other additional step to be taken? I can see other AppsFlyer events are logging properly. Only SKAN Analytics got this warning message. Please let me know if there is anything... My App is published with these SKAN settings for almost a month (3+ weeks).

**Comment by RohanRajGautam** [comment]
Any updates on this issue? Facing similar problem.

**Comment by Vorob-Astronaut** [comment]
@trung1051996 @rakshitharodrigo @RouberR 

were you able to fix it?

**Comment by AlexSalas55** [comment]
I had this problem and did not know how to solve it. My solution was to simply run the ad campaign and when the SKAN data started coming in it disappeared after a couple of days. That message comes up because the SKAN data has not been received yet.

**Comment by LouisCapelle** [comment]
same issue here

**Comment by markwitt1** [comment]
Is this message affected by crowd anonymity, so we need min 70 daily installs for it to disappear?

**Comment by sebastiantheobald** [comment]
any news on that here? Run into the same problem

**Comment by agusstingalvan** [comment]
any solution?
