### ISSUE TITLE
Support for new architecture and bridgeless

### ISSUE THREAD

**Issue by brentvatne** [AppsFlyerSDK/appsflyer-react-native-plugin#537]
# Report

## Plugin Version

n/a

## On what Platform are you having the issue?

iOS and Android

## What did you do?

n/a

## What did you expect to happen?

n/a

## What happened instead?

n/a

## Please provide any other relevant information.

Hi there! I'm working on supporting the roll out of the new architecture + bridgeless with Expo and Meta, and as part of that we identified which are the most popular native libraries on [EAS Build](https://docs.expo.dev/build/introduction/) to help prioritize which libraries to investigate. react-native-appsflyer came up on that list. [See the list on Google Sheets](https://docs.google.com/spreadsheets/d/1F1tI9PQLl_uab3HNYNwgjPVL2r0hJ9VymXcgDp5etdg/) (request edit access if you'd like to update the status of react-native-appsflyer after testing, or if you prefer to report back here on this issue it's fine too). 

We want to start recommending folks try out the new architecture in the next release, react-native 0.74 / Expo SDK 51. Ideally we can get the ecosystem ready to switch over to the new architecture within the next few releases. So, we'll have from now until 0.74 release (before May) to give meta feedback on anything that might not be working as expected with the new arch/bridgeless enabled.

Folks at Meta would really appreciate it if you could test your libraries against the latest release and report any issues that you find. **This new version enables an interop layer by default**, so hopefully many things will just work, but the more off of the beaten path of a simple module / view that a library goes the more likely it is to encounter possible issues ;) The following gist includes a step by step process for how to test your library and report issues: https://gist.github.com/cipolleschi/82b7a9561b8861330efabbd3eb08c6f5.

**Comment by AdamGerthel** [comment]
@amit-kremer93 so the new architecture is supported? Starting with which version?

**Comment by christophe-chausseray** [comment]
@amit-kremer93 If you have a bit of time I would like to have more information about the progress of this issue as well
