### ISSUE TITLE
privacy manifest for third part sdk

### ISSUE THREAD

**Issue by jordan-rp-cb** [AppsFlyerSDK/appsflyer-react-native-plugin#538]
# Report

Could you please provide Privacy Manifest support for appsflyer SDK? Some relevant links as follows:

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
https://stackoverflow.com/questions/78163859/itms-91053-missing-api-declaration-privacy

Thank you!

## Plugin Version

ℹ Please replace these two lines with the plugin version.
6.13.0

## On what Platform are you having the issue?
React Native
iOS

## What did you do?
N/A
## What did you expect to happen?
N/A

## What happened instead?
N/A

## Please provide any other relevant information.
Linked above

**Comment by Nonoyamalfoy** [comment]
Hi! I would like to know when you have an idea of when it will be released!

**Comment by d-moreira** [comment]
@amit-kremer93 any news regarding the timeline for this release?

**Comment by matthewdfay** [comment]
I see that 6.14.0 was released on the iOS SDK with the privacy manifest file. Any timeline for when this will be updated to use that SDK?

**Comment by luisfmsouza** [comment]
Do we have any updates about this issue? I believe we are getting too close to the deadline.

Trying to breakdown what we need to do, given we are 13 days away from May 1st, but 4 days are weekends. We have 9 working days to: 
- increment iOS SDK version
- release the `appsflyer-react-native-plugin`
- upgrade the plugin on our apps
- test and release our apps with the latest plugin version

**Comment by CTOverton** [comment]
@amit-kremer93 would love an update on this as well. This is a critical issue.

**Comment by jscarmona** [comment]
Opened PR https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/pull/543

**Comment by Nonoyamalfoy** [comment]
I found the documentation about manifests and have created the manifest file myself.
However, I don't understand what should be in the tracking domain.
If anyone can help me, please let me know.
https://support.appsflyer.com/hc/en-us/articles/21677433322641-Privacy-Manifest

**Comment by luisfmsouza** [comment]
This got fixed by the #546
