### ISSUE TITLE
redefinition of 'SUCCESS' as different kind of symbol

### ISSUE THREAD

**Issue by RyuWoong** [AppsFlyerSDK/appsflyer-react-native-plugin#541]
# Report

## Plugin Version
`6.13.1`

## On what Platform are you having the issue?
ios

## What did you do?
Run build

## What did you expect to happen?
Build Success but error

## What happened instead?
redefinition of 'SUCCESS' as different kind of symbol

i'm using this lib.    "@react-native-seoul/naver-login": "3.0.0",

naveridlogin-sdk-ios/NaverThirdPartyLogin.framework/Headers/NaverThirdPartyLoginConnection.h:11:

```
typedef enum {
    SUCCESS = 0, // <--- here
    PARAMETERNOTSET = 1,
    CANCELBYUSER = 2,
    NAVERAPPNOTINSTALLED = 3 ,
    NAVERAPPVERSIONINVALID = 4,
    OAUTHMETHODNOTSET = 5,
    INVALIDREQUEST = 6,
    CLIENTNETWORKPROBLEM = 7,
    UNAUTHORIZEDCLIENT = 8,
    UNSUPPORTEDRESPONSETYPE = 9,
    NETWORKERROR = 10,
    UNKNOWNERROR = 11
} THIRDPARTYLOGIN_RECEIVE_TYPE;

```

## Please provide any other relevant information.
-

**Comment by dev-jaylim** [comment]
+1

**Comment by RyuWoong** [comment]
@dev-jaylim 
Hi, there

here is Solution.
step 1. open AppDelgate.mm
step 2. find line "import AppsFlyerLib.h"
step 3. fix it to the content below

`#if __has_include(<AppsFlyerLib/AppsFlyerLib.h>) // from Pod
#import <AppsFlyerLib/AppsFlyerLib.h>
#else
#import "AppsFlyerLib.h"
#endif`
