### ISSUE TITLE
Expo - Cannot read properties of undefined (reading 'shouldUseStrictMode')

### ISSUE THREAD

**Issue by umangloria** [AppsFlyerSDK/appsflyer-react-native-plugin#550]
# Report
I followed this guide: https://dev.appsflyer.com/hc/docs/rn_expoinstallation
after adding the plugin information on app.json file when I tried to run the app it seems like npx expo prebuild --clean  or yarn run ios commands are failing now. 
the error we are  getting: `CommandError: Cannot read properties of undefined (reading 'shouldUseStrictMode')`

## Plugin Version

"react-native-appsflyer": "^6.14.3",
"expo": "^50.0.17",

## On what Platform are you having the issue?

both (expo managed RN project)

## What did you do?

npx expo install react-native-appsflyer
and other steps mentioned here: https://dev.appsflyer.com/hc/docs/rn_expoinstallation

## What did you expect to happen?

App should run fine on both android and iOS without any build/runtime issues

## What happened instead?

getting this error (CommandError: Cannot read properties of undefined (reading 'shouldUseStrictMode')) during following commands:
- npx expo prebuild --clean
- yarn run ios
- yarn run android

## Please provide any other relevant information.

this is the first time we are trying to use this package. Also as you can see we are using latest expo as well.

**Comment by KharamanV** [comment]
@umangloria hey mate, got this as well. Have you fixed it?

**Comment by KharamanV** [comment]
nvm, I've fixed it by setting `["react-native-appsflyer", {}]` in app.json -> plugins field. (before that I has just `"react-native-appsflyer"`

**Comment by umangloria** [comment]
> nvm, I've fixed it by setting `["react-native-appsflyer", {}]` in app.json -> plugins field. (before that I has just `"react-native-AppsFlyer"`

Yes, there should be no `"react-native-appsflyer"` entry directly, I didn't notice that it has been added by default, I think this should not be added this way by default or it should be added properly automatically, In my case I didn't realize this until I started comparing all the changes in the working branch.

**Comment by ruslanjabari** [comment]
Encountered this issue again.

```
    "expo": "^50.0.14",
    "react-native-appsflyer": "^6.14.3",
    "react-native": "0.73.6",
```

even tried setting the restrict mode to true and it did not work

```
[
        "react-native-appsflyer",
        {
          "shouldUseStrictMode": true
        }
],  
```
   
patched the plugin like so to make it work:
```
module.exports = function withAppsFlyer(config, options = {}) {
  const { shouldUseStrictMode = false } = options;
  config = withAppsFlyerIos(config, shouldUseStrictMode);
  return config;
};
```

**Comment by ruslanjabari** [comment]
> Encountered this issue again.
> 
> ```
>     "expo": "^50.0.14",
>     "react-native-appsflyer": "^6.14.3",
>     "react-native": "0.73.6",
> ```
> 
> even tried setting the restrict mode to true and it did not work
> 
> ```
> [
>         "react-native-appsflyer",
>         {
>           "shouldUseStrictMode": true
>         }
> ],  
> ```
> 
> patched the plugin like so to make it work:
> 
> ```
> module.exports = function withAppsFlyer(config, options = {}) {
>   const { shouldUseStrictMode = false } = options;
>   config = withAppsFlyerIos(config, shouldUseStrictMode);
>   return config;
> };
> ```

you'll also need to patch withAppsFlyerIos.js (withPodfile func):
```
      if (contents.includes("AppsFlyer Strict Mode")) {
        console.log(
          "AppsFlyer configuration already exists in Podfile. Skipping modification."
        );
        return config;
      }
```

**Comment by bob-devereux** [comment]
Why was this closed?  Seems like a bug.

**Comment by yash2code** [comment]
facing same issue in expo sdk 50. how do you guys solved it ?
