### ISSUE TITLE
SDK Integration Tests Failed but show Success in terminal

### ISSUE THREAD

**Issue by amir-ibrahim** [AppsFlyerSDK/appsflyer-react-native-plugin#557]
## Plugin Version
6.14.3

## On what Platform are you having the issue?
Android

## What did you do?
after finishing setup AppsFlyer Integration and trying to test it I faced an issue SDK Integration Tests (Non-organic install) Failed but show Success in terminal

## What did you expect to happen?
complete Non-organic install sucssfully

## What happened instead?
nothing happen

![Screenshot 2024-06-05 at 4 08 16 PM](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/assets/41516271/cf88c166-275d-4d89-b4c0-2dfff2671936)

**Comment by Firanus** [comment]
@amir-ibrahim I'm experiencing a similar issue here. How did you solve your problem?

**Comment by amir-ibrahim** [comment]
@Firanus i contacted the customer support they say because you are in the free plan once you upgrade to any plan you will see response
