### ISSUE TITLE
Onelink not working in IOS 17.3

### ISSUE THREAD

**Issue by TanNguyenEnouvo** [AppsFlyerSDK/appsflyer-react-native-plugin#560]
# Report

## Plugin Version

ℹ use: "react-native-appsflyer": "^6.14.3",

## On what Platform are you having the issue?

ℹ IOS

## What did you do?

ℹ I am using Onelink for a referral function to open my app and retrieve data. It works perfectly on my iPhone 12 running iOS 17.5.1. However, on my iPhone 11 with iOS 17.3, Onelink redirects me to the App Store, even though my app is already installed.

## What did you expect to happen?

ℹ Onelink can open the app if it is installed

## What happened instead?

ℹ Onelink redirects the user to the App Store, even though the app is already installed

## Please provide any other relevant information.

ℹ  I have completed all the configuration, and it works on my iPhone 12 running iOS 17.5.1. However, on my iPhone 11 with iOS 17.3, it does not.

**Comment by mostafahazim** [comment]
facing the same issue with  iphone 11 / IOS 17.6.1 using react-native-appsflyer@16.5.1. the link is opening the app store instead of the installed application
