### ISSUE TITLE
A problem occurred configuring project ':react-native-appsflyer'.

### ISSUE THREAD

**Issue by xx-git** [AppsFlyerSDK/appsflyer-react-native-plugin#590]
# Report
Running npx expo run:android failed
## Plugin Version

ℹ Please replace these two lines with the plugin version.
    "react-native-appsflyer@6.15.1"
    "expo": "~45.0.0",
    "expo-dev-client": "~0.9.5",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-appsflyer": "^6.15.1",
    "react-native-web": "0.17.7"
## On what Platform are you having the issue?

ℹ Please replace these two lines with the SDK version.
     android
## What did you do?
tried to run android locally react-native run-android
compile app in release mode in CI
ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`
npx expo run:android 
npm run addroid
ℹ Please replace these two lines with of what happened instead.  
```
* What went wrong:
A problem occurred configuring project ':react-native-appsflyer'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':react-native-appsflyer:classpath'.
      > Could not resolve com.android.tools.build:gradle:7.2.2.
        Required by:
            project :react-native-appsflyer
         > Could not resolve com.android.tools.build:gradle:7.2.2.
            > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/7.2.2/gradle-7.2.2.pom'.
               > Could not GET 'https://maven.google.com/com/android/tools/build/gradle/7.2.2/gradle-7.2.2.pom'.
                  > Connect to maven.google.com:443 [maven.google.com/142.250.204.46] failed: Connection timed out: no further information

```
## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by al-af** [comment]
Hi @xx-git,
Starting from AppsFlyer Android SDK v6.15.1, the following upgrades have been implemented:
	•	targetSDKVersion updated to 34
	•	Java updated to 17
	•	Gradle updated to 8.7

For more details, please refer to the [release notes](https://support.appsflyer.com/hc/en-us/articles/115001256006-AppsFlyer-Android-SDK-release-notes).
Kindly update your setup accordingly, and feel free to reach out to support if you need any assistance.
