### ISSUE TITLE
Is sendPushNotificationData supported?

### ISSUE THREAD

**Issue by aohua** [AppsFlyerSDK/appsflyer-react-native-plugin#75]
I couldn't find AppsFlyerLib.getInstance().sendPushNotificationData(this) in the sdk.

**Comment by stereodenis** [comment]
@af-fess will it be implemented?

**Comment by amit-kremer93** [comment]
Hi @aohua @stereodenis 
A new version has released with sendPushNotificationData api.
Thank you!
