### ISSUE TITLE
Please clarify if we need to add SingleInstallBroadcastReceiver in AndroidManifest.xml

### ISSUE THREAD

**Issue by gsunsnackv** [AppsFlyerSDK/appsflyer-react-native-plugin#83]
https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android#25-setting-the-broadcastreceiver-in-androidmanifestxml

Without this, I cannot pass the integration test using the integration test app. After I added this it passed smoothly.

But according to https://github.com/AppsFlyerSDK/react-native-appsflyer/issues/46 , we should not do this?

**Comment by BenjaminAF** [comment]
Hi @gsunsnackv ,

The `singleInstallBroadcastReceiver` Receiver is used to get the Google Play Store Install Referrer - specifically the `com.android.vending.INSTALL_REFERRER` action.

The Integration test app validates that functionality, so not having the receiver breaks the test flow.

As @af-fess said, our react-native integration makes use of Google's `com.android.installreferrer:installreferrer:1.0` library, which is a more recent method of obtaining the  Play Store Install Referrer.

Another possible solution to [#46](https://github.com/AppsFlyerSDK/react-native-appsflyer/issues/46)  would be using the `multipleBroadcastReceiver` which can process the `INSTALL_REFERRER` action and pass it on to other receivers in the AndroidManifest. However using the new referrer lib makes this redundant - as the referrer will be obtained anyway.

There is no effective need to use both solutions, but there is no limitation in doing so either.

**Comment by gsunsnackv** [comment]
Hi @BenjaminAF , thank you for the clarification. We have added SingleInstallBroadcastReceiver in AndroidManifest.xml , do we have to take it out?

**Comment by BenjaminAF** [comment]
@gsunsnackv 
You probably don't have to, but you can.

The only reason you would have to take it out is if it interferes with another receiver that is trying to get  the com.android.vending.INSTALL_REFERRER action.
Either way the new install referrer lib will obtain the referrer from Google.

**Comment by rmamtaventures** [comment]
SingleBroadcastReciver added in manifest but due to it crash on production app. Unable to instantiate receiver com.myapp.pkgname.SingleInstallBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "com.myapp.pkgname.SingleInstallBroadcastReceiver" on path:

**Comment by BenjaminAF** [comment]
@rmamtaventures the `com.myapp.pkgname` seems off in this case - AppsFlyer's SingleBroadCastReceiver is under `com.appsflyer` and should be added to the manifest as is:
```
        <receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">
        <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
        </intent-filter>
        </receiver>
```

Can you please share your Manifest code?
You can also open a support ticket with support@appsflyer.com ,if you do not wish to publicly share your App's manifest.
